### ISSUE TITLE
[Bug] Enabling certain options of the plug-in will crash

### ISSUE THREAD

**Issue by LaoYuan77** [YTLitePlus/YTLitePlus#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:iOS 14.3
- Device model:12Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...):TrollStore 1.5.1
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): latest 3.0.2

### Describe the bug

After YTLitePlus enables the hidden SponsorBlock button, YouTube will crash when it is closed and reopened. The IPA file of YouTube version 19.10.5 will crash. The mobile phone system version is 12Pro Max iOS 14.3.

### Steps to reproduce the issue

YouTube crashes whenever Hide SponsorBlock button is enabled

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Melon1921** [comment]
Thank you for this post, I had no idea what was the issue!  As long as isponsorblock is enabled every video I click on besides yt shorts crashes the app immediately. I'm on the latest version(19.21.3).

**Comment by bhackel** [comment]
This seems to be fixed in the latest version. Please note that you are talking about different issues. The original post is talking about the Hide SponsorBlock Button in Navigation Bar, whereas the newer comment is talking about a crash when having sponsorblock enabled in the app. These should both be fixed.
