### ISSUE TITLE
[Bug] Enabeling disable auto captions and play video's in fullscreen makes captions appear again

### ISSUE THREAD

**Issue by Macleykun** [YTLitePlus/YTLitePlus#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.4
- Device model: 9th gen ipad
- Sideload tool (AltStore, Sideloadly, TrollStore,...): sidestore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v19.10.5-3.0.1 - YTLitePlus

### Describe the bug

If you go into the ytlite section, toggle on the Disable auto captions and also toggle on Play video's in fullscreen.
When you open for example a mr beast video, it will display the subtitles while they shouldn't!
If you toggle off the play video's in fullscreen and start the closed video again, it won't show the subittles as expected.

### Steps to reproduce the issue

1. Toggle in ytlite disable auto captions and play video's in fullscreen
2. Play a recent mr beast video and see that captions still appear
3. (to verify the cc toggle does work) disable play video's in fullscreen and relaunch the video and see the captions are gone.

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Macleykun** [comment]
I wanted to try to compile only ytlite but i just couldn't figure the compile process out, therefore i wanted to check on you if you can recreate the same problem (using only ytlite in the latest yt version).

**Comment by Balackburn** [comment]
Just download the deb from the latest release and inject it in Youtube (decrypted) ipa, with pyzule https://github.com/asdfzxcvbn/pyzule (azule but better) or sideloadly. No need for compiling

**Comment by Macleykun** [comment]
yes thank you! it's super easy to use! made the issue here: https://github.com/dayanch96/YTLite/issues/92
