### ISSUE TITLE
[Suggestion] Is it possible to add a feature that blocks recommended videos that pop up after playing the video?

### ISSUE THREAD

**Issue by LaoYuan77** [YTLitePlus/YTLitePlus#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:iOS 14.3
- Device model:12 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...):TrollStore 1.5.1
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):latest 

### Describe the bug

![QQ图片20240321125651](https://github.com/YTLitePlus/YTLitePlus/assets/118520171/7718057e-f845-4456-a3af-eaa5785ca247)

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

✅ Yes, It does

**Comment by abheizthe** [comment]
please take a look on this settings…

Youtube - Settings - YTLiyePlus - Video Controls Overlay Options …
![868C44BA-F11E-4A27-9862-77AB4FFF4071](https://github.com/YTLitePlus/YTLitePlus/assets/54247318/d2f9a7c7-e307-41f3-94ec-121bf8c3f069)

**Comment by Balackburn** [comment]
Already present

**Comment by LaoYuan77** [comment]
Hello, since I am using the Chinese translated version of YouTube Plus, I am not sure whether the YTlite Plus function is the same as yours. I turned on the box selection function and did not block the recommended video that popped up at the end of the video.
![QQ图片20240323132941](https://github.com/YTLitePlus/YTLitePlus/assets/118520171/89be424c-f3c8-4daf-a9aa-5297aa8d504a)
![QQ图片20240323132913](https://github.com/YTLitePlus/YTLitePlus/assets/118520171/00733b24-f300-4a64-92b7-778bdf48bc3e)

**Comment by Balackburn** [comment]
Idk how do you have 3.0.2 version of YTLite as latest is 3.0.1 did you built it yourself?
And it's located in YTLitePlus settings not in YTLite
