### ISSUE TITLE
[question] Is PiP not automatically activated?

### ISSUE THREAD

**Issue by ev0tto** [YTLitePlus/YTLitePlus#107]
I have been using uYouEnhanced until now. Today, I discovered YTLitePlus and wanted to use it, but there is one issue. PiP doesn't automatically activate. You will understand if you watch a video. Is this a unique feature of uYouEnhanced? Or is there somewhere I can set it up? 
I am looking for a fanction to automatically transition to PiP like in the videos, not just a PiP button.

<details><summary>video</summary>

![](https://github.com/YTLitePlus/YTLitePlus/assets/80548883/5b1117eb-95aa-48b7-9a77-f8b2c562d194)

</details>

**Comment by Balackburn** [comment]
Settings<YouPiP
