### ISSUE TITLE
[Bug] SponsorBlock crashing app suddenly 

### ISSUE THREAD

**Issue by garshmo** [YTLitePlus/YTLitePlus#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.4.1
- Device model: iPhone 13 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v19.10.7-3.0.1

### Describe the bug

After days of no issue, SponsorBlock is crashing YouTube making it unable to play any videos, when turning off sponsor block the videos will play again 

### Steps to reproduce the issue

1. Have this version for a few days 
2. Have sponsor block enabled 
3. Eventually it makes YouTube unusable 

### Crash log (if the app crashes)

```shell
{
  "videoid" : "lGVaIJm_7Ek",
  "gfeedback" : {
    "e" : "23804281,23946420,23964928,23966208,23983296,23998056,24004644,24036947,24077241,24078297,24078311,24080738,24117491,24120417,24120819,24135310,24166867,24181174,24187377,24212199,24241378,24255545,24260378,24265964,24267188,24290971,24367823,24377598,24390675,24406318,24451319,24453274,24457316,24458684,24468724,24475159,24491186,24515034,24515423,24520674,24522874,24524098,24542367,24545212,24548627,24548629,24555431,24560416,24569425,24580219,24580808,24585133,24585737,24589977,24690006,24697067,24697122,39321705,39321709,39322687,39323850,39325413,39325978,51002041,51003636,51009781,51012659,51014091,51016856,51017346,51019626,51020570,51024932,51025415,51027870,51030101,51033399,51033492,51033765,51034629,51037330,51037344,51037353,51037540,51038803,51040445,51044725,51046127,51048236,51048489,51050361,51053689,51054999,51057846,51057855,51058724,51059573,51060353,51064366,51064835,51067700,51069269,51071073,51074183,51079301,51079315,51079992,51080128,51080342,51083232,51084279,51084290,51084521,51084677,51086809,51089175,51089441,51089956,51090385,51091899,51092660,51092916,51094173,51094200,51094205,51094721,51095387,51095478,51095536,51096293,51096646,51096989,51097829,51098775,51099406,51100401,51101454,51102344,51102756,51102775,51102791,51103088,51103519,51103858,51105799,51105868,51105993,51106916,51106995,51107336,51107658,51108006,51108626,51108975,51109077,51110160,51111704,51111738,51113656,51113663,51114247,51115164,51115184,51117319,51118293,51118932,51119199,51119290,51119653,51119935,51120275,51120546,51120589,51123073,51123410,51123457,51123540,51124104,51125717,51125857,51125901,51125903,51127129,51127956,51128585,51129060,51129105,51129208,51130230,51131840,51132393,51132535,51134507,51135346,51135654,51135665,51136218,51136459,51136785,51136843,51136977,51137185,51138513,51139378,51140749,51140947,51141038,51141537,51141541,51141691,51141798,51141867,51142566,51143428,51144925,51145070,51145587,51145727,51146434,51146737,51146963,51147046,51147521,51148974,51148985,51148995,51149304,51149481,51150230,51150503",
    "logged_in" : "1"
  },
  "player" : {
    "state" : 6,
    "ad" : "none",
    "audioitag" : "140",
    "xtags" : "",
    "adcpn" : "",
    "playertype" : "19",
    "isdrm" : "no",
    "videoitag" : "136",
    "ishls" : "no",
    "islocal" : "no",
    "connectiontype" : 3,
    "ismonetized" : "no",
    "ismuted" : "no",
    "errorscreen" : "no",
    "mobilecarrier" : "--",
    "qoeerrorcode" : "",
    "mlplayer" : {
      "type" : "hamplayer_queue",
      "docid" : "lGVaIJm_7Ek",
      "rate" : 1
    },
    "qoeerrordetails" : "",
    "resolution" : "720p"
  },
  "client" : {
    "cmodel" : "iPhone14,2",
    "cosver" : "17.4.1.21E236",
    "cver" : "19.10.7",
    "cbr" : "com.google.ios.youtube"
  },
  "date" : "2024-03-27 10:46:48 +0000"
}
```

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Strange that it happened suddenly after days of working completely fine, maybe it’s a memory leak, I’m not sure, but it’s definitely broken as of right now

**Comment by abheizthe** [comment]
most of users who using 19.10.7 having this issue on [Reddit](https://reddit.com/r/sideloaded/comments/1bp174s/sponsorblock_causing_crashes/)

try updated to 19.12.3. i'm usin this version and everything is fine

**Comment by garshmo** [comment]
> most of users who using 19.10.7 having this issue on [Reddit](https://reddit.com/r/sideloaded/comments/1bp174s/sponsorblock_causing_crashes/) (uYouPlus)
> 
> try updated to 19.12.3. i'm usin this version and everything is fine

Just tested on most recent app and tweak verison, still broken for me

**Comment by abheizthe** [comment]
> > most of users who using 19.10.7 having this issue on [Reddit](https://reddit.com/r/sideloaded/comments/1bp174s/sponsorblock_causing_crashes/) (uYouPlus)
> > try updated to 19.12.3. i'm usin this version and everything is fine
> 
> Just tested on most recent app and tweak verison, still broken for me

it's SponsorBlock issue (most of users got reported this to) just waitting for the fixed version of the tweak, or you can installing old YT version (due compability tweak and app version)

**Comment by Balackburn** [comment]
Fixed please build the app with latest commit
