### ISSUE TITLE
[question] How To disable Dynamic island when watching a video ?

### ISSUE THREAD

**Issue by engproali** [YTLitePlus/YTLitePlus#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.4.1
- Device model:iPhone 15 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...):esign
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):19.08.2-2.7

### Describe the bug

after enable backgroud playback on YTLite , Dynamic island is playing while watching the video its so annoying 

### Steps to reproduce the issue

1. 
2. 
3. 
![photo_2024-03-27_15-51-44](https://github.com/YTLitePlus/YTLitePlus/assets/31234999/64cf1dc8-ea50-4ffe-85ca-17ee92f8ae75)

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
I don't have a Dynamic Island device to test, can you test with latest version, and does this happens with other YouTube Tweaked apps too? Unfortunately I don't think their is any way to disable that I suppose this normal.

**Comment by engproali** [comment]
> to

i've tried another ipa tweaked with uYou it's the same , It would be great to have an option to disable that anouying island on portare mode

**Comment by GrPK** [comment]
To add to this issue - If I use AltStore, there is no problem with dynamic island. But if I use any other signing service, the dynamic island will show. I'm trying rn with AppDB using my own ceritficate and will see...
