### ISSUE TITLE
can't build due to submodule error

### ISSUE THREAD

**Issue by bachig26** [YTLitePlus/YTLitePlus#112]
@Balackburn if you can please have a look at this issue.

> Making all in Tweaks/YouQuality…
> Making all for tweak YouQuality…
==> Preprocessing Tweak.x…
Tweak.x:6:9: fatal error: '../YouTubeHeader/YTTypeStyle.h' file not found
==> Compiling Tweak.x (arm64)…
#import "../YouTubeHeader/YTTypeStyle.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/Users/runner/work/YTLitePlus/YTLitePlus/theos/makefiles/instance/rules.mk:280: /Users/runner/work/YTLitePlus/YTLitePlus/main/.theos/obj/arm64/Tweak.x.5c8f6426.o] Error 1
rm /Users/runner/work/YTLitePlus/YTLitePlus/main/.theos/obj/arm64/Tweak.x.m
make[3]: *** [/Users/runner/work/YTLitePlus/YTLitePlus/theos/makefiles/instance/library.mk:52: /Users/runner/work/YTLitePlus/YTLitePlus/main/.theos/obj/arm64/YouQuality.dylib] Error 2
make[2]: *** [/Users/runner/work/YTLitePlus/YTLitePlus/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make[1]: *** [/Users/runner/work/YTLitePlus/YTLitePlus/theos/makefiles/master/rules.mk:119: YouQuality.all.tweak.variables] Error 2
make: *** [/Users/runner/work/YTLitePlus/YTLitePlus/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2
Error: Process completed with exit code 2.

**Comment by 1Tdd** [comment]
Same👍🏼

**Comment by Balackburn** [comment]
Can you try again, I just tested and it worked as expected.

**Comment by 1Tdd** [comment]
Now it’s also working for me
