### ISSUE TITLE
[Bug] App crashes when viewing any YouTube video

### ISSUE THREAD

**Issue by Hann8n** [YTLitePlus/YTLitePlus#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5
- Device model: iPhone 13 and iPad 11in 2018
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore and Appdb
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.10.7

### Describe the bug

App crashes when tapping on any YouTube video. App does not crash for YouTube shorts.

### Steps to reproduce the issue

1. Open app
2. Click on YouTube video
3. 

### Crash log (if the app crashes)

```shell
{"app_name":"YouTube","timestamp":"2024-04-04 10:27:28.00 -0400","app_version":"19.05.5","slice_uuid":"a609f55d-469e-3bf5-9743-0dfdd1187a8f","build_version":"19.05.5","platform":2,"bundleID":"com.google.ios.youtube","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 17.5 (21F5048f)","roots_installed":0,"name":"YouTube","incident_id":"AE60E5FF-DDD7-47C4-ABE3-A8F7BFCE2BCE"}
{
  "uptime" : 110000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone14,5",
  "coalitionID" : 3295,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 17.5",
    "releaseType" : "Beta",
    "build" : "21F5048f"
```

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Playeereq** [comment]
Update to 19.12.3, it cant get any higher tho, 19.13.1 and 19.14.2 crashes if I click any vid.

**Comment by xzelleiv** [comment]
19.13.1 works for me

**Comment by Hann8n** [comment]
When I tired to update using the AltStore source it gave me this message: Install YTLitePlus Failed
NSCocoaErrorDomain 4
YTLitePlus could not be downloaded. The file doesn't exist.

**Comment by xzelleiv** [comment]
> When I tired to update using the AltStore source it gave me this message: Install YTLitePlus Failed NSCocoaErrorDomain 4 YTLitePlus could not be downloaded. The file doesn't exist.

have you tried esign?
