### ISSUE TITLE
[Bug] Cannot login v19.10.5-3.0.1

### ISSUE THREAD

**Issue by d0g4-c3m** [YTLitePlus/YTLitePlus#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iPadOS 17.1.1 (21B91)
- Device model: iPad Air (3rd gen)
- Sideload tool: Sidestore
- The specific version of YTLitePlus: v19.10.5-3.0.1

### Describe the bug

![IMG_2713](https://github.com/YTLitePlus/YTLitePlus/assets/77882595/842c23c1-9e4b-4f6d-9bbf-3954324fb43f)

I can’t login. That’s it.

### Steps to reproduce the issue

1. Click on the icon at top right
2. Click “login”
3. Enter your information

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

There is no faq…

**Comment by d0g4-c3m** [comment]
Turns out my version was v19.10.5-3.0.1 instead of v19.12.3-3.0.1, i don’t know why this has happened because i’ve clicked the “Download .ipa — Latest from Github” button at the site https://ytliteplus.github.io/

**Comment by samuelc02** [comment]
This thread is duplicated, go to https://github.com/YTLitePlus/YTLitePlus/issues/85 for solution

**Comment by Balackburn** [comment]
Fixed https://github.com/YTLitePlus/YTLitePlus/commit/ae2957dfcb67b9be1f6a7d9527829e2654906594
