### ISSUE TITLE
[Bug] Process completed with exit code 2.

### ISSUE THREAD

**Issue by Yunogamer** [YTLitePlus/YTLitePlus#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5 b1
- Device model: iPhone 14 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sidestore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 3.0.1

### Describe the bug

when trying to build, it fails saying "Process completed with exit code 2"

### Steps to reproduce the issue

1. ~
2. ~
3. ~

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
It's fixed could you try again thank you
