### ISSUE TITLE
[Bug] Merchandise ads are not removed

### ISSUE THREAD

**Issue by cooldude-91** [YTLitePlus/YTLitePlus#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.4.1
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): SideStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.14.3

### Describe the bug

Merchandise ads are still shown despite keeping the global remove ads option enabled.

Check the screenshot below
![IMG_6623](https://github.com/YTLitePlus/YTLitePlus/assets/156496036/c84bb778-9910-4352-a464-ffbbd215dde6)

### Steps to reproduce the issue

1. Open any channel which hosts merchant links to products.
2. It appears on their page

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

✅ Yes, It does

**Comment by Balackburn** [comment]
Not a bug, this isn't considered an ad
