### ISSUE TITLE
[Feature Request] Add YTClassicVideoQuality

### ISSUE THREAD

**Issue by rafaeldamasceno** [YTLitePlus/YTLitePlus#129]
Title is pretty self explanatory :) YouQuality is best when used with YTClassicVideoQuality, so it would be nice if it could be added to let us instantly choose the quality instead of navigating those weird YouTube options.

**Comment by abheizthe** [comment]
already have it. check YtLite settings - player - Classic video quality

still working on mine (Yt v.19.15.1)

**Comment by rafaeldamasceno** [comment]
Absolutely correct. Thanks for the help!
