### ISSUE TITLE
[Bug] Blank Spaces on the homepage and while scrolling

### ISSUE THREAD

**Issue by shahin365** [YTLitePlus/YTLitePlus#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.4.1
- Device model: 12 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore,...):
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): [19.14.3-3.0.1]

### Describe the bug

There is a blank space on the homepage as I open the app, videos start to appear if I scroll down, but there are blank spaces between videos as I scroll down. After a bit of digging, I found out that the ad block was causing this issue by displaying the ads as blank spaces which gets annoying. it seems the only workaround is disabling the ad-blocker by going to Settings > YTLite > General> toggle-off remove ads. (which is meant to only display in-app ads, but for some reason when I disable it, I get ads in the videos as well, and essentially makes YTLite useless). 
![IMG_7886](https://github.com/YTLitePlus/YTLitePlus/assets/16749755/1d881f2d-5925-485d-bd5e-79fe6dc45a0a)
![IMG_7887](https://github.com/YTLitePlus/YTLitePlus/assets/16749755/e876ca09-0f40-4d55-a3ee-50609a725d0e)
![IMG_7888](https://github.com/YTLitePlus/YTLitePlus/assets/16749755/dfe79ae4-48b4-49dc-82a8-1a7700ae8cdc)

### Steps to reproduce the issue

1. open YTLite
2. Scroll

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by haomuch** [comment]
Turn off remove ads in settings could fix it. Or wait for the next update.

**Comment by CSummerChild** [comment]
Disabling removing ads does fix the issue, but then it defeats the purpose of not wanting ads. Anyway to fix this?

**Comment by haomuch** [comment]
> Disabling removing ads does fix the issue, but then it defeats the purpose of not wanting ads. Anyway to fix this?

use uYouPlus Enhanced and spoofing the version to be 18.16.2

**Comment by Balackburn** [comment]
Duplicated with #116

**Comment by shahin365** [comment]
> Duplicated with #116

Do you know which version of YTLitePlus was the last one without this problem? It feels like this problem is getting worse with each update.

**Comment by Balackburn** [comment]
@shahin365 Try [v19.09.4-3.0.1](https://github.com/YTLitePlus/YTLitePlus/releases/tag/v19.09.4-3.0.1), it will be fixed in a future update, this is the biggest issue for now but their isn't any fix unfortunatly
