### ISSUE TITLE
[Bug] not seeing option to enable old quality selector 

### ISSUE THREAD

**Issue by geekysrm** [YTLitePlus/YTLitePlus#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: v17
- Device model: iphone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): sidestore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.16.3-3.0.1

### Describe the bug

I am not seeing option to enable old quality selector. How do i do that? Please see screenshots of  YTLite and YTLitePlus settings screens.
![IMG_1618](https://github.com/YTLitePlus/YTLitePlus/assets/10224804/e04f6959-1b67-432a-ade9-6be7144da6e8)
![IMG_1617](https://github.com/YTLitePlus/YTLitePlus/assets/10224804/8ef17034-ff27-4991-9692-4b1843f2d765)

### Steps to reproduce the issue

attached screenshots above 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by abheizthe** [comment]
on YTLite settings. tap on version info. activated "advance mode" option.
kill and reopen the Yt app. YtLite settings - player - classic video quality

**Comment by geekysrm** [comment]
Worked.
Thanks!
