### ISSUE TITLE
[Bug] remove the ipa from your releases (Bc of the DMCA)

### ISSUE THREAD

**Issue by Macleykun** [YTLitePlus/YTLitePlus#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:
- Device model:
- Sideload tool (AltStore, Sideloadly, TrollStore,...):
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):

### Describe the bug

Please remove the ipa on your latest and second latest release!
It would be incredible sad if this would get you in trouble

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Fixed

**Comment by Macleykun** [comment]
> Fixed

Happend again in your latest release I’m afraid!
