### ISSUE TITLE
[Bug] Ambient Mode not showing in fullscreen

### ISSUE THREAD

**Issue by michaelpopi1** [YTLitePlus/YTLitePlus#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.3
- Device model: iPhone 13
- Sideload tool: MapleSign
- The specific version of YTLitePlus: 19.17.2-3.0.1

### Describe the bug

When I’m in fullscreen mode on a video with Ambient Mode enabled, I’m not seeing Ambient Mode on the sides.
![IMG_4868](https://github.com/YTLitePlus/YTLitePlus/assets/99459598/236c5fc6-1321-44c3-844d-b205fdf0a1b4)

### Steps to reproduce the issue

1. Turn Ambient Mode on.
2. Open a video.
3. Make the video fullscreen.

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by bhackel** [comment]
This seems to be fixed in newer versions. If you are still having the issue, feel free to re-open this issue.
