### ISSUE TITLE
[Bug] Double Search bar bug

### ISSUE THREAD

**Issue by garshmo** [YTLitePlus/YTLitePlus#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.4.1
- Device model: iPhone 13 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.16.3_3.0.1

### Describe the bug

Weird double search bar UI problem, has a whole search bar directly under the search button

### Steps to reproduce the issue

1. sideload ytliteplus
2. open app
3. weird search bar shows on homepage
![IMG_5094](https://github.com/YTLitePlus/YTLitePlus/assets/109909393/9d47d0c1-a799-4407-bb56-3daecfbd7a3e)

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Impossible to reproduce for me, does it happens too with other modded app (e.g. uYouEnhanced)

**Comment by garshmo** [comment]
> Impossible to reproduce for me, does it happens too with other modded app (e.g. uYouEnhanced)

Not sure since this is the only tweaked version I ever use, it could be a new UI feature beta they are slowly rolling out server side, maybe because I’m using a tweaked version it fails to remove the old search with it, no settings I change make it go away, only makes sense that it’s YouTube trying out new UI for random people, kind of how Facebook does it
