### ISSUE TITLE
[Bug] Merchandise ads are not removed

### ISSUE THREAD

**Issue by cooldude-91** [YTLitePlus/YTLitePlus#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): SideStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.16.3

### Describe the bug

Merchandise ads are visible on the channel page. uYouEnhanced does not have them.
![IMG_6890](https://github.com/YTLitePlus/YTLitePlus/assets/156496036/3fc9dc9e-89de-422c-8596-b7c23d4e7c60)

### Steps to reproduce the issue

As shown in the screenshot

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
These aren't considered as ads

**Comment by cooldude-91** [comment]
Do we have any option to hide them?
