### ISSUE TITLE
[Bug] Delete player remix, clip, and download buttons do not work

### ISSUE THREAD

**Issue by naoto0826g** [YTLitePlus/YTLitePlus#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5
- Device model: iPhone 15
- Sideload tool (AltStore, Sideloadly, TrollStore,...): SideStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.19.5_3.0.1

### Describe the bug

It should have disappeared before, but it hasn't.

### Steps to reproduce the issue

1. Settings
2. YTLite
3. Player
4. Remove remix button, remove clip button, remove download button

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by StonkYT** [comment]
I found how to fix it!

Go to Youtube Settings
then go to “A/B” and enable it
Go back to settings
Go to “YouTube Plus”
Go to “Downloading”
Make sure both “Downloading manager” and “Add as YouTube Plus button” are on.

That’s what fixed it, at least for me.

**Comment by bhackel** [comment]
Hello, are these options removed from the latest version? I can't seem to find them

**Comment by bhackel** [comment]
Ah that is unfortunate, I will close the issue then
