### ISSUE TITLE
[Bug] translation is not active

### ISSUE THREAD

**Issue by ev0tto** [YTLitePlus/YTLitePlus#154]
I think this translations are not displayed correctly.

https://github.com/YTLitePlus/YTLitePlus/blob/a6e881fb84b6ddfe9af4ba60271567d25f17f3a7/lang/YTLitePlus.bundle/es.lproj/Localizable.strings#L27

![image](https://github.com/YTLitePlus/YTLitePlus/assets/80548883/3caf79f1-9755-4f12-b62b-8074fdf7b660)

**Comment by bhackel** [comment]
Sorry are you still having this issue?

**Comment by ev0tto** [comment]
yes, it does not solve
