### ISSUE TITLE
[Bug] Red progress bar not working

### ISSUE THREAD

**Issue by Deluxillo** [YTLitePlus/YTLitePlus#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:
- Device model:
- Sideload tool (AltStore, Sideloadly, TrollStore,...):
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):

### Describe the bug

still white

### Steps to reproduce the issue

1. color progress bar
2.
3. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Avakining** [comment]
I'm also having this issue. The progress bar is white in portrait mode but correctly is red in landscape.

**Comment by bhackel** [comment]
This seems to be fixed in newer versions, feel free to reopen if the issue persists.
