### ISSUE TITLE
Home screen is not displaying properly

### ISSUE THREAD

**Issue by tonysprenk** [YTLitePlus/YTLitePlus#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: 15 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): SideStore 
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.20.2-3.0.1

### Describe the bug

Nothing is loaded on the home tab until you start scrolling at which point content loads sporadically. 

### Steps to reproduce the issue

1. Open YouTube
2. Go to the home tab
3. Nothings is loaded
4. Start scrolling and some content loads and some does not

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Screen grab:

https://youtube.com/shorts/1t5YjMnck34?si=aqnkwNupD6Q6hBj5

**Comment by cobaltdisco** [comment]
Did you turn off Shorts?

**Comment by tonysprenk** [comment]
I tried that but it gives the same result

**Comment by Srat84** [comment]
I have it to.
When I disable the Adblock on YTlite is work fine.
But when a activate it y have nothing before 3 or 4 scrolling down.

**Comment by UBCK** [comment]
Same issue

**Comment by 42648594** [comment]
Same issue, and can confirm that @Srat84's solution works. Disabling "Remove Ads" in YTLite settings fixes the issue, and sideloading older builds results in the same issue.

**Comment by Gryzle** [comment]
Bump. Seems to be a backend change to YouTube in an attempt to thwart adblocking in-app.

**Comment by pgirzalsky** [comment]
There was a fix in the newest 4.0 release of YTLite which should address this issue. Please update YTLitePlus to use this version.

**Comment by Balackburn** [comment]
> There was a fix in the newest 4.0 release of YTLite which should address this issue. Please update YTLitePlus to use this version. 

I am waiting for @dayanch96 to push the commits, can't update as only the dev (not source code) was updated

**Comment by tonysprenk** [comment]
I guess Dan will not update YTLite source code… Now what?

![IMG_1100](https://github.com/YTLitePlus/YTLitePlus/assets/38426377/b2872baa-e8cb-4d74-8c10-c0adb8d2c2b2)

**Comment by Balackburn** [comment]
> I guess Dan will not update YTLite source code… Now what?
> 
> 
> 
> ![IMG_1100](https://github.com/YTLitePlus/YTLitePlus/assets/38426377/b2872baa-e8cb-4d74-8c10-c0adb8d2c2b2)
> 
> 

Don't ask him like that it's not correct! He will probably update the source when he wants. Also don't bother him with YTLitePlus, he isn't affiliated with this repo and probably annoyed that people confound the 2 repositories.

**Comment by tonysprenk** [comment]
I don't think I asked in a bad way. Will be great if YTLitePlus is updated to use deb directly. Thank you!

**Comment by Balackburn** [comment]
Fixed with latest release
