### ISSUE TITLE
Conflict between YTLitePlus and YouTube Plus common settings

### ISSUE THREAD

**Issue by bachig26** [YTLitePlus/YTLitePlus#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 15.8.2
- Device model: iPhone SE 1st Gen
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 4.0

### Describe the bug

I think if there’s a common/ similar functional settings between YTLitePlus and the YouTube Plus settings makes some conflict.

for example,
the issue with the hide shorts in Feed
> YouTube Plus Settings - Feed - Hide Shorts videos
> YTLite Plus Settings - Micellaneous - Hide Shorts (YTUnShorts)

It just interferes with each other.

Also I find a issue with Hide Subbar from YouTube Plus Navigation bar settings when the Hide Shorts is active. I’ll also open a issue at YTLite repo, if it’s a issue with Tweaks injected into YTLite Plus, please have a look.

### Steps to reproduce the issue

-

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Yes, these two are basically the same, will remove it in next release the YTLite option was broken but is no fixed

**Comment by bhackel** [comment]
Hey @Balackburn , is it possible for you to give me Triage permission so that I can start closing older issues? Thanks

**Comment by Balackburn** [comment]
> Hey @Balackburn , is it possible for you to give me Triage permission so that I can start closing older issues? Thanks

Added you as a colaborator

**Comment by bhackel** [comment]
> Added you as a colaborator

Hi @Balackburn I don’t think I have access still, can you try to add me again? Sorry about that

**Comment by Balackburn** [comment]
> > Added you as a colaborator
> 
> Hi @Balackburn I don’t think I have access still, can you try to add me again? Sorry about that

Should be good now?

**Comment by bhackel** [comment]
> 
> Should be good now?

Yep looks good now, thank you. I’m going to start closing older issues to clean up the reports.
