### ISSUE TITLE
[Bug] shorts video title dont match + comments or likes button are hidden

### ISSUE THREAD

**Issue by Joshua-18** [YTLitePlus/YTLitePlus#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.6.1
- Device model: iPad Pro (11-inch) (2nd generation) 
- Sideload tool (AltStore, Sideloadly, TrollStore,...): trollstore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 4.0

### Describe the bug

When watching shorts, the comments and likes are hidden now, and also after a few swaps the shorts title doesn’t match the video playing. 
![IMG_0711](https://github.com/YTLitePlus/YTLitePlus/assets/30993319/f77b1b2a-56e4-4b0f-8196-3c396cdf00f8)
![IMG_0712](https://github.com/YTLitePlus/YTLitePlus/assets/30993319/989cd989-0945-4770-aa3a-f35732f435cd)

### Steps to reproduce the issue

1. Watch shorts and keep swiping down 
2. Shorts video title shows for the next short
3. The ui hides like and dislike as well as the comments button. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Yes, for the gesture features why not have the two fingers swipe for brightness work on either the right or left side and have it also work for volume control but on one side, that way the single finger drag doesn’t conflict with the hold for speed option. ie brightness: two finger swipe on left side, volume: two finger swipe on right side.

**Comment by bhackel** [comment]
Are you still having this issue in the latest version?
