### ISSUE TITLE
[Bug] (iPad) youtube-native-share doesn’t work when using on an iPad or when using iPad layout

### ISSUE THREAD

**Issue by Macleykun** [YTLitePlus/YTLitePlus#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: iPad 9th gen
- Sideload tool (AltStore, Sideloadly, TrollStore,...): side store 
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v19.21.3-4.0

### Describe the bug

The [youtube-native-share](https://github.com/jkhsjdhjs/youtube-native-share) doesn’t work
 See: https://github.com/jkhsjdhjs/youtube-native-share?tab=readme-ov-file#what
If you toggle this tweak on/off it doesn’t change the style sheet.

### Steps to reproduce the issue

1. Navigate in YouTube Plus to interface.
2. In interface toggle Native share sheet ON.
3. Restart the app to be sure.
4. Observe no difference.

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

![IMG_1034](https://github.com/YTLitePlus/YTLitePlus/assets/26381427/4bf76f82-2c7e-4320-9ad2-c5e7bad66604)
![IMG_1033](https://github.com/YTLitePlus/YTLitePlus/assets/26381427/a6cdc854-f65f-4a38-8d3d-6f784ab96383)

![IMG_1035](https://github.com/YTLitePlus/YTLitePlus/assets/26381427/a8fc415b-2c49-4f77-9a52-d4ed7b024a0b)

**Comment by Macleykun** [comment]
> Same, but it does work on iPhones. (I used **iPhone Layout** from YTLitePlus Settings)
> 
> so I am assuming it might be incompatible with iPad Devices which is odd?

yup your fully correct! I'll adjust the issue name to reflect the actual root cause

**Comment by Macleykun** [comment]
heyo, it's fixed in the latest commit, but how did you guys add this tweak into ytliteplus actually? through git submodules or?

**Comment by Macleykun** [comment]
> > heyo, it's fixed in the latest commit
> 
> I don’t know what happened. I didn’t mess with it.
> 
> > but how did you guys add this tweak into ytliteplus actually? through git submodules or?
> 
> YTLite 4.0.1 Deb

Oh Nono I meant it’s fixed in the latest commit of that tweak! Not ytliteplus yet!
How can the Deb be updated to include in the latest yt native share?

**Comment by Macleykun** [comment]
@Balackburn 
i noticed here: https://github.com/YTLitePlus/YTLitePlus/blob/d9ccf7bad56bd47bc6ee86d4425f3be5a1b0d56f/YTLitePlus.xm#L120
that the native ios sharesheet can be used from the get go, sadly this doesn't seem to work for ipad.
But would it be possible to use this repo/commit to also use those hooks that the ipad uses? https://github.com/jkhsjdhjs/youtube-native-share/commit/8e3a6a98e8d04106d50ac828f7e5530ac42e8350

**Comment by Balackburn** [comment]
@Macleykun Will look into it later when I have time.

**Comment by Macleykun** [comment]
> @Macleykun Will look into it later when I have time.

Here's the PR from arichornlover so you have all the info what you need to update the extension (if you don't use submodules for it) https://github.com/jkhsjdhjs/youtube-native-share/pull/3/files

**Comment by Macleykun** [comment]
is it possible to re-open the issue meanwhile?

**Comment by Macleykun** [comment]
> Sure. I reopened it, but here’s a sneak peak of what it will look like on iPad. ![IMG_1954](https://private-user-images.githubusercontent.com/157071384/348844629-4cb3ceed-875b-47b3-90d0-aca14c1a926c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTUwNTQsIm5iZiI6MTcyMTExNDc1NCwicGF0aCI6Ii8xNTcwNzEzODQvMzQ4ODQ0NjI5LTRjYjNjZWVkLTg3NWItNDdiMy05MGQwLWFjYTE0YzFhOTI2Yy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDcyNTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTEzMGM5MWJjMzE3OGJlODg0ZmRlMmQ5YjY1MzI1MmYyYjZhOGYxNGQ4NTMxNTY5NWUwMGU1ZDBmY2E5OTE0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HOqCTUqc0fU3BDaUsGpZffMVsxG6cDShsNE64XVOe2Y) ![IMG_1955](https://private-user-images.githubusercontent.com/157071384/348844632-82c4efc0-cdac-45b3-bfe1-f1e0f1576247.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTUwNTQsIm5iZiI6MTcyMTExNDc1NCwicGF0aCI6Ii8xNTcwNzEzODQvMzQ4ODQ0NjMyLTgyYzRlZmMwLWNkYWMtNDViMy1iZmUxLWYxZTBmMTU3NjI0Ny5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDcyNTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZlNDcwMDIzYjQ5OTM1M2I4MDBhNTExZDdkYzMxZTgwYmJkNDQyYWY3ZDNhMjljMmM4OTVhODRhNGNlMzI3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tVNrtnwxNOFPqQkamosWSohU6Yf5is98cqSWtfj5Ai4) ![IMG_1956](https://private-user-images.githubusercontent.com/157071384/348844634-85df0f9e-7bbf-48e6-93c3-69ca9a01efe0.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTUwNTQsIm5iZiI6MTcyMTExNDc1NCwicGF0aCI6Ii8xNTcwNzEzODQvMzQ4ODQ0NjM0LTg1ZGYwZjllLTdiYmYtNDhlNi05M2MzLTY5Y2E5YTAxZWZlMC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDcyNTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmIzYmJlNWRhM2I0YzYzNTFkYjMwZWVhNzY1NmRmMGIxOWNhZGNkZjVlMDYyMjExMDNjN2Q3ZTY0MjFkYjcxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4ID1xmyeA18gtNMDcQ8JntmmWSAchfao-N446MdEO78)

Damn! That looks awsome! So much better then what google cooked up!

**Comment by bhackel** [comment]
This seems to be fixed in latest versions. Going to close, we can reopen if issue persists. Thank you

**Comment by reticivis-net** [comment]
It’s not fixed, I just downloaded a freshly cooked up ytliteplus ipa and I can’t share *anything* on iPad. The share sheet doesn’t even appear at all

**Comment by bhackel** [comment]
So there is no share interface showing with the Native Share off, and also no share interface when Native Share on?

**Comment by reticivis-net** [comment]
Yep, lemme record a video

**Comment by reticivis-net** [comment]
https://github.com/user-attachments/assets/17d5e0dd-96bb-49d8-9da6-9e6567ab6455

**Comment by bhackel** [comment]
Waiting for a possible fix from version 5 of YTLite
