### ISSUE TITLE
Hold to seek removed?

### ISSUE THREAD

**Issue by MaartenSomay** [YTLitePlus/YTLitePlus#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: Ios 17.5.1
- Device model: IP 14 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): esign
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.21.3-4.0

### Describe the bug

Hold to seek is not working anymore when updating to latest version. Hold and swipe left or right to control playback. 

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by kfur** [comment]
Disable "Hold to speed" in YtLite menu

**Comment by MaartenSomay** [comment]
> Disable "Hold to speed" in YtLite menu

Its disabled, still hold to deel doesnt work..

**Comment by tevyisertyin** [comment]
Can confirm that hold to seek is still missing in 19.23.3-4.0.1, whether or not hold to speed is disabled in YouTube Plus.

**Comment by MaartenSomay** [comment]
> Can confirm that hold to seek is still missing in 19.23.3-4.0.1, whether or not hold to speed is disabled in YouTube Plus.

I got a temp fix. Go to YtLitePlus -> Miscellaneous and put on these settings:
![IMG_0602](https://github.com/YTLitePlus/YTLitePlus/assets/37876797/d43a9b02-16b8-488a-aba4-ce8522bd4ed8)

Restart YT and you should have hold to seek.

**Comment by bhackel** [comment]
I am working on a tweak for this, will come in a few days to a week

**Comment by samuelawachie** [comment]
> I am working on a tweak for this, will come in a few days to a week
>
Oh, you're back. At last! Please did you get my pinged message to you? Oh, it must've been cleared with the removal of arichcorn's uYouEnhanced repo.
I was wondering if you were able to help us fix this new comment highlighter issue that we have here ( https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/issues/1 ). I was so impressed with how you worked on my "remaining time" issue that I had on the YouTube app, and I couldn't find someone more apt to ask for help from. I don't know if you use the Apollo app at all, but this is the only thing that the app is currently missing and the current dev/maintainer can't fix it. 
Could you just take a look please? We'd all be eternally in your debt.
