### ISSUE TITLE
[Bug] VP9 cause crash in short

### ISSUE THREAD

**Issue by colorzpe** [YTLitePlus/YTLitePlus#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 15.7.1
- Device model: iPhone 11 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Trollstore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v19.21.3-4.0

### Describe the bug

VP9 Cause Crashing Short video

### Steps to reproduce the issue

1. enable Vp9 decode in video quality preferences
2. restart apps
3. go to short tab and crash

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by mohkg1017** [comment]
They fixed this in the latest uYouEnhanced hopefully these guys can fix it here too

**Comment by bhackel** [comment]
If you are still having this problem, feel free to re-open this issue. I think something may be causing an older version of the shorts player to activate. Please reinstall with the latest commits to see if it fixes the issue.
