### ISSUE TITLE
error compiling exit code 2 

### ISSUE THREAD

**Issue by mohkg1017** [YTLitePlus/YTLitePlus#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

it wont compile exit code 2 

### Describe the bug

i try to compile like i do with every other page on here but it says exit code 2 failed compiling. 

### Steps to reproduce the issue

1. try to compile
2. wait
3. error code 2 exit failed 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

something is wrong it wont compile, give it a try

**Comment by Yunogamer** [comment]
```
Run wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa
2024-06-10 03:14:06 URL:https://************/com.google.ios.youtube-19.22.6-Decrypted.ipa [111183502/111183502] -> "main/YouTube.ipa" [1]
/Users/runner/work/_temp/010ec80e-40f2-4de9-9fd1-02bc65cfb6b3.sh: line 7: syntax error near unexpected token `>'
Error: Process completed with exit code 2.
```

broken again..will this ever work..?

**Comment by RuneCE** [comment]
> broken again..will this ever work..?

It seems like the developers have lost passion/motivation for this project, maybe the end is near for YTLitePlus...

**Comment by ElliotCHEN37** [comment]
> > broken again..will this ever work..?
> 
> It seems like the developers have lost passion/motivation for this project, maybe the end is near for YTLitePlus... They won't even fix core functionalities of it, like how ad blocking is breaking the App/ the UI ([1](https://github.com/YTLitePlus/YTLitePlus/issues/168), [2](https://github.com/YTLitePlus/YTLitePlus/issues/116)), and other issues.

if you're using the latest ver, these were fixed. (at least it works for me)

**Comment by RuneCE** [comment]
@ElliotCHEN37 "if you're using the latest ver, these were fixed. (at least it works for me)"
Latest version seems to be v19.22.6-4.0.1, which I am currently on, all the issues are still occurring persistently for me, unfortunately.

**Comment by Balackburn** [comment]
> > broken again..will this ever work..?
> 
> 
> 
> It seems like the developers have lost passion/motivation for this project, maybe the end is near for YTLitePlus...
> 
> They won't even fix core functionalities of it, like how ad blocking is breaking the App/ the UI ([1](https://github.com/YTLitePlus/YTLitePlus/issues/168), [2](https://github.com/YTLitePlus/YTLitePlus/issues/116)), and other issues.

Don't be so dramatic, a major update of YTLite was released last week (4.0) and it was updated yesterday, YTLitePlus is a all in one .ipa with more tweaks, I am not the developer of 99% of the functionality.

**Comment by ElliotCHEN37** [comment]
I mean v4.0, cuz I can’t build v4.1. So v4.0 is the latest available
version.

RuneCE ***@***.***>於 2024年6月10日 週一，15:41寫道：

**Comment by Balackburn** [comment]
> ```
> Run wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa
> 2024-06-10 03:14:06 URL:https://************/com.google.ios.youtube-19.22.6-Decrypted.ipa [111183502/111183502] -> "main/YouTube.ipa" [1]
> /Users/runner/work/_temp/010ec80e-40f2-4de9-9fd1-02bc65cfb6b3.sh: line 7: syntax error near unexpected token `>'
> Error: Process completed with exit code 2.
> ```
> 
> broken again..will this ever work..?

Fixed
