### ISSUE TITLE
[Bug] Downloaded videos can’t be opened in file browser or saved to album 

### ISSUE THREAD

**Issue by haomuch** [YTLitePlus/YTLitePlus#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: iPhone 15
- Sideload tool (AltStore)
- The specific version of YTLitePlus :19.22.6-4.0.1

### Describe the bug

It seems the downloaded video is encoded in an unsupported format that it can’t be opened after saved in the iOS file browser.

### Steps to reproduce the issue

1. Downloads a video
2. Save it to the iOS file app
3. Try to open the video in the file app but it only shows the file’s name

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by bhackel** [comment]
Having trouble replicating this, are you still having this issue? This is the process that I use: Download video, which saves it to photos. Open video in the Photos app. Press share button. Press Save to Files app. Then, I can see the full video in the files app.

**Comment by haomuch** [comment]
> Having trouble replicating this, are you still having this issue? This is the process that I use: Download video, which saves it to photos. Open video in the Photos app. Press share button. Press Save to Files app. Then, I can see the full video in the files app.

I have updated to the latest 19.29.1-4.0.1 version and still experience this issue. After I download video, I can't save it to photos as there is no such option. I can only share it to other apps or save it to the File app. In either way, I can't directly play the video after saving or sharing it.

**Comment by haomuch** [comment]
By the way, since I set VP9 codec for all resolutions, all the downloaded videos are in WebM format.

**Comment by bhackel** [comment]
VP9 for all is a buggy feature, so I will close this with the solution as disabling the setting. Thank you
