### ISSUE TITLE
VP9 Crashing issue fixed in uYouEnhanced maybe can use same fix

### ISSUE THREAD

**Issue by mohkg1017** [YTLitePlus/YTLitePlus#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:
- Device model:
- Sideload tool (AltStore, Sideloadly, TrollStore,...):
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):

### Describe the bug

Infamous VP9 Crashing issue was fixed yesterday in uYouEnhanced maybe you guys can use same fix please or ask them what fixed it?

### Steps to reproduce the issue

1. Turn on vp9 for HD
2. Play video
3. Crash

### Crash log (if the app crashes)

```shell
Infamous VP9 Crashing issue was fixed yesterday in uYouEnhanced maybe you guys can use same fix please or ask them what fixed it?
```

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Infamous VP9 Crashing issue was fixed yesterday in uYouEnhanced maybe you guys can use same fix please or ask them what fixed it?

**Comment by bhackel** [comment]
Should be fixed in latest version
