### ISSUE TITLE
[Bug] Ambient mode not activating when using OLED theme

### ISSUE THREAD

**Issue by Metercedes** [YTLitePlus/YTLitePlus#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1 (21F90)
- Device model: iPhone 14 Pro Max (A2894)
- Sideload tool (AltStore, Sideloadly, TrollStore,...): eSign
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.23.3_4.0.1

### Describe the bug

The ambient mode doesn't seem to be working.

### Steps to reproduce the issue

1. Open any video on YouTube.
2. Exit from fullscreen.
3. Examine if the ambient mode is working or not.

![IMG_1015](https://github.com/YTLitePlus/YTLitePlus/assets/51666146/88263143-faf1-4bf8-9b46-ac945baff8f6)

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

I am not entirely sure what causes that. But as theme mode, I enabled OLED and OLED Keyboard from YTLitePlus settings. But nothing changes even if I switch to the default theme settings. _(Every time I change the settings, I close the app completely (including the background), wait a while and then open it again.)_

**Comment by Ionutovic** [comment]
I have the exact same issue, ambient mode doesn't work so is not a big deal.
Dev 14 pro max

**Comment by bhackel** [comment]
Hello, are you all still having this issue in the latest version? I am having trouble replicating it

**Comment by Metercedes** [comment]
> Hello, are you all still having this issue in the latest version? I am having trouble replicating it

Mate, someone told me to disable OLED theme. It works only in that way.

**Comment by Metercedes** [comment]
> I have the exact same issue, ambient mode doesn't work so is not a big deal.
> Dev 14 pro max 
> 

Try to disable OLED.

**Comment by Ionutovic** [comment]
> Hello, are you all still having this issue in the latest version? I am having trouble replicating it

Yep

**Comment by Metercedes** [comment]
> > Hello, are you all still having this issue in the latest version? I am having trouble replicating it
> 
> Yep 

Disable OLED theme

**Comment by Balackburn** [comment]
> Hello, are you all still having this issue in the latest version? I am having trouble replicating it

The Oled / OLD Grey themes are really bugged, the OLED theme from YTLite is better.

**Comment by bhackel** [comment]
New builds will have the YTLite OLED setting removed. Thank you
