### ISSUE TITLE
[Bug] chromecast not found 

### ISSUE THREAD

**Issue by TheCodeboy12** [YTLitePlus/YTLitePlus#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5
- Device model: iPhone 15 pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): sidestore 
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.23.3-4.0.1

### Describe the bug

https://github.com/YTLitePlus/YTLitePlus/assets/88766663/4507e174-2c46-4662-a5e7-d455bf565679

hi, this video shows the issue 

### Steps to reproduce the issue

1. Try to connect to chromecast 
2. 
3. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Chrome cast is being found on the Google home app so the device is able to find it. Also, the local network privacy setting is on. Device is not connected to a VPN

**Comment by mitsos1os** [comment]
Exactly same thing happens to me with latest version while trying to cast to my LG TV YouTube app which works correctly with the native YouTube app. Also similar device specs and sideload with SideStore:

**Device info**

- iOS/iPadOS version: 17.5.1
- Device model: iPhone 15 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): sidestore
- The specific version of YTLitePlus (latest or newest is NOT a version number!): 19.23.3-4.0.1

**Comment by dextersnp** [comment]
Same here

**Comment by SSII77** [comment]
I can't cast to anything either, perpetually stuck searching for devices like in video above.  

Device info:

iOS/iPadOS version: 18.0
Device model: iPhone 15 Pro Max
Sideload tool (AltStore, Sideloadly, TrollStore,...): Sidestore
The specific version of YTLitePlus (latest or newest is NOT a version number!): 19.23.3-4.0.1

**Comment by bhackel** [comment]
Hello, can you try building with the latest version? I added a setting under Miscellaneous called Fix Casting that may or may not fix your issue. I do not have a chromecast to test with. Let me know if it works

**Comment by mitsos1os** [comment]
I tried using the latest version and build myself.
YouTube version for decrypted IPA used: 19.26.5

It still doesn't work but now I get this prompt instead of the previous one shown in the video in the original issue description:

![image](https://github.com/YTLitePlus/YTLitePlus/assets/8208733/6a09c75b-30fe-4625-9e47-7a9576ece87f)

Still no devices discovered...

**Comment by Macleykun** [comment]
> I tried using the latest version and build myself. YouTube version for decrypted IPA used: 19.26.5
> 
> It still doesn't work but now I get this prompt instead of the previous one shown in the video in the original issue description:
> 
> ![image](https://private-user-images.githubusercontent.com/8208733/347511519-6a09c75b-30fe-4625-9e47-7a9576ece87f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjUxMjYsIm5iZiI6MTcyMTQ2NDgyNiwicGF0aCI6Ii84MjA4NzMzLzM0NzUxMTUxOS02YTA5Yzc1Yi0zMGZlLTQ2MjUtOWU0Ny03YTk1NzZlY2U4N2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMDg0MDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzYzM2Q1M2I2ZjBlOGExYWM5MGJkNzlkNmZjZTY5ZDI1MjgwMzllYzNhODZmZDFmYzk5NDIwYTJmZjlkYjdlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._tch0AY8xrgXLVdpyckPaFgyxSXE_aWGh4SV6cGi_cc)
> 
> Still no devices discovered...

Could you try this one: https://github.com/arichornloverALT/uYouEnhanced there's in the uyouenhanced section a toggle to fix casting. I wonder if that one does work for you, if so we could look at the code what it does to fix that.

**Comment by Macleykun** [comment]
![IMG_1041](https://github.com/user-attachments/assets/c7337e35-209c-4278-9429-ff04acf5c371)
In the yt app > tab on your profile > gear icon > uYouEnhanced and look for the fix cast toggle and restart the app.

**Comment by bhackel** [comment]
> ![IMG_1041](https://private-user-images.githubusercontent.com/26381427/350677988-c7337e35-209c-4278-9429-ff04acf5c371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzAzMzksIm5iZiI6MTcyMTQ3MDAzOSwicGF0aCI6Ii8yNjM4MTQyNy8zNTA2Nzc5ODgtYzczMzdlMzUtMjA5Yy00Mjc4LTk0MjktZmYwNGFjZjVjMzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEwMDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NjMyZDk3NGE3OTJlYjUxYjc3NzBiY2UxNjk2ZTQwMzA0YmYxYzYzM2M3NmMzYmJmMjNhMTk4MjU1ZjU4NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XiErdMWvurPXSHPs0zgkW4qaR0RtFJ68kwGfb8_I1lM) In the yt app > tab on your profile > gear icon > uYouEnhanced and look for the fix cast toggle and restart the app.

Hello, I wrote the code that does the Fix Casting setting, and I added it to YTLitePlus already. It is under the Miscellaneous section of the settings.

**Comment by bhackel** [comment]
Please refer to #211 for future updates. That thread also has a workaround for chromecast devices. It seems airplay is fixed, but other casting methods are still having issues.
