### ISSUE TITLE
[Bug] Playlist only has one page

### ISSUE THREAD

**Issue by kumikooumae** [YTLitePlus/YTLitePlus#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: iPhone SE3
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v19.23.3-4.0.1

### Describe the bug

Playlist only has one page. Unable to scroll to load the second page. Enable old UI is a workaround.

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by bhackel** [comment]
I'm having trouble understanding the problem. Can you attach a screenshot or video recording please? Thanks
