### ISSUE TITLE
[Bug] (YouPiP) Download & Video Problem

### ISSUE THREAD

**Issue by RXNationGMG** [YTLitePlus/YTLitePlus#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 15.8.2
- Device model: iPhone 7 Plus
- Sideload tool (AltStore, Sideloadly, TrollStore,...): TrollStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.22.6

### Describe the bug

Whenever i tried downloading a video, it wouldn’t show any options, and if i tried downloading a video in the Shorts tab, it would crash. And if i ever play my video on the background and came back to YouTube, it gives me a black screen.

### Steps to reproduce the issue

1. ![16FDF4CA-1CFA-4BF4-B68C-BEC12BE8BD7B](https://github.com/YTLitePlus/YTLitePlus/assets/77547237/25ac5312-ec4a-486b-8413-a9b487cbcd16)
2. None
3. None

### Crash log (if the app crashes)

```shell
No crash logs was given.
```

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

None

**Comment by Balackburn** [comment]
Does it work with for you with YTLite alone?

**Comment by Balackburn** [comment]
Don't use the download button but the ytlite button and check if the download option is enabled in Youtube Plus Settings

**Comment by fwmaietta** [comment]
I am also having this same issue. A small grey bar appears at the bottom of the screen as if it's trying to show me the different resolutions to download, but no resolutions are listed so all you see is the top of the menu that is just barely visible. I have verified that Download Manager and Add as YouTube Plus button are checked. I also don't see a Download Manager button under the video, just the YouTube Plus button.

iOS 17.5.1 | iPhone 15 Pro Max | YTLitePlus_19.25.4_4.0.1.ipa

I have seen other modified YouTube IPAs have issues with downloading video and there was some mention that it could be the way they are signed or delivered. So I have tried signing using an Apple Developer Certificate and sideload using Xcode, an iOS Developer Certificate and sideload using Xcode, and iOS Distribution Certificate and installed OTA using google firebase. They all work to get the app installed and everything else seems to work but I can't download the videos. Any help or suggestions would be greatly appreciated. Thank you!!

**Comment by nanospearing** [comment]
Bumping this as I also am having the same issue with the latest release for SideStore on the latest stable iOS version.

**Comment by bhackel** [comment]
I found a workaround I think? If you enable YouTube Plus -> Downloading -> Add as YouTube Plus button, then the menu seems to work fine. I’m using signing service with default bundle ID.

**Comment by FrankTheTank07** [comment]
I saw this mentioned somewhere else and I can't remember where it was to give proper credit, but when I disabled YouPiP from Settings > YouPiP, the very top options says "Enabled". Make sure it us toggled off and then restarted the app. This allowed me to get the  download manager to open up and choose what quality I could download at. Hope this helps and If I find out where I found this information , I'll give proper credit. 
![IMG_3002](https://github.com/YTLitePlus/YTLitePlus/assets/51723011/da8e575c-988a-4c79-ad28-c49dcb08640d)

**Comment by bhackel** [comment]
Yes it worked for me too - I’m going to see if removing YouPiP will work, since YTLite may have a PiP option, not sure yet

**Comment by bhackel** [comment]
Hello everyone, I'm wondering if people are able to disable this setting in YouPiP (when YouPiP is enabled of course)
![image](https://github.com/user-attachments/assets/9d60a357-c2ae-44c6-adf2-ab4936b7f408)
Please let me know. You can provide the device information, which will also help.
- iPhone 15 Pro Max
- iOS 18b3
- Cannot Disable Legacy PiP

**Comment by bhackel** [comment]
Fixed by default in latest version
