### ISSUE TITLE
Can't access You page 

### ISSUE THREAD

**Issue by JudeTheTechSavvyDude** [YTLitePlus/YTLitePlus#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:18.0 Beta 1
- Device model:iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):19.23.3-4.0.1

### Describe the bug

I wanted to access my History so i can rewatch some of the videos that i was watching earlier and the You Button isn't there, and it gets annoying.

### Steps to reproduce the issue

1. Open YTLitePlus
2. Look on your bottom right corner 
3. No You Button 
![IMG_2719](https://github.com/YTLitePlus/YTLitePlus/assets/120291623/2405c948-ce3e-4df4-9285-43ee224456a3)

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Is there a fix to this?

**Comment by ahein22** [comment]
@JudeTheTechSavvyDude did you find a resolution to this? I'm running into a similar issue.

**Comment by JudeTheTechSavvyDude** [comment]
Yes i did figure it out, you have to hold the home down until it says You/Library has been restored

**Comment by ahein22** [comment]
Thanks!
