### ISSUE TITLE
[Bug] Navigation and Tab Bar Missing Certain Icons

### ISSUE THREAD

**Issue by justinw0681** [YTLitePlus/YTLitePlus#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: iPhone 13 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):

### Describe the bug

There is a blank grey rounded square on the left-most side on the navigation bar with missing cast button icon at the top: 
![Navigation Bar](https://github.com/YTLitePlus/YTLitePlus/assets/163300547/ba7b7436-cbdb-4e9e-bc11-e10e44b6624b)

Additionally, all of the icons except the library icon with the account profile picture is missing in the tab bar: 
![Tab Bar](https://github.com/YTLitePlus/YTLitePlus/assets/163300547/abc6a588-d418-4f94-9c04-e2432a6c785e)

### Steps to reproduce the issue

1. Compile the app
2. Sideload the app with AltStore
3. Open the app

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Please use 19.23.3 latest version of YT isn't compatible for now

**Comment by justinw0681** [comment]
Ok thank you, will try!

**Comment by justinw0681** [comment]
> Please use 19.23.3 latest version of YT isn't compatible for now

This fixes the issue.

**Comment by justinw0681** [comment]
> Please use 19.23.3 latest version of YT isn't compatible for now

This fixes the issue!

**Comment by pseudobacon** [comment]
I tried compiling today with 19.23.3 and it did not work. The app just crashes on startup
