### ISSUE TITLE
[Bug] Icons not showing throughout the UI

### ISSUE THREAD

**Issue by backstab5983** [YTLitePlus/YTLitePlus#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: iPhone 13 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.24.3-4.0.1

### Describe the bug

Opening the app or at any point navigating the menus no icons ever show in the bottom navigational row or for example in shorts

### Steps to reproduce the issue

1.  Open app
2.  Icons missing

![screen1](https://files.catbox.moe/hfev89.png)
![screen2](https://files.catbox.moe/06q3h1.png)

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Unfortunatly I can't reproduce this myself, did you enabled any options that you suspect could cause this?

**Comment by Balackburn** [comment]
> Along with that, Return YouTube Dislike must be disabled or it will crash

🤦‍♂️ My bad, I had it disabled and though latest commit fixed it, will remove this version.

**Comment by hzozo** [comment]
Same issues here.

**Comment by wiz-mayura** [comment]
https://github.com/arichornlover/uYouEnhanced/issues/733

**Comment by JudeTheTechSavvyDude** [comment]
Same is happening to me as well, before i was on the version V19.23.3-4.01 no issues what so ever, is there a fix for it coming soon?

**Comment by ne0dynamic** [comment]
Im having the same issue on mine that I just downloaded.

**Comment by Balackburn** [comment]
> Im having the same issue on mine that I just downloaded.
> 
> 
> 
> I am also unable to pause a short without it crashing.

Yes use the YT version from the latest released version of this repo (19.23.3) newer version aren't compatible yet.

**Comment by Balackburn** [comment]
Fixed

**Comment by Realsafe91** [comment]
Icons missing…version 19.26.5-3.0.4

**Comment by Realsafe91** [comment]
> > Icons missing…version 19.26.5-3.0.4
> 
> Update and rebuild the branch

This is the last update…rebuild the branch? What?
