### ISSUE TITLE
[Bug] YouTube links don’t open in app

### ISSUE THREAD

**Issue by miguelfsilvan** [YTLitePlus/YTLitePlus#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iPadOS 17.5.1
- Device model: iPad Air 4 (2020)
- Sideload tool (AltStore, Sideloadly, TrollStore,...): E-Sign
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 4.0.1

### Describe the bug

When I try to open a YouTube link, I expect it to open in my YouTube app. This works with the original app, but with YTLitePlus, the link opens in a browser window instead.

### Steps to reproduce the issue

1. Tap on any YouTube video link
2. Browser window will open not YouTube app

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Enable the "OpenYoutube" extension in the safari settings
