### ISSUE TITLE
[Bug] Crashing when clicking on any video or short

### ISSUE THREAD

**Issue by ThomasRuss** [YTLitePlus/YTLitePlus#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: iPhone 14
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.26.5-4.0.1

### Describe the bug

App instantly crashing when clicking on a video or short

https://github.com/YTLitePlus/YTLitePlus/assets/174258695/27741833-61e0-456d-824e-2527c403a405

### Steps to reproduce the issue

1. Click on a video or short
2. ...
3. ...

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

I've tried disabling and enabling some of the settings and restarting the app multiple times to no avail

**Comment by auddis** [comment]
You tried disabling return YouTube dislike? That’s what did it for me but I’m on 19.25.3 currently

**Comment by xnymphie** [comment]
> You tried disabling return YouTube dislike? That’s what did it for me but I’m on 19.25.3 currently

thank you! I was having the same issue and thought it was sponsorblock. it did turn out to be the dislike button

**Comment by itsdstar** [comment]
> You tried disabling return YouTube dislike? That’s what did it for me but I’m on 19.25.3 currently

Yes I did that but it didn't work, but I disabled iSponsor Block and it did the trick.

**Comment by bhackel** [comment]
Should be fixed in new versions, feel free to re-open if it is not.
