### ISSUE TITLE
App crashes when exiting full screen mode

### ISSUE THREAD

**Issue by vamp1r7771** [YTLitePlus/YTLitePlus#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: ios 14.4.2
- Device model:i6s
- Sideload tool (AltStore, Sideloadly, TrollStore,...):
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):4.0.1

### Describe the bug

Application crashes when exiting full screen mode

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by bhackel** [comment]
Hello, can you attach the crashlog contents? (iPhone settings -> Privacy -> Analytics -> Analytics Data -> Scroll to the latest one)
