### ISSUE TITLE
[Bug] Dynamic island appearing when using background playback

### ISSUE THREAD

**Issue by GrPK** [YTLitePlus/YTLitePlus#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: IOS 18
- Device model:15PM
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Own Certificate & Signoulous
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.23.3

### Describe the bug

Hello! Probably it is known that whenever someone sideload an YT app with Notification Entitlements, there is a bug where the Dynamic Island is always on and the specific functions won't work. A temporary fix would be to have both original YT for notification and the modded one for general use, but this rises other problems.

After some trial and error, I am 99% confident that the bug occurs because of the "Background Playback" mode that let non-premium users to use that function.

I want to further test my hypothesis, but I really don't know how to compile the app without that mod. Can someone point out what do I need to remove in order not to have that mod? 

Also, if the devs needs further testing for this bug, I am more than happy to help them find out a fix for this issue.

Thanks in advance!

### Steps to reproduce the issue

Use the YT app normally. [Example](https://www.reddit.com/r/sideloaded/comments/1bnmyqv/youtube_and_dynamic_island_bug/)

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by bhackel** [comment]
You can disable background playback in the YouTube Plus settings menu under Player. However, if you are trying to remove YTLite from the app, it is a bit more involved. The two files that you would need to focus on are the Makefile and the .github/workflows/buildapp.yml. I'm not sure about the specifics, but in the makefile, you would want to delete anything involving YTLite (but keep anything with YTLitePlus). In the workflow, you would want to delete the lines in the stage titled "Prepare YouTube iPA" that download YTLite, and probably in some other places.

**Comment by bhackel** [comment]
I’m curious if you found anything new with this bug

**Comment by GrPK** [comment]
Hey, sorry for not answering sooner, having finals and all stuff...

Nope, it still didn't work, the Dynamic Island is still appearing while in app. 

Some people say that this happens because the DI entitlements can't be set-up while sideloading, but that isn't true -> For example, a modded Instagram IPA can use the DI as expected, without any problems.

I don't lnow if there is any developer with DI devices, but I am willing to test different things if anyone tries to fix this damn bug.

As I said, I'm pretty confident that the background thingy is the root of the problem

**Comment by bhackel** [comment]
Oh do you know if that modded instagram iPA happens to be open-source? Then we could take a look at how they do their background playback. Thanks for the ideas

**Comment by GrPK** [comment]
Unfortunately, it isn't. You can try any mod that you can find [here ](https://github.com/swaggyP36000/TrollStore-IPAs). Or Facebook Wolf IPA, it works as well with DI.
