### ISSUE TITLE
[Feature Request] Plz add some kind of Download manager where downloaded Videos/Audio can stay with in app & Volume gesture

### ISSUE THREAD

**Issue by Blockr22** [YTLitePlus/YTLitePlus#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: IPhone 14
- Sideload tool (SideStore)
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.23.3-4.0.1

### Describe the bug

Not a bug but a feature request.
1. Volume gesture- change volume when sliding at the top of the screen going left & right like that un uYouEnhanced
2. Download manager like uYou where downloaded videos/Audio’s go after being downloaded. So that we don’t have to leave the app to find & play files. Now it’s just little bit annoying that it save videos in files app.
3. Other than that i think it works great & fast downloading is great. I would switch to this app from uYouEnhanced if it gets these features
4. Thnx

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
This will not be done, otherwise ask on the YTLite Github from dayanch96 as this feature come from his tweak

**Comment by bhackel** [comment]
Video manager not very likely because of file issues with the side loading methods (some methods work, some don’t, like uYou). Volume gesture is possible and I hope to do it soon.

**Comment by Blockr22** [comment]
Thnx, appreciate the volume gesture but right now with the manager videos saves to files app & it’s an extra step to go find & they play through VLC player. I think i will stick to uYouEnhanced until manager is a thing in this tweak. But thankyou very much for even responding & great work here. So many people love & recommend your tweak on reddit

**Comment by eliliam** [comment]
Would also love to see a volume gesture added, it's the last remaining feature in other apps(like uYouPlus) that is not yet present in this app
