### ISSUE TITLE
workflow issue [due to recent submodule]

### ISSUE THREAD

**Issue by bachig26** [YTLitePlus/YTLitePlus#222]
updated submodules: https://github.com/bachig26/YTLitePlus/commit/c323470b200cb6ff28787bc9a67011230cf2ce3f

workflow run/artifacts: https://github.com/bachig26/YTLitePlus/actions/runs/9842838051

@Balackburn @arichornloverALT after updating to this recent submodules, 

1. the workflow doesn't release the ipa to `Releases` section.
2. zip extension is applied to the artifact instead of ipa extension.
3. when replaced the extension and ran with altstore, it can't able to installed. i got an error like `the operation can't be completed.` something like this.

**Comment by Balackburn** [comment]
1. Did you checked the "Create a draft release" option?
2. The artifact always was a .zip with the .ipa inside
3. What do you mean by when replaced the extension?

**Comment by bachig26** [comment]
> 1. Did you checked the "Create a draft release" option?

yes

> 2. The artifact always was a .zip with the .ipa inside

hmm. i remember whenever i downloaded the ytliteplus artifact or package from release, it always was in ipa extension.

> 3. What do you mean by when replaced the extension?

by manually changing the extension from .zip to .ipa

**Comment by bachig26** [comment]
maybe i'll sync the repo to the new pr and run again.

**Comment by Balackburn** [comment]
> > 1. Did you checked the "Create a draft release" option?
> 
> yes. fyi, i didn't check it in the attached workflow but later i did and i removed that workflow which i forgot to attach here.
> 
> > 2. The artifact always was a .zip with the .ipa inside
> 
> hmm. i remember whenever i downloaded the ytliteplus artifact or package from release, it always was in ipa extension.
> 
> > 3. What do you mean by when replaced the extension?
> 
> by manually changing the extension from .zip to .ipa

You should just extract the .zip the .ipa is comressed inside, renaming the .zip to .ipa will not work.
