### ISSUE TITLE
[Bug] Ad/shorts block not wokring with new home tab UI

### ISSUE THREAD

**Issue by NotSpicyMan** [YTLitePlus/YTLitePlus#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sidestore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v19.23.3-4.0.1

### Describe the bug

The new Home tab UI that YouTube is rolling out breaks the block ads and block shorts functionalities when first booting up the app. A temporary solution I found is if I open a video, then close it, and reload the home tab, then the blocking works until I reboot again.

### Steps to reproduce the issue

(I know youtube is rolling out the new home tab slowly, so I'm not sure if anyone else's account has the changes at the moment)
1. Enable block ads/shorts in settings
2. Reboot the app
3. Open the home tab

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by bhackel** [comment]
Hello can you attach a picture of this new home tab UI? I think I have heard of it but I want to make sure it is the same one.
