### ISSUE TITLE
[Request] iOS 14 EoL question

### ISSUE THREAD

**Issue by juins1** [YTLitePlus/YTLitePlus#235]
Is it possible you can add a 19.20.2 release for YTLplus 4.0.1 ? 
Ive only seen a 3.0.1 one online but home screen is broken/blank and ads go thru once in a while.
Worth asking since 19.20.2 is EoL for YT on iOS 14 and its worth having an updated version for iOS 14 devices

**Comment by bhackel** [comment]
You can probably build one yourself using your own iPA. If you can’t obtain a raw 19.20.2 iPA, let me know

**Comment by juins1** [comment]
@bhackel ive tried building before but it wouldnt work. Trolldecrypted the ipa and went from there, but nothing. Also looked to see if there was a .deb for YTliteplus 4.0.1 but i only found one for YTlite which seems different... less features and ads come thru every now and then. And lastly, the inquiry was so that the release would be permanently on the releases page, for easy installations thru altstore, trollapps, etc

**Comment by juins1** [comment]
ugh i clicked on close as completed by accident.

**Comment by bhackel** [comment]
Ah I see, I think the idea is good since there are a lot of people still on iOS 14. I will work on getting a version out in a day or two hopefully

**Comment by juins1** [comment]
@bhackel awesome, thank you!

**Comment by bhackel** [comment]
Hey I’m having crashes on my 19.20.2 iPA at the moment, so I think my decryption method (Trolldecrypt) might be buggy. I’m planning to use bagbak (worked for my 19.26 iPA), which requires palera1n to work, but I won’t have time to set that up again before my trip this weekend. I’ll try to have it out on Monday

**Comment by juins1** [comment]
@bhackel i can provide one if needed, from an SE1 on 14.2. Let me know and can post a 1-time download file.io link

**Comment by juins1** [comment]
hi @bhackel , just circling around to this. Is an updated ios14 (19.20.2 + 4.0.1) build still planned?

**Comment by bhackel** [comment]
Yes someone this week hopefully

**Comment by bhackel** [comment]
@juins1 can you try installing this build and see if it works without crash: https://github.com/bhackel/YTLitePlus/actions/runs/10012380149

**Comment by juins1** [comment]
@bhackel Worked! Tried loading some videos and everything... all good. no blank home screen either like before

**Comment by bhackel** [comment]
Nice, I’ll keep this open for about a week, and if there are no more issues, then I will close it

**Comment by bhackel** [comment]
There is a new tool out called TrollFools https://github.com/Lessica/TrollFools. It supports injecting dylibs into AppStore apps rather than requiring sideload of an iPA. I think that it should be possible to build a dylib from future releases so that you can easily inject into the older YouTube version without needing to build a new iPA each time.

**Comment by juins1** [comment]
@bhackel , hey.. i messed around with it yesterday on my main ios 16 phone but seems you can only inject dylibs, not debs

**Comment by bhackel** [comment]
I'm working on a fix for Trolldecrypt iPAs. For me, it had to do with UISupportedDevices. Maybe that will fix it for you as well.
