### ISSUE TITLE
shorts are super blurry, anyway to fix it or add a default shorts quality option?

### ISSUE THREAD

**Issue by mohkg1017** [YTLitePlus/YTLitePlus#239]
shorts are super blurry like blurrier then stock youtube, anyway to fix it or add a default shorts quality option?

**Comment by epic-bruh-moment** [comment]
Having same issue, reopen this in proper format then you'll get support

**Comment by mohkg1017** [comment]
> Having same issue, reopen this in proper format then you'll get support

done
