### ISSUE TITLE
[Bug] background video shows black screen when reopened

### ISSUE THREAD

**Issue by yairtu** [YTLitePlus/YTLitePlus#242]
https://github.com/user-attachments/assets/8da75c4d-474f-4a41-869c-0bb04bf76622

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: 
- Sideload tool: Sideloadly
- The specific version of YTLitePlus: 19.26.5-4.0.1 but happened in previous versions as well

### Describe the bug

When swiping down on the video (for example to continue browsing for other videos) then exiting out of the app so it is in the background, the video shows a black screen until the video is closed and re-opened. 

### Steps to reproduce the issue

1. Play video
2. Swipe down on the video so it’s minimized in the bar at the bottom
3. Swipe up out of the app so it is in background 
4. Re-open app and check video 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by yairtu** [comment]
https://github.com/user-attachments/assets/04c07f53-0af5-440b-b0fc-d045da9e822f

**Comment by ExtNinja2099** [comment]
This also happens when switching from shorts in the video feed below back to the main video player screen. Both shorts and video go black

Shorts video can go back by changing short and swiping up to go back. But the main video stays black until you close and reopen in history menu

**Comment by TheKivster** [comment]
Me too

**Comment by ExtNinja2099** [comment]
> Me too

Latest code has fixed this bug. Try using actions and workflow to build with 19.28.1. The bug is basically gone
