### ISSUE TITLE
[Bug] Shorts are blurry when opening

### ISSUE THREAD

**Issue by mohkg1017** [YTLitePlus/YTLitePlus#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: 15 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): esign/gbox
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): latest

### Describe the bug

shorts are super blurry, anyway to fix it or add a default shorts quality option?

### Steps to reproduce the issue

1. go to shorts
2. scroll through and you'll notice the shorts are super blurry for some reason
3. doesn't happen on normal youtube from appstore 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by abheizthe** [comment]
Indeed, i've facing it on YT 19.26x - 19.28.1
There's an option to set the quality of shorts but, it's doesn't work when scrolling to another shorts videos
If possible, make an option default shorts quality videos

thank you

**Comment by bhackel** [comment]
Can you try disabling YouPiP and seeing if the issue persists?

**Comment by abheizthe** [comment]
> Can you try disabling YouPiP and seeing if the issue persists?

After forcing closed and reopen YT app, i think it's now working with default settings from YtPlus playback quality

ps; injecting/ replacing to v1.8.14 of YouPiP

**Comment by epic-bruh-moment** [comment]
> Can you try disabling YouPiP and seeing if the issue persists?

I have YouPiP disabled cause I hate bg playback but I am still encountering the issue

**Comment by mohkg1017** [comment]
Youpip is off and i still have the same issue

**Comment by mohkg1017** [comment]
The vp9 trick worked, it defaults shorts to 480p on a 1.2gbps connection.... Any way to add a option to set the default quality of shorts?

**Comment by schweppes-0x** [comment]
same issue here. Turning off the "VP9 for all" option worked and defaults the quality to 480p. But still it would be nice to have the option to be able to set the default quality for shorts

**Comment by bhackel** [comment]
I will close this and mark the solution as disabling VP9 for all. Thinking about disabling this setting entirely since it causes many issues in the app (and its not supported when sideloading with non-trollstore methods). Thank you
