### ISSUE TITLE
Pause on overlay app crash

### ISSUE THREAD

**Issue by PerkedheL** [YTLitePlus/YTLitePlus#252]
https://github.com/user-attachments/assets/fb6049fc-f8eb-4552-aa24-05a0ddef8fe5

**Comment by bhackel** [comment]
Can you attach the crash log? Use the bug template when creating the issue next time please, it helps us solve the problem.

**Comment by bhackel** [comment]
Can you try building with the latest commits and seeing if you still have the issue? I'm having trouble replicating the problem
