### ISSUE TITLE
[Request] Add in-app Downloads player

### ISSUE THREAD

**Issue by TechnicallyJackson** [YTLitePlus/YTLitePlus#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

I would like videos to be added directly to YouTube (like in YT Premium) because I like the YouTube UI better than VLC or the others

**Comment by rlaboy777** [comment]
X2

**Comment by bhackel** [comment]
This is a basic video player that is buried in the settings menu - Currently looking for feedback on the functionality, and also going to wait for YTLite version 5 before making any more major changes to it.

**Comment by samuelawachie** [comment]
> This is a basic video player that is buried in the settings menu - Currently looking for feedback on the functionality, and also going to wait for YTLite version 5 before making any more major changes to it.

>
Do these guys know that if you install YTLitePlus over uYouEnhanced, the video rendering is by the YouTube app and no need to use VLC or whatever? The only time you need to use an external app like VLC is if you download the video to folder, or specifically tell it to play by that application from the "Download" page in YTL+ settings. 
Or maybe I'm missing the point..
