### ISSUE TITLE
[Bug] Exit code 2 (stops at injecting dependancies)

### ISSUE THREAD

**Issue by y4wnn** [YTLitePlus/YTLitePlus#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.5.1

### Device model

iPhone 13

### Sideload method

AltStore

### Tweak version

YTLitePlus - 19.23.3 - 4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

Process completed with exit code 2.

### Steps to reproduce the issue

1. Fork repo and start action as usual with IPA link
2. Fix compiling & build package process takes over an hour and ultimately fails with exit code 2

### Additional context

Also tried with YouTube 19.22.6 IPA

**Comment by y4wnn** [comment]
<img width="1309" alt="image" src="https://github.com/user-attachments/assets/581a0ba1-c510-4cfd-b687-4fc888dae99b">

**Comment by bhackel** [comment]
I see your branch is behind on commits. Try going to the main page of your fork and updating the commits.

**Comment by y4wnn** [comment]
hi...I hate to have to report this, but although I have seen your newer commit and synced my fork, it seems my run still failed: ![image](https://github.com/user-attachments/assets/f8086287-218d-4447-b2f8-1849e6719390)
any additional help would be appreciated, thank you!

**Comment by bhackel** [comment]
Hey no worries, I am having trouble replicating the issue. I am wondering where you found your base YouTube iPA. You can download my build from here: https://github.com/bhackel/YTLitePlus/actions/runs/10023991003/job/27705515832

**Comment by y4wnn** [comment]
> Hey no worries, I am having trouble replicating the issue. I am wondering where you found your base YouTube iPA. You can download my build from here: https://github.com/bhackel/YTLitePlus/actions/runs/10023991003

thank you for your build link! I have checked out others' forks and they did just fine too, so I was also suspecting my source. I used the catbox download link on YT Lite Plus' website, then pasted (what seems to be) the new YT IPA version stated in the release section (pmsw97 dot ipa), as such:
  YOUTUBE_URL: https://files.catbox.moe/pmsw97.ipa

**Comment by bhackel** [comment]
Ah I see, the Catbox link on the website is already injected with tweaks, so you can install that one directly. No need to re-inject the tweaks

**Comment by y4wnn** [comment]
> Ah I see, the Catbox link on the website is already injected with tweaks, so you can install that one directly. No need to re-inject the tweaks

oh! I should've figured that 😅 Thank you so much then, have a nice day
