### ISSUE TITLE
Error code 2 while building the latest commits 

### ISSUE THREAD

**Issue by Tomithan** [YTLitePlus/YTLitePlus#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

IOS 18.0

### Device model

Iphone 12 Pro

### Sideload method

Esign

### Tweak version

YTLitePlus-19.29.1-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/df921fce-f6be-4a1e-a28b-b84c3151b914">

### Steps to reproduce the issue

1. 
2. 
3. 

### Additional context

Don't eat my content error.

**Comment by mohkg1017** [comment]
same

**Comment by mohkg1017** [comment]
i see a commit was made 15 minutes ago...i tried again still error code 2

**Comment by Skawtnyc** [comment]
This looks like theos GitHub no longer has the necessary file. Any way to fix that or work around it? To be honest, I wouldn’t mind having the ability to select checkboxes for which modules we want compiled into the ipa. I could bypass a lot of these errors by not having these external modules in the first place.

**Comment by bhackel** [comment]
For devs: We need to add YTHeader (foxter’s fork) as a submodule

**Comment by joseyskindaweird** [comment]
got the same issue here
![image](https://github.com/user-attachments/assets/537ff91c-b605-4eeb-b728-c9f6d836fa1d)

**Comment by bhackel** [comment]
Fixed in latest, thank you @Balackburn
