### ISSUE TITLE
[Bug] Cannot expand Community Post images

### ISSUE THREAD

**Issue by bhackel** [YTLitePlus/YTLitePlus#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18b3

### Device model

iPhone 15 Pro Max

### Sideload method

Maplesign

### Tweak version

YTLitePlus 19.26.2-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

When tapping an image on a community post, the image used to expand to show the full image. However, YouTube recently changed it (in 19.09 for me) so that the image is displayed in full screen. For some reason, the side loaded version of YouTube does not support this.

### Steps to reproduce the issue

1. Go to a channel with community posts of non-square images (https://youtube.com/@kylehill/community)
2. Tap on the image
3. Nothing happens

### Additional context

I am hoping to investigate this bug by testing what happens when I sideload YouTube with no tweaks, and when I inject tweaks into a stock YouTube app.

**Comment by A-Gigabyte-Of-RAM** [comment]
Spoof to 18.34.5 for a temp fix

**Comment by UrDone4** [comment]
> Spoof to 18.34.5 for a temp fix

Also having this issue. Can you provide more instructions on how to do this? Is this a setting, or do we need to change something before we do the build action?

**Comment by A-Gigabyte-Of-RAM** [comment]
> > Spoof to 18.34.5 for a temp fix
> 
> Also having this issue. Can you provide more instructions on how to do this? Is this a setting, or do we need to change something before we do the build action?

Settings > YTLitePlus > Miscellaneous > Scroll to bottom > Click “Version Spoofer Picker”, then 18.34.5 > Go back to previous page and click “Enable App Version Spoofer (Lite)” > Restart app

**Comment by Proaxel** [comment]
> Settings > YTLitePlus > Miscellaneous > Scroll to bottom > Click “Version Spoofer Picker”, then 18.34.5 > Go back to previous page and click “Enable App Version Spoofer (Lite)” > Restart app

Thanks a lot, this issue was driving me a bit crazy

**Comment by dayanch96** [comment]
google removed this with their server-side updates hopefully they will fix it in the future. 5.1 coming with the feature to show posts in fullscreen window. closing this issue since it has nothing to do with the tweak

**Comment by Sirlink360** [comment]
Update: do not try this fix.  I think Windows has cracked down on "reversing updates" since this post has been made and it made my entire YTliteplus app error out without anyway to access the settings.
