### ISSUE TITLE
[Request] Always select default audio track

### ISSUE THREAD

**Issue by ywj515** [YTLitePlus/YTLitePlus#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

Whenever I watch a video with multi-language audio tracks, usually my speaking language is selected, and sometimes it chooses a completely wrong language that I can't even understand. It's very annoying to revert back to the original audio track. I want to have a option to always select the OG audio track.
Thanks.

**Comment by dora727** [comment]
i think dan (the dev of ytlite) made it (he posted abt that on his x/twitter)
but yeah understandable, sometimes i watch mrbeast short and they play as russian which isn’t my language (and can’t even change💀)

**Comment by bhackel** [comment]
That's cool to see that Dan has implemented it in v5. Here is the link: https://x.com/Dayanch96/status/1815052388220219415. We will wait for the public release then.
