### ISSUE TITLE
Interface issues 

### ISSUE THREAD

**Issue by Magichouse227** [YTLitePlus/YTLitePlus#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.0

### Device model

iPhone 11 PM 

### Sideload method

Esign / paid certificate 

### Tweak version

YouTubeliteplus 19.29.1 - 4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

I have the settings to remove Save button, remix button and stock download button & report button enabled on Interface but it still shows under the video 

![IMG_4839](https://github.com/user-attachments/assets/2eb1b8e8-ae44-4c32-9bd1-825a68490c01)

https://github.com/user-attachments/assets/2d4305cb-d323-48b7-b0a3-ddff473fbc6d

### Steps to reproduce the issue

1. Enabled the setting 
2. Close out the app 
3. And open it and it still shows under the video player 

### Crash log (if the app crashes)

```shell
None
```

### Additional context

None

**Comment by bhackel** [comment]
I believe those settings affect the 3-dots menu
![image](https://github.com/user-attachments/assets/4f6afb01-e248-42d5-9b69-903abdcfb47e)

**Comment by Magichouse227** [comment]
Oh 😥 So there isn’t a way to remove them from under the video?  

> I believe those settings affect the 3-dots menu ![image](https://private-user-images.githubusercontent.com/34104885/351972489-4f6afb01-e248-42d5-9b69-903abdcfb47e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzY4MzQsIm5iZiI6MTcyMTkzNjUzNCwicGF0aCI6Ii8zNDEwNDg4NS8zNTE5NzI0ODktNGY2YWZiMDEtZTI0OC00MmQ1LTliNjktOTAzYWJkY2ZiNDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE5NDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MjczN2E0NjFlNmRkYzRkYzQ3YWJkMGY0NDU4Mzc2MmQ1MDVlMWE1M2VkZTA5ODk4OWJkYWM2MDQ1YjQ2NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QpR7hH9SgwDcaU0VAyUkKf5wt8u5tIiBpjlMwv_N7sQ)

**Comment by bhackel** [comment]
I think there used to be, but it was removed from YTLite for being broken.

**Comment by bhackel** [comment]
If you want, you can make a new post requesting the features, and one of the devs may make it eventually.
