### ISSUE TITLE
[Bug] Can not play videos above 1080p

### ISSUE THREAD

**Issue by Mokerjay** [YTLitePlus/YTLitePlus#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.1.1

### Device model

Iphone 15 pro max

### Sideload method

Signulous

### Tweak version

19.28.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

I cant seem to play videos above 1080p!
i hope this can be fixed, thank you in advance!

Here is a image of proof!

![IMG_4432](https://github.com/user-attachments/assets/6254a97c-ada1-49e8-a72c-7daf38b8822e)
![IMG_4431](https://github.com/user-attachments/assets/17c8aa6f-3b2b-4ec3-a34a-0089079b458d)

### Steps to reproduce the issue

1. 
2. 
3. 
![IMG_4432](https://github.com/user-attachments/assets/873630b6-2bfc-482a-9c87-1b515f9b4ffd)
![IMG_4431](https://github.com/user-attachments/assets/9d01bbee-8d2c-438c-89f4-c1dc19880651)

**Comment by bhackel** [comment]
Can you check if you have YouPiP: Legacy Video Player enabled? If you do, turn it off

**Comment by Mokerjay** [comment]
> Can you check if you have YouPiP: Legacy Video Player enabled? If you do, turn it off

Nop still does the same issue

**Comment by bhackel** [comment]
When I had this issue in a previous version, I would try to turn off YouPiP: Legacy Video Player, but it would not stay off. When I restarted app, it would turn on again. Do you have this problem as well?

**Comment by Mokerjay** [comment]
> When I had this issue in a previous version, I would try to turn off YouPiP: Legacy Video Player, but it would not stay off. When I restarted app, it would turn on again. Do you have this problem as well?

Yes i do, it just re-enables it and when i turn on videos in the background it also shows a black screen after reopening it!

**Comment by bhackel** [comment]
Ah a temporary fix would be to disable YouPiP (PiP will no longer work). You can also build a new iPA, which should have the problem fixed
