### ISSUE TITLE
Some recorded livestreams crash

### ISSUE THREAD

**Issue by senorYME** [YTLitePlus/YTLitePlus#274]
https://youtu.be/MNJofMjnE04?si=OMxcXd0WoCJjBPK1 even when paused on latest ytliteplus crashes can you check why it happens to many videos like this

**Comment by KieranBLK** [comment]
> https://youtu.be/MNJofMjnE04?si=OMxcXd0WoCJjBPK1 even when paused on latest ytliteplus crashes can you check why it happens to many videos like this

Seems to only apply to the latest (July 22) update. Happens for streams that are 2 or more days old. The crash occurs when the feed under it loads. 

Here's a crash log to help debug, if I didn't already downgrade I would've captured a screen recording
[YouTube-2024-07-25-214720.log](https://github.com/user-attachments/files/16397427/YouTube-2024-07-25-214720.log)

**Comment by senorYME** [comment]
> > https://youtu.be/MNJofMjnE04?si=OMxcXd0WoCJjBPK1 even when paused on latest ytliteplus crashes can you check why it happens to many videos like this
> 
> 
> 
> Seems to only apply to the latest (July 22) update. Happens for streams that are 2 or more days old. The crash occurs when the feed under it loads. 
> 
> 
> 
> Here's a crash log to help debug, if I didn't already downgrade I would've captured a screen recording
> 
> [YouTube-2024-07-25-214720.log](https://github.com/user-attachments/files/16397427/YouTube-2024-07-25-214720.log)
> 
> 

Yep and thank you for confirming it

**Comment by bhackel** [comment]
Can you test if you get the crash after disabling Return YouTube Dislike?

**Comment by senorYME** [comment]
> Can you test if you get the crash after disabling Return YouTube Dislike?

Confirmed turning it off fixed it

**Comment by bhackel** [comment]
👍 We will wait for a fix from their repo then.
