### ISSUE TITLE
[Bug] Dislike count sometimes doesn’t show

### ISSUE THREAD

**Issue by dora727** [YTLitePlus/YTLitePlus#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

16.4

### Device model

iPhone SE 2022

### Sideload method

TrollStore

### Tweak version

v19.29.1 - 4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

So, sometimes after watching a few videos i realize that dislike count disappeared, even when I checked RYD is enabled.

(i’ll add imgs later cuz somehow my phone bugged so can’t add while jailbroken)

### Steps to reproduce the issue

1. Watching video
2. hmm(?)

**Comment by dora727** [comment]
damn i can’t add image when editing so, here’s imgs 
![IMG_8715](https://github.com/user-attachments/assets/0fa8def5-1459-40f6-ab53-4808edb230cb)
![IMG_8697](https://github.com/user-attachments/assets/38f9eab4-1bde-4745-84a8-73d04867eb29)

**Comment by bhackel** [comment]
Looks like this was fixed in a newer version of RYD. We will wait for the fork that this repo uses to be updated, and then it will work properly.
