### ISSUE TITLE
[Bug] Shorts title and video desync after a few videos

### ISSUE THREAD

**Issue by Milchkarl** [YTLitePlus/YTLitePlus#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

17.3.1

### Device model

iPhone 12 Pro Max

### Sideload method

Altstore

### Tweak version

19.21.1-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

In the shorts section, the shorts itself work fine but everything else is not synchronised. If I watch a short the title, likes and comments don’t match the short I’m watching but the one 4 scrolls further. For example watching a mrbeast short but channel name, title 
, likes and comments are from another short and if zip click the channel the channel of the other short opens instead of the creator of the short you’re currently watching.

### Steps to reproduce the issue

1. Fresh install
2. Open YouTube shorts section
3. Scroll a bit and after a few scrolls you notice that the title doesn’t match the vid you’re watching

### Additional context

The only settings I have changed are Oled dark mode, quality button in video ui, downloader button under video, pip, (all not related to shorts).

I’ve read in one of the changelogs that you’re supposed to be able to export your settings I would’ve done that and added the config in here but I can’t seem to find the setting for export.

**Comment by bhackel** [comment]
Not sure about this idea, but I think there is an older shorts UI that could be having problems. Do you think you can include a screenshot/screen recording of the issue? Also, include a screenshot of opening the comments section, since I think that might show it better.

**Comment by bhackel** [comment]
Ah sorry I haven’t been able to find anything or replicate it, I would suggest doing a fresh install and testing each setting until the issue reappears.

**Comment by bhackel** [comment]
Likely fixed in v5, try it out and see if the problem still exists
