### ISSUE TITLE
[Bug] Autoplay not working after fast forward/backward

### ISSUE THREAD

**Issue by sdugoten** [YTLitePlus/YTLitePlus#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

IOS 17.5.1

### Device model

iPad Pro m4 13inch

### Sideload method

MapleSign

### Tweak version

YTLitePlus 19.28.1-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

When you try to fast forward or backward by dragging the red time bar at the bottom of the video, it will just stop playing.  You will have to manually press the play button again in order to play the video again.

This is not the default behavior with official youtube.   The official youtube will auto play the video right after you fast forward or backward by dragging the red time bar on the bottom of the screen

### Steps to reproduce the issue

1. Play any video on youtube app
2. drag the red time bar on the bottom of the screen to somewhere
3. You will notice the video stop and not auto play

### Additional context

can see the bug here from the video link

https://streamable.com/4bjnd8

---

**Comment by sdugoten** [comment]
Please note that the same version do not have this bug on iphone 15 pro max.  It seems it only hit ipad.

**Comment by bhackel** [comment]
I had this issue with YouPiP enabled in an older version. Can you try disabling YouPiP and see if it fixes the issue
