### ISSUE TITLE
[Request] Add HTTP3 protocol please 

### ISSUE THREAD

**Issue by YanPramuda** [YTLitePlus/YTLitePlus#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

Hello, dear developers! 
Now in Russia they are blocking the speed of YouTube. Videos in 720p 1080p 4K work with brakes, with freezes, including your application. 

I read that HTP3 Quick protocol allows to bypass this story. 

Is there any possibility to add such an option to your app to enable these protocols? 

Sincerely thank you.
U are my most favorite project on the YouTube app. Thank you!

**Comment by bhackel** [comment]
Hi this seems out of the skill level for the devs here, you may have better luck requesting it directly on the YTLite github page.
