### ISSUE TITLE
[Bug] Hide shorts function not working properly

### ISSUE THREAD

**Issue by ThanhPhuoc91** [YTLitePlus/YTLitePlus#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

16.1.2

### Device model

Iphone 12

### Sideload method

Trollstore

### Tweak version

YTLitePlus v19.29.1-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

Sometimes the shorts title appears when the app start up.
![00FECA45-56F6-4DE5-81F6-D4F08F5D33D0](https://github.com/user-attachments/assets/6b890b77-732e-46ed-9d64-1281fdac76b7)

### Steps to reproduce the issue

1. Setting
2. Turn on hide shorts
3. Reboot and open app

**Comment by ThanhPhuoc91** [comment]
(Update) I checked and learned that the above error appears due to the ad blocking function. When you turn off ad blocking, there will be no error but ads will appear.

**Comment by RadCod3** [comment]
Yep having the same issue

**Comment by bhackel** [comment]
Fixed in v5, thank you
