### ISSUE TITLE
[Bug] Videos crash on opening when building using todays 19.30 youtube release

### ISSUE THREAD

**Issue by mohkg1017** [YTLitePlus/YTLitePlus#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

17.6

### Device model

15 pro max

### Sideload method

esign

### Tweak version

19.30-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

[Bug] Videos crash on opening when building using todays 19.30 youtube release, didn't have. this issue on 19.29.

### Steps to reproduce the issue

1. build using latest youtube released today 19.30
2. open videos
3. they crash
4. this didn't happen on 19.29

**Comment by bhackel** [comment]
Hmm can you attach the crash log?

**Comment by miketester10** [comment]
I'm using 19.29.1 and it's working properly. Maybe your problem is related to the latest YouTube update 19.30.2
Go back to a version, you could fix it.

**Comment by mohkg1017** [comment]
fixed with latest commit

**Comment by mohkg1017** [comment]
fixed
