### ISSUE TITLE
[Questions] About injecting YTLite beta

### ISSUE THREAD

**Issue by dora727** [YTLitePlus/YTLitePlus#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

So, dvntm released YTLite v5 beta on his patreon, and i wanted to use it with YTLitePlus.

So, what do I suppose to do (on my fork repo, or with the ipa) if i want to?
Btw I used TrollFools to eject current ytlite and injected the beta one but crashed (without crash logs).
Thanks.

**Comment by Balackburn** [comment]
Maybe there will be a conflict with iSponsorBlock, as I see that it has added sponsorblock to YTLite. 
 
 Don't use 19.30+ versions of Youtube as they aren't compatible with YTLitePlus, fork the repostory and edit the Github action (.github/workflows/buildapp.yml) use your own YTLite .deb for injection instead of the latest from dayanch96 Github. I tested this code and it seem to work fine.
 
 
[buildapp.yml.zip](https://github.com/user-attachments/files/16465862/buildapp.yml.zip)

**Comment by dora727** [comment]
Thanks. I’ll try and let you know.

**Comment by Balackburn** [comment]
@dora727 Thank you

**Comment by dora727** [comment]
@Balackburn so I tried. But it’s weird
(I used b1 cuz i don’t have b2)

The version in release, and YTLP says 5.0b1
But the version injected is 4.0.1 not 5.0b1

**Comment by Balackburn** [comment]
Yes forgot to edit the makefile

**Comment by Balackburn** [comment]
After some testing I can't it to work (crash on launch) removing sponsor block doesn't work either.

**Comment by Balackburn** [comment]
Update your makefile and buildapp.yml files with theses to fix building, maybe with some testing you can get it to work 

[Support for 5.0.zip](https://github.com/user-attachments/files/16475574/Support.for.5.0.zip)

I tested with Youtube 19.29.1 and 19.30.2

I tested changing the extraction method set YTLite version to 5.0 instead of 5.0b1 in case it caused an issue but it change nothing.

I tested without iSponsorBlock too.

**Comment by dora727** [comment]
> Update your makefile and buildapp.yml files with the following to fix building, maybe with a few tests you can get it to work.
> 
> [Support for 5.0.zip](https://github.com/user-attachments/files/16475574/Support.for.5.0.zip)
> 
> I tested with Youtube 19.29.1 and 19.30.2.
> 
> I tried changing the extraction method by setting the YTLite version to 5.0 instead of 5.0b1 in case that caused a problem, but it didn't.
> 
> I also tested without iSponsorBlock.
> 
> There must be a conflict with other tweaks but I don't know which.

so i got error 127 after doing this (at build package)
https://github.com/dora727/YTLitePlus/actions/runs/10224293326/job/28291849509

**Comment by Balackburn** [comment]
Could you try with uploading the deb to litterbox.catbox.moe and use that url instead of discord?

**Comment by Balackburn** [comment]
I created a new branch (YTLite5.0b) sync your fork and build using this branch (remove your commits) I just built it using litterbox url for the deb and it work

**Comment by dora727** [comment]
Just tried both my commits and the new forked one, but all crashed.
Also tried to eject isponsorblock

**Comment by Balackburn** [comment]
> Just tried both my commits and the new forked one, but all crashed. Also tried to eject isponsorblock

Yes, that's what I said, you can try deleting other tweaks and see if you can find the culprits.

**Comment by dora727** [comment]
Okay I got the result
Even after removing every dylib, it still crashes.

So I’m curious what If i use rootless package, so I also uploaded it and try, but failed at build package (failed to extract) with error 2

**Comment by dora727** [comment]
So now I guess is that only for jailbroken? I have no idea but it worked when installing the deb

**Comment by dora727** [comment]
> So now I guess is that only for jailbroken? I have no idea but it worked when installing the deb

regarded to this, i just did an experiment
so, i tried to eject ytlite.dylib -> didn’t crash.

and then i tried to install ytlite deb file, crashed.
so i tried to eject all, still crashes.
-> it crashed due to ipa installing?

**Comment by Tomithan** [comment]
The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0

**Comment by dora727** [comment]
> The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0

i ejected all and didn’t work, did you install yt from appstore or trollstore?

**Comment by dora727** [comment]
kay i tested. i decrypted yt ipa myself then install with trollstore, it worked with ytlite deb install

so ig its sth modified in ytliteplus side that aren’t dylib

**Comment by Tomithan** [comment]
> > The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0
> 
> i ejected all and didn’t work, did you install yt from appstore or trollstore?

I have decrypted ipa, then inject manually YTLiTe deb and all tweaks of YTLitePlus without YT return dislike and Isponsorblock, and it work, installed with Esign, but i can try with trollstore.

**Comment by dora727** [comment]
> > > The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0
> > 
> > 
> > i ejected all and didn’t work, did you install yt from appstore or trollstore?
> 
> I have decrypted ipa, then inject manually YTLiTe deb and all tweaks of YTLitePlus without YT return dislike and Isponsorblock, and it work, installed with Esign, but i can try with trollstore.

yeah so it might be sth modified with ytliteplus

**Comment by Tomithan** [comment]
> > > > The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0
> > > 
> > > 
> > > i ejected all and didn’t work, did you install yt from appstore or trollstore?
> > 
> > 
> > I have decrypted ipa, then inject manually YTLiTe deb and all tweaks of YTLitePlus without YT return dislike and Isponsorblock, and it work, installed with Esign, but i can try with trollstore.
> 
> yeah so it might be sth modified with ytliteplus

Sure

**Comment by Tomithan** [comment]
> > The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0
> 
> i ejected all and didn’t work, did you install yt from appstore or trollstore?

It working with trollstore

**Comment by Balackburn** [comment]
> > > The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0
> 
> > 
> 
> > i ejected all and didn’t work, did you install yt from appstore or trollstore?
> 
> 
> 
> It working with trollstore

Could you try to build YTLitePlus from the YTLite5.0b branch with the deb you have?

**Comment by Tomithan** [comment]
> > > > The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0
> > 
> > 
> > > 
> > 
> > 
> > > i ejected all and didn’t work, did you install yt from appstore or trollstore?
> > 
> > 
> > It working with trollstore
> 
> Could you try to build YTLitePlus from the YTLite5.0b branch with the deb you have?

Where can i access to the YTLite5.0b branch ? Btw i have inject latest yt return dislike and it working, only removed Isponsorblock because it is already added it 5.0b.

**Comment by Tomithan** [comment]
> > > > > The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > i ejected all and didn’t work, did you install yt from appstore or trollstore?
> > > 
> > > 
> > > It working with trollstore
> > 
> > 
> > Could you try to build YTLitePlus from the YTLite5.0b branch with the deb you have?
> 
> Where can i access to the YTLite5.0b branch ? Btw i have inject latest yt return dislike and it working, only removed Isponsorblock because it is already added it 5.0b.

Latest YT return dislike: 
https://repo.chariz.com/debs/bKPpdKCIO1sPAYdQwBwcYyWtAKRFiV1ITzQyUgFeTg5iGm24wGiQvbZZcvIfaX6OOjrnyMRkTzKtVqLgZBEYtw/weeb.lillie.youtubedislikesreturn_1.12.3_iphoneos-arm.deb

**Comment by Tomithan** [comment]
> > > > The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0
> > 
> > 
> > > 
> > 
> > 
> > > i ejected all and didn’t work, did you install yt from appstore or trollstore?
> > 
> > 
> > It working with trollstore
> 
> Could you try to build YTLitePlus from the YTLite5.0b branch with the deb you have?

<img width="1347" alt="image" src="https://github.com/user-attachments/assets/e70a155a-a06d-4844-ab7a-e013e6cd4a78">
 This one ?

**Comment by Tomithan** [comment]
> > > > The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0
> > 
> > 
> > > 
> > 
> > 
> > > i ejected all and didn’t work, did you install yt from appstore or trollstore?
> > 
> > 
> > It working with trollstore
> 
> Could you try to build YTLitePlus from the YTLite5.0b branch with the deb you have?

How to build it ? Manually ? Can you give me instructions, i don't know how to do it. 
<img width="1732" alt="image" src="https://github.com/user-attachments/assets/e204cae7-8f86-4594-b4ef-773b8ca3fc2e">

**Comment by Balackburn** [comment]
https://github.com/YTLitePlus/YTLitePlus/wiki/Building

Instead of using main branch choose YTLite5.0b

**Comment by Balackburn** [comment]
After testing with just YTLite5.0b1 deb injected (no other tweaks) it work

**Comment by Tomithan** [comment]
> https://github.com/YTLitePlus/YTLitePlus/wiki/Building
> 
> Instead of using main branch choose YTLite5.0b

Will try now
<img width="319" alt="image" src="https://github.com/user-attachments/assets/362860ab-152f-4f8a-a07f-af5ea935861b">

**Comment by Tomithan** [comment]
> After testing with only YTLite5.0b1 deb injected (no other tweaks) it works https://github.com/YTLitePlus/YTLitePlus/actions/runs/10230853823

Yes i have tested too with 5.0b2 and it working

**Comment by Tomithan** [comment]
> > > > The tweaks who make crash IPA is YT return dislike and Isponsorblock, without both, the app work great with the latest version of YT and YTLiTe beta 2 5.0
> > 
> > 
> > > 
> > 
> > 
> > > i ejected all and didn’t work, did you install yt from appstore or trollstore?
> > 
> > 
> > It working with trollstore
> 
> Could you try to build YTLitePlus from the YTLite5.0b branch with the deb you have?

Doesn't work

**Comment by Balackburn** [comment]
@Tomithan After some testing, I got it to work by removing the YTLitePlus injection the YTLitePlus.xm and YTLitePlus.bundle injection cause the crash on launch. 

All the other tweaks work as expected, there must be a conflict somewhere @arichornloverALT @bhackel .

**Comment by Balackburn** [comment]
Sync your fork and build it it should work but they will be some features (the YTLitePlus ones) missing

**Comment by Tomithan** [comment]
> Sync your fork and build it it should work but they will be some features (the YTLitePlus ones) missing

Will try now

**Comment by dora727** [comment]
I got it working now!

**Comment by Tomithan** [comment]
> Sync your fork and build it it should work but they will be some features (the YTLitePlus ones) missing



> I got it working now!

How i don't success

**Comment by dora727** [comment]
> > Sync your fork and build it it should work but they will be some features (the YTLitePlus ones) missing
> 
> > I got it working now!
> 
> How i don't success

Did you sync your fork (the YTLite5.0b branch) then build?

**Comment by dora727** [comment]
Also I realized sth funny is this
<img width="375" alt="image" src="https://github.com/user-attachments/assets/0c670fa1-3123-4eb9-8e04-69455457ae35">
also hide the iSponsorBlock button.
might have conflicted with the ytliteplus one, idk

**Comment by Tomithan** [comment]
> > > Sync your fork and build it it should work but they will be some features (the YTLitePlus ones) missing
> > 
> > 
> > > I got it working now!
> > 
> > 
> > How i don't success
> 
> Did you sync your fork (the YTLite5.0b branch) then build?

Like this ?

<img width="1790" alt="image" src="https://github.com/user-attachments/assets/bc9df952-9c35-4b2f-a9bd-29107c587da1">

<img width="1664" alt="image" src="https://github.com/user-attachments/assets/072f4b01-9655-411f-a0da-1c3515c756a0">

**Comment by dora727** [comment]
just checked ur repo, u did it right tho… weird

**Comment by dora727** [comment]
ah wait, can you try building with youtube 19.29.1?

**Comment by Tomithan** [comment]
> ah wait, can you try building with youtube 19.29.1?

I will retry with 19.30.2 then 19.29.1

**Comment by dora727** [comment]
> > ah wait, can you try building with youtube 19.29.1?
> 
> I will retry with 19.30.2 then 19.29.1

i tried the ipa u built, its working fine for me

**Comment by Tomithan** [comment]
> > > ah wait, can you try building with youtube 19.29.1?
> > 
> > 
> > I will retry with 19.30.2 then 19.29.1
> 
> i tried the ipa u built, its working fine for me

You don't have removed anything ? No dylibs ?

**Comment by dora727** [comment]
> > > > ah wait, can you try building with youtube 19.29.1?
> > > 
> > > 
> > > I will retry with 19.30.2 then 19.29.1
> > 
> > 
> > i tried the ipa u built, its working fine for me
> 
> You don't have removed anything ? No dylibs ?

yeah i didn’t have to remove anything, but i suggest removing isponsorblock dylib

**Comment by dora727** [comment]
oh btw, uninstall youtube-related tweaks that you installed (if you have)

**Comment by Tomithan** [comment]
> > > ah wait, can you try building with youtube 19.29.1?
> > 
> > 
> > I will retry with 19.30.2 then 19.29.1
> 
> i tried the ipa u built, its working fine for me

Yes it working now

**Comment by dora727** [comment]
nice

**Comment by Balackburn** [comment]
> Hi 
> 
> Where from can I get the YTLite deb file
> 
> for Direct URL in building 
> 
> 
> 
> @Balackburn 

It's paid as it's a prerelease, you can get it by donating to the dev (@dayanch96) patreon

**Comment by Balackburn** [comment]
> > > Hi
> 
> > > Where from can I get the YTLite deb file
> 
> > > for Direct URL in building
> 
> > > @Balackburn
> 
> > 
> 
> > It's paid as it's a prerelease, you can get it by donating to the dev (@dayanch96) patreon
> 
> 
> 
> I want V 4.0.1 not prerelease (5) old version I mean for building ipa 
> 
> 
> 
> @Balackburn 

You don't need any deb it automtically download it from latest release

**Comment by Balackburn** [comment]
> > > > > Hi
> 
> > > 
> 
> > > 
> 
> > > > > Where from can I get the YTLite deb file
> 
> > > 
> 
> > > 
> 
> > > > > for Direct URL in building
> 
> > > 
> 
> > > 
> 
> > > > > @Balackburn
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > It's paid as it's a prerelease, you can get it by donating to the dev (@dayanch96) patreon
> 
> > > 
> 
> > > 
> 
> > > I want V 4.0.1 not prerelease (5) old version I mean for building ipa
> 
> > > @Balackburn
> 
> > 
> 
> > You don't need any deb it automatically download it from latest release
> 
> 
> 
> I can't do that When I run workflow there is a field
> 
> (Direct URL of the YTLite deb file) I can't continue building without it.
> 
> 
> 
> 
> 
> @Balackburn 
> 
> 

Your on branch YTLite5.0b switch to main

**Comment by Balackburn** [comment]
> > > > > > > Hi
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > Where from can I get the YTLite deb file
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > for Direct URL in building
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > @Balackburn
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > It's paid as it's a prerelease, you can get it by donating to the dev (@dayanch96) patreon
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > I want V 4.0.1 not prerelease (5) old version I mean for building ipa
> 
> > > 
> 
> > > 
> 
> > > > > @Balackburn
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > You don't need any deb it automatically download it from latest release
> 
> > > 
> 
> > > 
> 
> > > I can't do that When I run workflow there is a field
> 
> > > (Direct URL of the YTLite deb file) I can't continue building without it.
> 
> > > @Balackburn
> 
> > 
> 
> > Your on branch YTLite5.0b switch to main
> 
> 
> 
> ![IMG_1695](https://github.com/user-attachments/assets/845b5c9b-8a31-431e-ab9c-f0ec783a2899)
> 
> 

Reload the page, the main workflow doesn't have this box.

**Comment by bhackel** [comment]
@Stephan-87 When you are updating the repo, click on Discard Commits instead of Update Branch

**Comment by bhackel** [comment]
The easiest way to reset the commits is probably to delete your fork, and then re-fork the repo

**Comment by Balackburn** [comment]
I am closing the issue as injection of 5.0b works (without YTLitePlus features), discussion will move to this issue #300
