### ISSUE TITLE
[Bug] App crash

### ISSUE THREAD

**Issue by miketester10** [YTLitePlus/YTLitePlus#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6

### Device model

iPhone 15

### Sideload method

Sideloadly 

### Tweak version

YTLitePlus - v19.30.2-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

The application crashes all the time I open a video. This does not happen with version 19.29.1.

### Steps to reproduce the issue

1. Open YTLitePlus app
2. Open a video

**Comment by Balackburn** [comment]
This was fixed yesterday sync your fork.
