### ISSUE TITLE
[Bug] Open In Youtube extension missing in 19.29.1-4.0.1

### ISSUE THREAD

**Issue by mynametoad** [YTLitePlus/YTLitePlus#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18.1 beta 1

### Device model

iPhone 15 Pro Max

### Sideload method

Signulous

### Tweak version

YTLItePlus v19.29.1-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

Extension to open in sideloaded ytliteplus is missing from safari after installing latest build

### Steps to reproduce the issue

1. sideload 19.28.1-4.0.1
2. open safari and go to extensions
3. note extension to open in youtube is missing and links in safari will not open in ytliteplus due to this

### Additional context

not sure if this is an 18.1 beta issue or extension issue. dont have another device to confirm.

**Comment by mynametoad** [comment]
Maybe I brain farted and this was something never handled by YTLitePlus... I am not sure, but i set back up an userscript to handle this as a workaround.

Sidenote: Guess this could be a feature request to include open in side loaded youtube safari extension if its not a bug that its missing currently.0

**Comment by bhackel** [comment]
It was there in a previous version I remember. I am also on 18b1 but I can test on an older phone too. The extension is old, so it may be outdated

**Comment by mynametoad** [comment]
This is the userscript I am using that works just fine. Not sure if its any help!

// ==UserScript==
// @name         Open YouTube App
// @version      1.0.2
// @author       asportnoy
// @match        *://*.youtube.com/*
// @downloadURL  https://gist.github.com/asportnoy/628b820184297f5fe296c1a5b79c8000/raw/open-youtube-app.user.js
// @updateURL    https://gist.github.com/asportnoy/628b820184297f5fe296c1a5b79c8000/raw/open-youtube-app.user.js
// @homepage     https://gist.github.com/asportnoy/628b820184297f5fe296c1a5b79c8000/
// ==/UserScript==
if (window.location.pathname === '/redirect') return;
window.location.href = `youtube://${window.location.pathname.slice(1)}${
	window.location.search
}${window.location.hash}`;

**Comment by spry-equity-gory** [comment]
I think it's because of this change in Makefile:
https://github.com/YTLitePlus/YTLitePlus/commit/8a1fa0cac4ba3be2e916f573caddfc383757db02?diff=split&w=0#diff-1da50d4a4dff993b1b2c97677ae52522c0d59b2f7ae618f9ae995812cd249034L129

It seems that the current version of Makefile doesn't include the extension in the build now.

**Comment by bhackel** [comment]
Oh yeah that was my mistake, should be a very easy fix then

**Comment by bhackel** [comment]
Fixed in latest

**Comment by mynametoad** [comment]
Will this be pushed to altsource?

**Comment by Balackburn** [comment]
> Will this be pushed to altsource?

Should be good

**Comment by mynametoad** [comment]
Still only seeing the build from 7/30 on altsource. Not seeing one from today/yesterday with this fix. Not a big deal though.
