### ISSUE TITLE
[Questions] should i be compiling the ipa every time a new commit comes out? or just wait for the releases to come out and do it then?

### ISSUE THREAD

**Issue by ComfortableMilk4454** [YTLitePlus/YTLitePlus#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

title. tysm!

**Comment by Balackburn** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### Do you think this is a bug?
> 
> ❌ No, I don't think this is a bug. I will explain below
> 
> ### My question
> 
> title. tysm!
> 
> ### Additional context
> 
> _No response_

Do what you like, it's best to wait between releases as there are commits every day and building for each one is almost pointless.

**Comment by ComfortableMilk4454** [comment]
@Balackburn thanks for the response! aren't there important fixes inbetween releases tho?

**Comment by Balackburn** [comment]
> @Balackburn thanks for the response! aren't there important fixes inbetween releases tho?

Not necessarily, if you don't have any problems with your current version no need to update.

The big updates fix bugs and add features but some are just updates for the latest version of Youtube.

If you want changes, wait between YTLite updates (currently 4.0.1) and wait for 5.0

**Comment by ComfortableMilk4454** [comment]
i c, tysm!
