### ISSUE TITLE
[Bug] Conflict between YTLitePlus and YTLite 5.0b

### ISSUE THREAD

**Issue by Balackburn** [YTLitePlus/YTLitePlus#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18.0b

### Device model

iPhone 14 Pro

### Sideload method

Sideloadly

### Tweak version

YTLitePlus_19.30.2_5.0b2 

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

Using the latest pre-release of YTLite (5.0b1 or 5.0b2) causes a crash at launch if YTLitePlus.xm and the YTLitePlus bundle are injected, but all the other injected tweaks work correctly with it. The temporary fix was  to not inject it.

### Steps to reproduce the issue

1. Build YTLitePlus with latest YTLite beta
2. Open app
3. Crash

**Comment by bhackel** [comment]
Hey any crash logs?

**Comment by Balackburn** [comment]
Doesn't seem to generate one, if you want to try yourself

Catbox y7q0s3.ipa

**Comment by dora727** [comment]
Wanna tell u guys this, I tried to use YTL v5.0b3

Actually I build using the main branch (cuz it has updates lmao) then use trollfools to inject 5.0b3, and without removing ytliteplus.dylib it s doesnt crash anymore!

however the popup “incompatible tweaks detected” shows (ig even when there’s no ytliteplus.dylib)

**Comment by dora727** [comment]
also i found ytlite v5.0b3 added an option to change mini-player style (ipad, iphone and floating)

i found a conflict with ytlp in this
ipad and iphone options work normally
but floating wont when ytliteplus.dylib is injected

**Comment by Balackburn** [comment]
> Wanna tell u guys this, I tried to use YTL v5.0b3
> 
> Actually I build using the main branch (cuz it has updates lmao) then use trollfools to inject 5.0b3, and without removing ytliteplus.dylib (and ytliteplus.xm) it doesnt crash anymore!
> 
> however the popup “incompatible tweaks detected” shows (ig even when there’s no ytliteplus.dylib)

can you share a catbox of it thx

**Comment by dora727** [comment]
> > Wanna tell u guys this, I tried to use YTL v5.0b3
> > Actually I build using the main branch (cuz it has updates lmao) then use trollfools to inject 5.0b3, and without removing ytliteplus.dylib (and ytliteplus.xm) it doesnt crash anymore!
> > however the popup “incompatible tweaks detected” shows (ig even when there’s no ytliteplus.dylib)
> 
> can you share a catbox of it thx

hmm idk what will dan think but lemme upload

**Comment by dora727** [comment]
@Balackburn https://litter.catbox.moe/qiz5ur.deb
if you downloaded tell me

**Comment by Balackburn** [comment]
> also i found ytlite v5.0b3 added an option to change mini-player style (ipad, iphone and floating)
> 
> i found a conflict with ytlp in this ipad and iphone options work normally but floating wont when ytliteplus.dylib is injected

I was talkin about the .ipa

**Comment by dora727** [comment]
> > also i found ytlite v5.0b3 added an option to change mini-player style (ipad, iphone and floating)
> > i found a conflict with ytlp in this ipad and iphone options work normally but floating wont when ytliteplus.dylib is injected
> 
> I was talkin about the .ipa

you mean the one on main branch + ytl 5.0b3, or the one built on ytlite5.0b branch?

**Comment by bhackel** [comment]
We will use #323 for tracking of duplicates, closing this.
