### ISSUE TITLE
[Bug] Mix minimized picture in full screen video player 

### ISSUE THREAD

**Issue by R-V12** [YTLitePlus/YTLitePlus#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.5

### Device model

iPhone 15

### Sideload method

ESign

### Tweak version

Ytliteplus-19.29.1-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

![IMG_2752](https://github.com/user-attachments/assets/a2f33204-44f4-475a-bfb2-575bae30ec24)

Sometimes, when I put my video in full screen and pull from the bottom for  recommended  videos, I get a “mix” (which includes the video I currently play) that has the picture minimized. I can still click the full rectangle(within the limits, but outside the mix picture) and open the mix of videos.

### Steps to reproduce the issue

There are no ways I’ve found of duplicating this. It happens at random.

**Comment by bhackel** [comment]
Closing this as it is a minor issue. We can reopen it in case other people find it annoying. Thank you
