### ISSUE TITLE
Add uyou-style video player for downloaded videos + folder download option for videos

### ISSUE THREAD

**Issue by R-V12** [YTLitePlus/YTLitePlus#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

Uyou has another tab for downloaded videos, where you can sort them by latest added, and a integrated video player where you can play your downloaded videos(unlike ytliteplus). I want a feature where we can have this tab, filter by time added, length of video, favorites, add folders where we can create different mixes of videos(I would use this feature primarily for music videos, but others might use them for example for workouts) and an integrated video player(or idk what to call it- what uyouenhanced has). I hate using the photos app’s video player where you have to drag the video. This tab’s video player could have things like speed controls, seek anywhere, etc.

ytliteplus could just pull the videos I downloaded normally, since it has normal download speeds, unlike Uyou, which also interrupts, and I have to close and reopen uyou, and integrate them in this tab.

**Comment by Balackburn** [comment]
This will not be added sorry

**Comment by Balackburn** [comment]
In YTLite 5.0 (not yet released), you can choose to download videos to files or to any another application, find a video player application in the app store and save them there.

**Comment by R-V12** [comment]
> In YTLite 5.0 (not yet released), you can choose to download videos to files or to any another application, find a video player application in the app store and save them there. 

I understand you don't want to add a video player, but would the download speeds be affected/ be slower, similar to Uyou if we were to download the video to file? I don't want that atrocious download speed ever again.

**Comment by Balackburn** [comment]
> > In YTLite 5.0 (not yet released), you can choose to download videos to files or to any another application, find a video player application in the app store and save them there.
> 
> I understand you don't want to add a video player, but would the download speeds be affected/ be slower, similar to Uyou if we were to download the video to file? I don't want that atrocious download speed ever again.

No this as nothing to do with download speed it download as a .mp4 file and then you can save it where you want
