### ISSUE TITLE
[Bug] Delete old workflow runs doesn't seem to work

### ISSUE THREAD

**Issue by Balackburn** [YTLitePlus/YTLitePlus#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

any

### Device model

any

### Sideload method

any

### Tweak version

any

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

The workflow runs correctly, but old runs are still present. 

### Steps to reproduce the issue

1. Run the "Delete old workflows" workflow.
2. Check if the old "Build and Release" workflows are still there.
3. They did not get deleted.

**Comment by Void-pixe-l** [comment]
That more of a GitHub issue I think.

**Comment by Balackburn** [comment]
> That more of a GitHub issue I think.

This is an issue linked to this repo, like building errors.

**Comment by bhackel** [comment]
Hey sorry about that, I made a change, I have now fixed it
