### ISSUE TITLE
No You/History/account

### ISSUE THREAD

**Issue by Void-pixe-l** [YTLitePlus/YTLitePlus#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iPadOS 17.5.1

### Device model

iPad 7th generation 

### Sideload method

Sidestore

### Tweak version

YTLite Plus 19.26.1-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

*I was using the app when randomly it removed the you section. I refreshed it multiple times*

### Steps to reproduce the issue

There are no ways I’ve found of duplicating this.
![Uploading IMG_0014.png…]()

### Additional context

I used the altstore repo

**Comment by Balackburn** [comment]
Hold the home tab or disable "hide you tab" in settings

**Comment by Void-pixe-l** [comment]
Thanks
