### ISSUE TITLE
[Request] Hide 2x speed UI Pop-up after 1/2 seconds. 

### ISSUE THREAD

**Issue by schweppes-0x** [YTLitePlus/YTLitePlus#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

![IMG_3590](https://github.com/user-attachments/assets/dec19e6d-2c73-410f-b9a7-25dedc72aabb)

When holding the screen and we enter the 2x speed mode, it's really annoying when this ui thingy is kept on the screen. I think it should be hidden or we should have the option to remove it if prefered.

**Comment by bhackel** [comment]
Hey I don’t think we will work on adding this, sorry. You can try request in the YTLite repo, but I am not sure if the developer is interested. Thank you

**Comment by bhackel** [comment]
Hey again, I saw that you are also interested in having a setting to remove it. This would be relatively easy to implement, so I will work on it soon

**Comment by schweppes-0x** [comment]
That would be awesome, thank you!
