### ISSUE TITLE
[Bug] app defaults to english instead of german

### ISSUE THREAD

**Issue by Ditpo** [YTLitePlus/YTLitePlus#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6

### Device model

iPhone 15 Pro Max

### Sideload method

ipasigner.com (probably signolous)

### Tweak version

19.29.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

I updated from 19.22.6 to 19.29.1 and the app defaults to english. 19.22.6 worked fine and was in german.

Not a huge issue of course, but maybe something you want to look into when you have the time :)

### Steps to reproduce the issue

1.  update 19.22.6 to 19.29.1 via ipasigner.com
2.  launch app

**Comment by bhackel** [comment]
Since it's a minor issue, I'm going to close this for now, and if enough people are interested, then we can investigate more. Thank you
