### ISSUE TITLE
[Questions] How do I go back to the original Miniplayer?

### ISSUE THREAD

**Issue by DominikP78** [YTLitePlus/YTLitePlus#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

How do I go back to the original Miniplayer?

**Comment by bhackel** [comment]
You may have accidentally enabled a setting in YTLite (YouTube Plus Settings). I would check there, otherwise you can reinstall to clean everything

**Comment by bhackel** [comment]
Hey are you talking about this miniplayer?
![image](https://github.com/user-attachments/assets/45abdbf4-9800-44a8-8784-e31dd1d1a5ef)
I randomly got it after a reinstall

**Comment by bhackel** [comment]
Hey I found a fix: in A/B Flags, disable enableIosFloatingMiniplayer

**Comment by DominikP78** [comment]
Thank you!
