### ISSUE TITLE
[Request] Remove "Up Next" mini banner at video end

### ISSUE THREAD

**Issue by Hydro1313** [YTLitePlus/YTLitePlus#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iPadOS 17.6

### Device model

iPad 9th Gen. 

### Sideload method

ESign

### Tweak version

YTLite 19.30.2 - 4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

Selected every option to hide banners, up next, overlays, and all that but this up next banner shows up underneath the current video title. 
![IMG_1941](https://github.com/user-attachments/assets/98b5c6a0-f352-405d-96f2-3d6724fc2748)

### Steps to reproduce the issue

1. Fats for video till the end. 
2. 
3.

**Comment by bhackel** [comment]
Yes this is the last suggested video overlay that I have found, I will work on removing it soon
