### ISSUE TITLE
[Bug] Channel watermark reappears when tapping the controls and dismissing them

### ISSUE THREAD

**Issue by reticivis-net** [YTLitePlus/YTLitePlus#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18.1

### Device model

iPad Pro M4

### Sideload method

MapleSigner

### Tweak version

v19.30.2-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

When opening a video the watermark is gone, but if you tap twice it reappears

### Steps to reproduce the issue

- Turn on hide channel watermark
- open a video, don’t show controls
- fullscreen it (watermark won’t be visible)
- tap to show controls
- tap again to hide them (watermark is now visible)

https://github.com/user-attachments/assets/6a025fe3-9070-4eaf-b7a3-b2640dd85baf

### Additional context

It’s NOT a YTLite issue, https://github.com/dayanch96/YTLite/issues/136 it can’t be reproduced in the official YTLite ipa.
This exact bug occurred in uYouPlus ages ago and was fixed https://github.com/qnblackcat/uYouPlus/issues/1292

**Comment by bhackel** [comment]
Based on the answer in uYouPlus, you can disable the AB flag iosEnableFeaturedChannelWatermarkOverlayFix

**Comment by reticivis-net** [comment]
Ah that worked
Maybe configure the tweak to automatically do that when the setting is on?

**Comment by bhackel** [comment]
Sounds possible, will implement soon

**Comment by bhackel** [comment]
Fixed in v5, thank you
