### ISSUE TITLE
[Request] Hide top comment (spoiler block)

### ISSUE THREAD

**Issue by samuelawachie** [YTLitePlus/YTLitePlus#314]
On the old uYouEnhanced, you could set this option to hide the comments but still display the content section (no comment will be there, unless you tap it). It helped to prevent spoilers in the comment section. How do I enable that here? I searched all the options, and couldn't do it so far.

**Comment by bhackel** [comment]
Should be easy to add, I have also been looking to add this, it is good to hear that uYouEnhanced already has it

**Comment by samuelawachie** [comment]
> Should be easy to add, I have also been looking to add this, it is good to hear that uYouEnhanced already has it

>
Waiting... as per usual ;)

**Comment by bhackel** [comment]
Well I always welcome new developers to learn and help

**Comment by samuelawachie** [comment]
Surprisingly, it's hiding the comments now on my first video this morning. I installed YTlite+ over uYouEnhanced, so I expected that setting to carry over like a few others did. 
It didn't appear so yesterday, but this morning seems to even though I changed nothing wrt this. 
I'll keep testing it and report back.

**Comment by bhackel** [comment]
Yes I find that it depends on the video. I looked into a cleaner way to hide the top comment, but the result to include it or not include it is made by YouTube servers, so it is quite hard to remove unfortunately
