### ISSUE TITLE
[Questions] Duplicated Settings

### ISSUE THREAD

**Issue by samuelawachie** [YTLitePlus/YTLitePlus#315]
Just came from uYouEnhanced and I'm setting up this app the way my old one was set up. But I'm finding that a lot of the settings are in 2 different places. Sometimes you'd find the same settings in 3 different places. 
I am then unsure as to which to toggle, and whether they conflict with one another. 
This needs to be simplified.

**Comment by bhackel** [comment]
It is different, what settings exactly are duplicated? There have been quite a few that have been removed already

**Comment by samuelawachie** [comment]
> It is different, what settings exactly are duplicated? There have been quite a few that have been removed already

>
It might be tedious going through each setting to compile the duplicates. This was just my overall feeling as I _felt_ as though I was seeing the same settings while setting stuff up. It's already way past my bedtime. I'll try to see if the feeling was indeed right when I try to make a list of them later, in the morning when I'm up

**Comment by eliliam** [comment]
I definitely have noticed the same thing, most of the duplication is between the "YouTube Plus" tab and the "YTLitePlus" tabs

**Comment by bhackel** [comment]
You may feel like it, but youtube has a lot of features that are very similar. For instance:
Hide videos under the video player
Hide videos in fullscreen engagement view
Disable fullscreen engagement view
Hide suggested video end cards
Hide suggested video end screen
So if you can actually find duplicates, then let me know and I will remove them

**Comment by bhackel** [comment]
Duplicates will be discussed in #323 along with other things, thank you
