### ISSUE TITLE
[Request] Video & Audio player in-app through Files app

### ISSUE THREAD

**Issue by DBeitniz** [YTLitePlus/YTLitePlus#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

Add an audio, and if possible, a video player that works directly in the app, similar to uYou. It’s much more convenient to have everything in one place, without needing to download a questionable audio or video player. I used uYou as an audio player because it’s so much more convenient and has all the music-player features. The video player in the Files or Photos app is terrible. uYou simply used the Apple player, which is far better, it saves the timestamp, makes it easy to skip parts, and prevents accidental exits. As example you could make the app make a folder in the files app where you can import videos and audios downloaded and if anyone wants to use the downloaded files anywhere else it won’t be a hassle for them to find the right file, as it’s already in the files app.

**Comment by eliliam** [comment]
Please edit your title to reflect your issue

**Comment by bhackel** [comment]
Hello, I agree with a good amount of what you have mentioned

- The reason for avoiding an in-app video player is because when you reinstall the app, you lose your downloads. I agree that the photos app and the files app both have bad player experiences. Maybe a compromise would be a menu in the YouTube app that can read videos saved somewhere in the Files app, using the normal Apple player. Not sure how possible this is.
- I have not used the uYou music player. Can you talk about the advantages of using it instead of using YouTube with background playback enabled?
- From what I can see in the uYou player right now, it does not save the timestamp. I do agree that the photos viewer is terrible for YouTube videos, and I think the Files viewer is not much better.

**Comment by DBeitniz** [comment]
> Hello, I agree with a good amount of what you have mentioned
> 
> * The reason for avoiding an in-app video player is because when you reinstall the app, you lose your downloads. I agree that the photos app and the files app both have bad player experiences. Maybe a compromise would be a menu in the YouTube app that can read videos saved somewhere in the Files app, using the normal Apple player. Not sure how possible this is.
> * I have not used the uYou music player. Can you talk about the advantages of using it instead of using YouTube with background playback enabled?
> * From what I can see in the uYou player right now, it does not save the timestamp. I do agree that the photos viewer is terrible for YouTube videos, and I think the Files viewer is not much better.

So the advantages in uYou audio player are that it can be used offline (which is important to me because I have 1GB of mobile internet), has a shuffle and repeat function and works like just any music app but better, because YouTube has more songs than any music platform does. I use it always in the background with my earbuds, it’s also convenient that these earbuds have a function to pause or skip songs by tapping on them and it works with uYou without any issues. What I mean about the video player is that in files/photos app if you leave it for 10 minutes the app content gets refreshed and you lose your video timestamp, with the Apple player you at least have much more time to do something else and go back to it and not have the whole app refreshed, because Apple made their player use RAM for longer time also you can easily go in PiP.

**Comment by MisShenanigans** [comment]
You could just download VLC and save all your downloaded stuff there, it's better than most video and audio players ever developed

**Comment by mmupmip** [comment]
Another option I recently started using is "Documents" by Readdle. It has a pretty nice media player with everything you mentioned even with the free version. The best thing about it is the "Save in Documents" shortcut that appears every time you share a file (along with "Save to Files" and others). I find this extremely convenient to move stuff around, previously with uYou I could download a video/audio then share it directly to Documents in 1 tap. It also has a bunch of other office functions too (though many of them require pro ver., like trimming audio, editting PDFs directly in the app, etc. You can sideload this but I already tried and the "Save in Documents" shortcut breaks which is not worth it for me.

**Comment by mmupmip** [comment]
Hmm, so a video & audio player in a video hosting app? Would be kinda neat actually. Also, I agree on the aesthetic aspect you mentioned, when I first saw the uYou download manager, I was hooked immediately. 
Another note on the Documents app I mentioned, for some music videos on youtube, they have the end screen that replays part of the song which I find really annoying. I can just trim that in the app without needing to move the files around.

**Comment by bhackel** [comment]
Basic idea could be something like this

https://github.com/user-attachments/assets/53f1fd8d-1f2c-4e4c-8d73-d34fa44b1af3

**Comment by DBeitniz** [comment]
> Basic idea could be something like this
> 
>  ScreenRecording_08-14-2024.11-06-55_1-compressed.mov

This is actually AWESOME! Now, the only thing left is to add an audio player. Maybe allow users to select a folder with audio files, and from there, show a UI with controls for shuffle, repeat, etc.

**Comment by bhackel** [comment]
Hey so I'm not going to be working on the audio player just yet - it's a bit more tricky and I think that the YTLite dev might be working on something related to it. However, in the future, I may develop it further. Also, the video player is a very basic one buried in the settings that I might move later on - looking for feedback right now

**Comment by samuelawachie** [comment]
Do you guys know that if you install YTLitePlus over uYouEnhanced, the video rendering is by the YouTube app and no need to use VLC or whatever? The only time you need to use an external app like VLC is if you download the video to folder, or specifically tell it to play by that application from the "Download" page in YTL+ settings.
Or maybe I'm missing the point..

**Comment by bhackel** [comment]
I am not sure what you mean - does YTLite have the ability to play videos in the app? Mine are always saved to photos or the files app.

**Comment by samuelawachie** [comment]
> I am not sure what you mean - does YTLite have the ability to play videos in the app? Mine are always saved to photos or the files app.

>
Yes. Mine has always played inside the app. I just installed it over uYouEnhanced.

**Comment by bhackel** [comment]
Maybe it’s because of my sideload method - can you link a screenshot or screen recording?

**Comment by samuelawachie** [comment]
> Maybe it’s because of my sideload method - can you link a screenshot or screen recording?

>
![image](https://github.com/user-attachments/assets/41786dc7-1c20-4c45-b279-4bf4b08f918c)

**Comment by samuelawachie** [comment]
It's always been just like uYouEnhanced for me. There's no way I could've stood playing videos outside the app with another app. 
If that were the case, I'll just stick to my Enhanced. 
I still have the two and I'm still undecided which one is better lol. 
I've been trying to understand what all the uproar has been about playing videos with VLC

**Comment by samuelawachie** [comment]
![image](https://github.com/user-attachments/assets/c1974684-a423-4b67-abf7-e66ab3a41710)

**Comment by samuelawachie** [comment]
![image](https://github.com/user-attachments/assets/b8d36a8e-745b-4899-9db1-6dacb0b10b2e)

**Comment by bhackel** [comment]
I’m looking for a place to move the player button to. Any suggestions? So far I have thought about the You tab, next to the Downloads section that already exists, or on the top navigation bar here:

![image](https://github.com/user-attachments/assets/f78f23cc-db19-4e2e-9b86-13ca211b06b0)

Let me know what people think is better. Also open to other ideas

**Comment by Balackburn** [comment]
> I’m looking for a place to move the player button to. Any suggestions? So far I have thought about the You tab, next to the Downloads section that already exists, or on the top navigation bar here:
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/d708d535-b655-4244-a146-37e0b0132de9)
> 
> 
> 
> 
> 
> Let me know what people think is better. Also open to other ideas

Top navigation bar with a option to hide it

**Comment by bhackel** [comment]
![IMG_1606](https://github.com/user-attachments/assets/7a5edb19-edd9-4239-b7b4-664ad3e139c2)

Worked better than I expected for a first try. Any opinions on having it colored/gray? I think the color makes it stand out more, which is good for making people interested in the button, but also it does not look like it belongs. Or other logo ideas? I know the image has some issues on the edges. @Balackburn do you have the logo with a transparent background? If not then that is fine, I can improve the quality still.

**Comment by Balackburn** [comment]
> ![IMG_1606](https://private-user-images.githubusercontent.com/34104885/361264070-7a5edb19-edd9-4239-b7b4-664ad3e139c2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MzA0MzgsIm5iZiI6MTcyNDYzMDEzOCwicGF0aCI6Ii8zNDEwNDg4NS8zNjEyNjQwNzAtN2E1ZWRiMTktZWRkOS00MjM5LWI3YjQtNjY0YWQzZTEzOWMyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQyMzU1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGY1OWI4OWNlMzhkZmExZTEzNDVhNzBjNzE2MjJlMjE1ZTI3MTJjMzg4NmNiN2MzMjZjMDBhYmVjNTY4Y2JjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0WTOpVEMeUIqw8TgWnzoA_a41_u5OMwU-Lu0dbJ6n0w)
> 
> Worked better than I expected for a first try. Any opinions on having it colored/gray? I think the color makes it stand out more, which is good for making people interested in the button, but also it does not look like it belongs. Or other logo ideas? I know the image has some issues on the edges. @Balackburn do you have the logo with a transparent background? If not then that is fine, I can improve the quality still.

![D](https://github.com/user-attachments/assets/8bb62e9f-c726-41f3-a435-ed6dc8c295cb)
![S](https://github.com/user-attachments/assets/8dec3341-7a7c-49dc-9aa3-51f64ab90a77)
![YTLitePlus (Flat)](https://github.com/user-attachments/assets/e4b8493d-fc3d-45f8-a5a4-8aa7ae2b823c)

**Comment by bhackel** [comment]
![IMG_1608](https://github.com/user-attachments/assets/f1d98131-37c1-44b4-8b1b-9a3f20215061)
![IMG_1609](https://github.com/user-attachments/assets/dc7b7baa-7207-4408-aa83-773371529e75)
![IMG_1610](https://github.com/user-attachments/assets/82ea1715-95e7-492b-bd93-12400feaa4f0)

I think I like the colored one more than the black/white one. What do other people think?

**Comment by bhackel** [comment]
Going to push this with the colored one, can be easily changed in the future - Maybe even a setting

**Comment by Balackburn** [comment]
> Going to push this with the colored one, can be easily changed in the future - Maybe even a setting

I don't like it that much, maybe just a + icon or download icon or a play triangle would be better.

**Comment by mmupmip** [comment]
> I think I like the colored one more than the black/white one. What do other people think? Yes the gray ones need some fixing

I agree, though I still really like the uYou icon. Would it be possible to have an option to add your own icons in the future? Because I'm assuming you can't use uYou's icon for this app?

**Comment by bhackel** [comment]
Possible yes, but I am not sure about the usefulness of the ability to change the icon. Also, not able to use uYou icon unfortunately

**Comment by mmupmip** [comment]
Yeah true, it's more of a cosmetic thing, the coloured one looks good for now 👍

**Comment by Balackburn** [comment]
> Possible yes, but I am not sure about the usefulness of the ability to change the icon. Also, not able to use uYou icon unfortunately

Honestly it should be disabled by default this look quite bad and bloat the UI, I think the resolution is way too high and too, also not that much a feature that most people will use. After building with last commit you pushed the black bugged icon

**Comment by Balackburn** [comment]
> Oh whoops I will definitely revert that. I do get the UI bloat, especially on smaller devices. Disabled by default seems fine then.

Also the resolution is way too high and it look bad

**Comment by bhackel** [comment]
Ok I do also want to make a low-res version of the logo, without any weird resizing artifacts

**Comment by Balackburn** [comment]
![43](https://github.com/user-attachments/assets/db8048e6-ad66-48af-9bb7-67d759384c0a) I don't think it look good as a 40x40 png

**Comment by Balackburn** [comment]
![34](https://github.com/user-attachments/assets/726be376-d694-49f6-8e4e-32856f290a04) 256x256
![DS](https://github.com/user-attachments/assets/83157dfd-47a7-4546-802e-730831731c5c) 128x128

**Comment by bhackel** [comment]
Hey thanks for the feedback, I’ve implemented the changes. Turns out the color issue was a light mode only thing, which is now fixed. There’s a color bug when changing light/dark mode, but I don’t think it’s big enough to worry about. Also added the 128px image. Feel free to try it out, I was not exactly sure about the image quality issue.

Also if you are planning on releasing soon, I have a settings export update that is almost ready, so wait for that

**Comment by Balackburn** [comment]
> Hey thanks for the feedback, I’ve implemented the changes. Turns out the color issue was a light mode only thing, which is now fixed. There’s a color bug when changing light/dark mode, but I don’t think it’s big enough to worry about. Also added the 128px image. Feel free to try it out, I was not exactly sure about the image quality issue.
> 
> 
> 
> Also if you are planning on releasing soon, I have a settings export update that is almost ready, so wait for that

The video player doesn't work for me 
![image](https://github.com/user-attachments/assets/2108d32b-afcd-441c-a0ac-cab0987e1257)

**Comment by Balackburn** [comment]
> > Hey thanks for the feedback, I’ve implemented the changes. Turns out the color issue was a light mode only thing, which is now fixed. There’s a color bug when changing light/dark mode, but I don’t think it’s big enough to worry about. Also added the 128px image. Feel free to try it out, I was not exactly sure about the image quality issue.
> > 
> > 
> > 
> > Also if you are planning on releasing soon, I have a settings export update that is almost ready, so wait for that
> 
> The video player doesn't work for me 
> ![image](https://github.com/user-attachments/assets/2108d32b-afcd-441c-a0ac-cab0987e1257)

Edit : it can't read webm

**Comment by bhackel** [comment]
Oh alright will take a look
