### ISSUE TITLE
[Request] Add “clear cache” button 

### ISSUE THREAD

**Issue by Kenry021** [YTLitePlus/YTLitePlus#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

Would it be possible to add a “clear cache” button just like on uYouEnhanced? Because usually the YouTube apps “documents & data” balloons up to at least a gigabyte or more after using it for a while after setup.

### Additional context

![IMG_2254](https://github.com/user-attachments/assets/8df06155-5982-4301-85f5-80404d69b339)
![IMG_2255](https://github.com/user-attachments/assets/72bd443b-6d81-47be-8e23-913abfae5b0b)
![IMG_0018](https://github.com/user-attachments/assets/68166a43-6456-49a1-8c58-8896b6f8ea46)

**Comment by KieranBLK** [comment]
Already exists. 
https://github.com/user-attachments/assets/266d9ff3-0333-47c8-b163-e874b70b9141
