### ISSUE TITLE
[Request] Hide playlist/live chat/etc. side panel in full screen

### ISSUE THREAD

**Issue by casualsailo** [YTLitePlus/YTLitePlus#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

When playing a video inside a playlist and I switch to full screen mode, the playlist side panel pops open on the right half of the video. When opening a live stream and switching to full screen mode, the live chat pops open in full screen mode

I've searched through the **Settings -> YouTube Plus -> Player** settings, but could not find one to hide/disable the side panel

![IMG_1213](https://github.com/user-attachments/assets/40266ee6-0b62-4ffb-ab8f-a4d87d0ff80d)
![IMG_1216](https://github.com/user-attachments/assets/699c8b8c-4a2d-4218-bd5b-6f07efe91802)

**Comment by bhackel** [comment]
Can you try YTLitePlus - Video controls overlay options - hide right panel in fullscreen mode?

**Comment by casualsailo** [comment]
Thank you for letting me know where to find the setting!
