### ISSUE TITLE
[Bug] Notification Area Not Showing Newest Notifications 

### ISSUE THREAD

**Issue by iAmANoobProgrammer** [YTLitePlus/YTLitePlus#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6.1

### Device model

iPhone 12

### Sideload method

Sideloadly

### Tweak version

YTLitePlus - v19.30.2-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

When I go to the notification area only old notifications show up. I have to refresh it every time I go there to get the newest ones.

### Steps to reproduce the issue

1. Go to the notification area
2. Refresh
3. Repeat

**Comment by bhackel** [comment]
Do you have any UI settings that might be using an older UI? I am currently unable to replicate

**Comment by iAmANoobProgrammer** [comment]
> Do you have any UI settings that might be using an older UI? I am currently unable to replicate

No it’s like this even when you fresh install. I’ll try to be more specific about what the bug is: at first when you go to notifications it shows old notifications. To view the new notifications you need to refresh it by swiping down. It happens every time you go to the notification menu.

Maybe it didn’t occur to you because you didn’t get any new notifications.

This is a small bug, but still I just wanted to share it.

**Comment by TheKivster** [comment]
Seems to be fixed with the most recent release

**Comment by bhackel** [comment]
Hey that’s great to hear, thanks for the report
