### ISSUE TITLE
[Bug] Live Shorts Comments Background is Black When OLED Theme is on

### ISSUE THREAD

**Issue by iAmANoobProgrammer** [YTLitePlus/YTLitePlus#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6.1

### Device model

iPhone 12

### Sideload method

Sideloadly

### Tweak version

YTLitePlus - v19.30.2-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

When OLED theme is turned on the background color of the comments in live shorts is black instead of transparent as it should be. This hides content of the stream.
![IMG_2941](https://github.com/user-attachments/assets/704dd4b9-0361-4c95-b7e9-de2613ec39a2)

### Steps to reproduce the issue

1. Turn on OLED theme
2. Go to a live short with comments
3.

**Comment by bhackel** [comment]
Oh, this is a result of the OLED Live Chat feature that I wrote for normal livestreams - will add a check for Shorts live streams
