### ISSUE TITLE
[Questions] best place to find vanilla yt ipa to inject YtLiteplus into?

### ISSUE THREAD

**Issue by ComfortableMilk4454** [YTLitePlus/YTLitePlus#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

ive always been using https://armconverter.com/decryptedappstore/us to get the ipa but they havent updated it to the latest yt v19.32.6 or the prior recent versions yet so im wondering if there is a more up to date site for getting the ipas. thanks so much!

**Comment by bhackel** [comment]
Not likely, any site hosting a lot of YouTube iPAs will likely be taken down with DMCA on Google

**Comment by ComfortableMilk4454** [comment]
@bhackel rip so the only way to really get the latest is with that program that u can only get when ur jailbreaked?

**Comment by bhackel** [comment]
If you have an older device that can install Trollstore (iOS 14.0 - 17.0, see compatibility here https://ios.cfw.guide/installing-trollstore/), then you can use an app called TrollDecrypt to generate the latest iPA: https://github.com/donato-fiore/TrollDecrypt. Note that you can only install this app with Trollstore. 

Also, if you want to downgrade YouTube to get an older iPA, then you can use an app called AppStore++ https://github.com/CokePokes/AppStorePlus-TrollStore.

This is the method that I use to generate my own iPAs. The decryption app stores use something similar that is automated.

**Comment by ComfortableMilk4454** [comment]
why would you want to downgrade yt tho?

**Comment by bhackel** [comment]
For users on iOS 14, the last compatible version released is 19.20.2, so in order to make builds for that version, then you need to downgrade to 19.20.2 and decrypt that iPA. Otherwise not really necessary.

**Comment by ComfortableMilk4454** [comment]
i see. thanks for this info!
