### ISSUE TITLE
[Questions] System level notification is working?

### ISSUE THREAD

**Issue by MisShenanigans** [YTLitePlus/YTLitePlus#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I installed this app from the latest githubusercontent repo and installed it using E-sign with a revoked enterprise certificate and anti revoke measures set up, somehow I am able to get Apple push notifications from the app even with background process turned off. I wonder if this is intentional and if it is, is there some way to make it work for other sideloaded apps?

**Comment by bhackel** [comment]
As far as I understand, it depends on your sideload method having the same bundle id as the original app, so com.google.ios.youtube. Altstore/sidestore do not have the ability to do this. I'm not super familiar with app entitlements, which is what this is all about.

**Comment by ghost** [comment]
> As far as I understand, it depends on your sideload method having the same bundle id as the original app, so com.google.ios.youtube. Altstore/sidestore do not have the ability to do this. I'm not super familiar with app entitlements, which is what this is all about.

So which method would you suggest? Any documentation or video would be heplful.
