### ISSUE TITLE
Crashing on open

### ISSUE THREAD

**Issue by 0b3l15k** [YTLitePlus/YTLitePlus#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

18 beta 6

### Device model

14 Pro Max

### Sideload method

Altstore

### Tweak version

v19.29.1-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

App crashes and won’t open

### Steps to reproduce the issue

1. Update to iOS 18b6
2.  Open app
3. 

### Crash log (if the app crashes)

```shell
Logs exceed limit
```

### Additional context

![image](https://github.com/user-attachments/assets/31dbac43-0352-4064-8f29-75892c333b60)

**Comment by bhackel** [comment]
Do you see any section in the crash log that says exceptionReason? This is the specific part that would be useful to look at. You can copy just that part, or send a screenshot of it

**Comment by 0b3l15k** [comment]
Here’s a screenshot of what I think you’re looking for I’ve attatched the log itself alsoOn Aug 13, 2024, at 12:18 AM, Bryce Hackel ***@***.***> wrote:﻿
Do you see any section in the crash log that says exceptionReason? This is the specific part that would be useful to look at. You can copy just that part, or send a screenshot of it

**Comment by bhackel** [comment]
Hello I think the images failed to send when you replied over email. Can you attach it using the website instead?

**Comment by bhackel** [comment]
Is this a new thing on 18.0b6?

**Comment by 0b3l15k** [comment]
I'm on 18.0b6 yes, I just updated to the latest and it's working fine now though

**Comment by bhackel** [comment]
Oh weird, that is good to hear though. Hopefully the bug does not return, although I know many people are crashing when viewing shorts in the new versions
