### ISSUE TITLE
[Bug] Copy Settings and Paste settings titles broken

### ISSUE THREAD

**Issue by kixrd** [YTLitePlus/YTLitePlus#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

16.0.2

### Device model

iPhone 13 Pro

### Sideload method

TrollStore

### Tweak version

YouTube - 19.29.1 - 4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

I downloaded the ipa from catbox. My phone language is set to EN_GB. The settings titles are broken for the paste and copy settings.
![A7151459-419D-440E-8954-169B2DD4D5D0](https://github.com/user-attachments/assets/65b6a223-7d0e-442d-910e-3f44f98ea280)

### Steps to reproduce the issue

1. Go to settings
2. Tap YTLitePlus

**Comment by bhackel** [comment]
Hello, this should be fixed in new builds. Once a new release is out, you can download it and it will be fixed. Thank you

**Comment by bhackel** [comment]
If you would rather not wait, you can download a build from me here: https://github.com/bhackel/YTLitePlus/actions/runs/10378934823
