### ISSUE TITLE
[Bug] Workflow getting stuck in "Build Package" on line 533 and 534

### ISSUE THREAD

**Issue by Cappunocci** [YTLitePlus/YTLitePlus#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

Irrelevant.

### Device model

Irrelevant.

### Sideload method

Irrelevant.

### Tweak version

v19.29.1-4.0.1-YTLitePlus

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

Hi!

I'm having a problem with building YTLitePlus.

When running a workflow, using the Catbox you listed, the workflow seems to get stuck in "Build Package" on:
Line 533: ==> Moving tweak's bundle to Resources/...
Line 534: ==> Changing the installation path of dylibs...

I haven't a clue how to solve this myself since I am not a programmer myself; I simply fork as instructed, use your catbox .ipa file (which I assume is the latest YouTube Decrypted one) and run the workflow. I used to get my .IPA's from another user, but their most recent IPA is 19.29.2, not 19.29.1. I've noticed that using newer IPAs does not work, unfortunately.

### Steps to reproduce the issue

1. Fork this repository.
2. Start a workflow.
3. Watch the process. It'll get stuck on lines 533 and 534.

### Crash log (if the app crashes)

```shell
Not Applicable.
```

### Additional context

Not Applicable.

**Comment by bhackel** [comment]
The ones from catbox are pre-built - they already have the tweaks injected. You can install it directly instead of having to rebuild again.

**Comment by Cappunocci** [comment]
> The ones from catbox are pre-built - they already have the tweaks injected. You can install it directly instead of having to rebuild again.

Right, well... I hadn't picked up on that. Thank you for clarifying! Thought I was messing up somewhere.
