### ISSUE TITLE
Does it crashes when playing shorts videos or is it only happens to me ?

### ISSUE THREAD

**Issue by ItzRyan786** [YTLitePlus/YTLitePlus#342]
Does it crashes when playing shorts videos or is it only happens to me ?

_Originally posted by @sujithsugadathan in https://github.com/YTLitePlus/YTLitePlus/discussions/338#discussioncomment-10336822_

**Comment by ItzRyan786** [comment]
> Does it crashes when playing shorts videos or is it only happens to me ?
> 
> _Originally posted by @sujithsugadathan in [#338 (comment)](https://github.com/orgs/YTLitePlus/discussions/338#discussioncomment-10336822)_

yep happens to me too

**Comment by Balackburn** [comment]
Duplicate with #337
