### ISSUE TITLE
[Request] Auto-enable captions & preferential captions

### ISSUE THREAD

**Issue by Infinitay** [YTLitePlus/YTLitePlus#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

Could you add a feature for captions that is similar to the quality preferences? What I mean is that people can set in their preferences what captions they prefer (see example below). Additionally, could you please add the auto-translated captions as an option too?

Example preferences:

1. English
2. Auto-Translate (English)
3. None

**Comment by bhackel** [comment]
I believe this feature is coming in YTLite version 5. Once that is out of beta, then it will be available for everyone to use.
