### ISSUE TITLE
Could you add the extension dearrow as a setting?

### ISSUE THREAD

**Issue by Hoe2020** [YTLitePlus/YTLitePlus#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

Dearrow automatically removes clickbait thumbnails and replaces them with other frames from the video.

I think it would work wonderful as an extension in YTlite.

https://dearrow.ajay.app/

**Comment by bhackel** [comment]
Hey I think you should request this in the YTLite repo since that dev may be able to do it. This is a little out of my ability and would be difficult to implement
