### ISSUE TITLE
[Bug] crash when clicking on new video (short in this case, not sure if it also happens with normal videos) noti in notis section of app

### ISSUE THREAD

**Issue by ComfortableMilk4454** [YTLitePlus/YTLitePlus#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6.1 (21G93)

### Device model

iPhone 13 mini

### Sideload method

MapleSign

### Tweak version

19.32.8-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

https://github.com/user-attachments/assets/4787f6e1-95c9-4e99-b43b-b57c478838b8

built with commit [de89f7a](https://github.com/ComfortableMilk4454/YTLitePlus/commit/de89f7aca8ee5fbb9fae857b61418c4c0c8c4021)

### Steps to reproduce the issue

see screen recording

### Crash log (if the app crashes)

```shell
https://mega.nz/file/1dshVD5D#e61MJDDNmfDQHAXL0MbDz9eVj22r1R7bguUUPm-0gNI (mega link to the .ips)
```

**Comment by bhackel** [comment]
Yes so this is a YTLite issue that is fixed in version 5, which is if paid beta. For now, you can use an older YouTube base version, like 19.29, to avoid the crashing when opening a short

**Comment by bhackel** [comment]
Refer to #337 for future updates

**Comment by ComfortableMilk4454** [comment]
ty @bhackel. im assuming a dev will post a comment in #337 when its fixed?

**Comment by ComfortableMilk4454** [comment]
resolved itself, thanks

**Comment by bhackel** [comment]
Strange but sounds good
