### ISSUE TITLE
[Questions] how do i buy the beta?

### ISSUE THREAD

**Issue by mohkg1017** [YTLitePlus/YTLitePlus#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

how do i buy the beta? thanks

**Comment by bhackel** [comment]
Here: https://www.patreon.com/dayanch96 Then refer to #300 for info on how to build using the beta
