### ISSUE TITLE
[Bug] Searching watch history doesn’t work

### ISSUE THREAD

**Issue by XynoCrest** [YTLitePlus/YTLitePlus#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iPadOS 17.1.2

### Device model

iPad Pro 12.9 (5th Gen)

### Sideload method

ESign

### Tweak version

YTLitePlus - 19.30.2-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

When you go to the You Tab (the tab with your profile picture), click history and try to search for anything, it will just show you results of the most recent videos watched, not the ones with the search keyword. 

You can fix this by spoofing to an older app version (possibly the ones that has the library tab instead of the You tab)

### Steps to reproduce the issue

1. Go to the You Tab
2. Click History
3. Search for a keyword of videos you may have watched at an older date
4. Search results will always be the list of videos watched today

**Comment by mmupmip** [comment]
I just encountered this bug today. For me, when I search for anything, it loads for a bit then returns to the default history tab. Sometimes though, it just says "Something went wrong" like when there's no internet.

**Comment by bhackel** [comment]
Seems to be fixed in 19.34, let me know if people are still having issues

**Comment by mmupmip** [comment]
It works normally in 19.34 now, thank you!

**Comment by mmupmip** [comment]
One small thing I noticed though, not sure if this is YTLite related but there's this 'x' on top of the cancel when searching something in History.


![image](https://github.com/user-attachments/assets/218a547a-3ef9-439b-9f83-e95f1978b21e)
