### ISSUE TITLE
[Bug] Crash after interacting with Playback In Feeds setting

### ISSUE THREAD

**Issue by harrobe123** [YTLitePlus/YTLitePlus#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.5.1

### Device model

iPad air 5

### Sideload method

Sidestore

### Tweak version

YtLiteplus 19.32.6-4.0.1 

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

app crashes when trying to change a setting

### Steps to reproduce the issue

1. go to "you" in the nav bar at the bottom
2. in the top right press on the gear icon
3. go to "YtLiteplus"
4. press "miscellaneous"
5. interact with the top option "playback in feeds"

### Crash log (if the app crashes)

```shell
[YouTube-2024-08-20-105943.ips.txt](https://github.com/user-attachments/files/16673976/YouTube-2024-08-20-105943.ips.txt)
```

**Comment by bhackel** [comment]
Try building before I added gestures at this commit id: 45b7cd948e1c0350090afefc4a4e70b56514fa67

**Comment by harrobe123** [comment]
I don't build I use the altstore repo

**Comment by bhackel** [comment]
Is it just the playback in feeds setting?

**Comment by harrobe123** [comment]
> Is it just the playback in feeds setting?

I don't know. I don't really care about this setting I just thought you should know

**Comment by eliliam** [comment]
I am experiencing this same exact bug on the latest iPad Mini running the latest iPadOS

**Comment by bhackel** [comment]
Both iPad, interesting. Will take a look

**Comment by eliliam** [comment]
Thank you! Let me know if I can provide anything to help with tracking this down

**Comment by bhackel** [comment]
> Thank you! Let me know if I can provide anything to help with tracking this down


When you get a chance, on the device that crashes, can you follow these steps and tell me the value of the inline_muted_playback variable?
https://github.com/user-attachments/assets/ef0845fd-8d28-4f07-8396-8d21607ca73c

**Comment by harrobe123** [comment]
> tell me the value of the inline_muted_playback variable? 

I can't. I went to userdefaults pressed call then searched inline and all that came up was see objects with references to this object

**Comment by bhackel** [comment]
Ok that’s also good to know. I will try to put together a fix soon then

**Comment by bhackel** [comment]
https://github.com/bhackel/YTLitePlus/actions/runs/10482017495

Here is a build with a fix hopefully. Whenever you all have time, feel free to try it out.
