### ISSUE TITLE
[Question] Overlay/player speed controls button position

### ISSUE THREAD

**Issue by NotADinosaur** [YTLitePlus/YTLitePlus#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

They are vertical on the left side, is there a way to make them horizontal below the previous/next (or forward/back) buttons? I’m pretty sure they used to be there and I preferred that.

**Comment by tevyisertyin** [comment]
Seconding this enhancement request for the Play Speed overlay control location to be the same as in uYou (underneath the Play, Previous and Next buttons), or to allow it to be a user-selectable preference.

**Comment by bhackel** [comment]
Unfortunately the dev of YouTube Plus/YTLite is not interested in having movable player speed controls. Since the tweak is closed source, we will likely not have it movable any time soon. Sorry about that
