### ISSUE TITLE
[Bug] Community posts won’t disable properly

### ISSUE THREAD

**Issue by Frostyman758** [YTLitePlus/YTLitePlus#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 16.4

### Device model

iPhone 14

### Sideload method

Trollstore

### Tweak version

19.32.6 - 4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

I enable the option to remove community posts, but it never seems to work for me. Posts are still showing in both subscriptions and below videos. It seems to work for a bit but then break and break video displaying with it.

### Steps to reproduce the issue

1. Launch app & go to settings
2. Enable the remove posts from feed option
3. Posts are in fact, not removed.

**Comment by bhackel** [comment]
Fixed in v5, thank you
