### ISSUE TITLE
[Bug] BigYTMiniplayer makes MiniPlayer Into a very small PiP

### ISSUE THREAD

**Issue by qwertyyuiopas** [YTLitePlus/YTLitePlus#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18.0b

### Device model

iPhone 12

### Sideload method

SideStore

### Tweak version

YTLitePlus - 19.32.8-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

When going into the MiniPlayer it’s just a PiP so it’s not like the one I recognise from uYouEnhanced.
![IMG_1903](https://github.com/user-attachments/assets/f5af469f-da59-4393-89bf-a9270dad539c)

### Steps to reproduce the issue

1. Go into settings and enable BigYTMiniplayer
2. Tap on a video
3. Swipe down to enable MiniPlayer

**Comment by bhackel** [comment]
Is this the style that you are looking for: 

![image](https://github.com/user-attachments/assets/ed0aa3f1-99f1-4002-bbef-0e3aa5e903b1)

**Comment by qwertyyuiopas** [comment]
> Is this the style that you are looking for: 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/ed0aa3f1-99f1-4002-bbef-0e3aa5e903b1)
> 
> 

Yes, like uYouEnhanced

**Comment by bhackel** [comment]
Fixed in latest, thank you
