### ISSUE TITLE
[Bug] Library button disappears

### ISSUE THREAD

**Issue by yairtu** [YTLitePlus/YTLitePlus#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.5.1

### Device model

iPhone 15 Pro

### Sideload method

Sideloadly

### Tweak version

v19.29.1-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

Library button and my google icon randomly disappear, not sure what causes it, and I don’t know how to access the ytlite settings since those buttons are gone. 

The only way I have found to fix it is delete and sideload the app from scratch. 
![IMG_1791](https://github.com/user-attachments/assets/5d48793c-f0e2-4310-a4ae-e6ee4de42e8c)

### Steps to reproduce the issue

Unknown

**Comment by KieranBLK** [comment]
Have to ever held down on the home tab? If you hold it, it hides the library/You tab. It's mentioned in the tab bar settings. 

![image](https://github.com/user-attachments/assets/5110d0ae-1a7e-49c2-94cb-2f7417a7f0d4)

**Comment by xcea** [comment]
What if i dont have the home tab present either?
