### ISSUE TITLE
[Request] Remove tracking parameters from shared links.

### ISSUE THREAD

**Issue by Arturro43** [YTLitePlus/YTLitePlus#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

✅ Yes, I do use YouTube Premium

### My feature request

When user is sharing link to any YT video, Google forces its tracking parameter (?si=) to be included in the copied link.

It looks like this:

https://youtu.be/HUUy3mnAhCE?si=ThEr3is_an_iD_00

I'd love to be able to share video with my friends without being tracked.

Here is regex to remove the ?si= part by [u/Nouche_](https://www.reddit.com/r/webdev/comments/15ukrpi/comment/lgs6po3/)

`(?<=^https://youtu\.be/[a-zA-Z0-9-_]{11})(?=\?.*\bsi=[^&]+)(.*?)(&si=[^&]+|(?<=\?)si=[^&]+&|\?si=[^&]+$)`

**Comment by bhackel** [comment]
Hey, version 5 updated youtube-native-share, which also happens to remove the tracking from shared links. I will close this with that feature as a solution. You can find the setting in YouTube Plus - Interface - Native Share Sheet
