### ISSUE TITLE
[Bug] YTLitePlus crashes when opening any YT short

### ISSUE THREAD

**Issue by AwesomeRedDragon** [YTLitePlus/YTLitePlus#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6.1

### Device model

iPhone 13 Pro

### Sideload method

Sideloadly

### Tweak version

YTLitePlus - v19.32.6-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

Whenever I open a short (from any menu, not specific to the shorts tab), the app crashes.

### Steps to reproduce the issue

1. Open YTLitePlus
2. Tap the shorts icon in the tab bar

### Additional context

Crash Log file (pasting the text in the provided box made the body too long [over 65536 characters] and this box doesn't accept .ips extension - this is the ips file with the extension changed to .txt)
[YouTube-2024-08-26-182236 - txt.txt](https://github.com/user-attachments/files/16755388/YouTube-2024-08-26-182236.-.txt.txt)

**Comment by codeugo** [comment]
Same

**Comment by Balackburn** [comment]
Duplicate with #337

**Comment by Elkas-Hamza** [comment]
Just disable the bring dislikes feature
