### ISSUE TITLE
[Bug] Using Saved Backup doesn’t work

### ISSUE THREAD

**Issue by CiroHoodLove** [YTLitePlus/YTLitePlus#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6.1

### Device model

iPhone 11

### Sideload method

ESign (Revoked Cert Method)

### Tweak version

YTLitePlus v19.30.2

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

when you go to the options where you can export/import current settings you can only export them , when you try to import them an error occures 

### Steps to reproduce the issue

1. Go to Settings
2. Navigate to Where you can find the option to export current settings
3. Click on import

**Comment by bhackel** [comment]
What exactly happens when you try to import the settings?

**Comment by bhackel** [comment]
Actually, what is the last time you updated the app? I fixed this yesterday, so hopefully it is fine now. Build is here: https://github.com/YTLitePlus/YTLitePlus/actions/runs/10572963035

**Comment by CiroHoodLove** [comment]
actually it worked today with an older build , the same build i always use , it didnt work last time , and this time it worked , but still it was the same build like the tweak wasn’t updated on it , it was the same one from 2 weeks ago , but it didn’t change the whole settings , like the one to keep iSponsorBlock button on the front page hidden , that didn’t work , and a couple things also

**Comment by bhackel** [comment]
Yeah there were quite a few keys missing from the export feature - It should be fixed in newer versions.

**Comment by CiroHoodLove** [comment]
i don’t understand how it was fixed for me tho because i’ll put this in a context , i usually use Esign with revoked certs , and it usually stops working in a couple of days so i keep a copy of the iPA file saved on my device , and i just import it to esign and install it each time i repeat the process , one time it didn’t work and next it did , with the same file so that’s pretty odd if you ask me
