### ISSUE TITLE
[Request] Default Shorts quality

### ISSUE THREAD

**Issue by GitUserX21** [YTLitePlus/YTLitePlus#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

This was reported a few times in unrelated topics: YouTube Shorts defaults to 480p and both quality settings (default YouTube & YouTubePlus) don’t change the default YouTube Shorts resolution.

There are apparently a few other issues with shorts and maybe v5 already fixes/implements this - but it would be awesome, if we could change the default Shorts resolution too, as 480p is obviously a bit too low

**Comment by bhackel** [comment]
Likely will be fixed/added in version 5 of YouTube Plus. Will wait for its public release before working on any features.

**Comment by MrAlucardDante** [comment]
Since there doesn't to be an issue for it, I'll mention it here, but the automatic quality switcher doesn't to work too on regular videos. It always defaults to 720p when I set it to 1080p or best

**Comment by Metercedes** [comment]
YT Shorts crashes when I try to open it, I don't understand how it works for you.

**Comment by bhackel** [comment]
Crash is due to #337

**Comment by Metercedes** [comment]
> Crash in shorts is due to #337 

So it only works on older versions?

**Comment by bhackel** [comment]
Yes it’s fixed in v5 of YouTube Plus which should be coming out around early september for free users

**Comment by Metercedes** [comment]
> Yes it’s fixed in v5 of YouTube Plus which should be coming out around early september for free users

Is there also paid ver? What changes?

**Comment by bhackel** [comment]
You can read through here: https://twitter.com/Dayanch96

**Comment by Metercedes** [comment]
> You can read through here: https://twitter.com/Dayanch96

Paid version offers beta/alpha features only. Nothing specified related to Shorts crash on latest release. They just telling us to use downgraded YT iPA.

**Comment by bhackel** [comment]
It’s not hard to find: https://www.patreon.com/dayanch96/shop/youtube-plus-5-0beta4-free-for-309649

- Fixed crash on shorts

**Comment by Metercedes** [comment]
> It’s not hard to find: https://www.patreon.com/dayanch96/shop/youtube-plus-5-0beta4-free-for-309649
> 
> 
> 
> - Fixed crash on shorts

Ah yes my bad sorry. Btw in the settings there is a section for YTLitePlus and YouTubePlus. And only YTLitePlus has import/export settings feature. Does it also affect other tweaks? (Does it also export YouTubePlus, iSponsorBlock etc. settings?)

**Comment by bhackel** [comment]
YouTube Plus section has export as well, it is hard to find though. In YouTube Plus, scroll all the way down to YouTube Plus Preferences, then you can export there. 

Currently YTLitePlus export can do most settings except for any in YouTube Plus and iSponsorBlock. This is only on builds from about 1 week ago though, any builds from before then will not have this ability.

**Comment by MrAlucardDante** [comment]
> YT Shorts crashes when I try to open it, I don't understand how it works for you.

As mentioned in the issue, shorts work on the current version if you disable download manager

**Comment by bhackel** [comment]
Closing thread as this feature is coming in v5
