### ISSUE TITLE
[Bug] Missing You Button in Selection Bar at bottom

### ISSUE THREAD

**Issue by JTG-gaming** [YTLitePlus/YTLitePlus#386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iPadOS 17.5.1

### Device model

iPad Mini 6

### Sideload method

Sideloadly

### Tweak version

YTLitePlus_19.34.2_4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

Missing the You/Library Button in the selection bar at the bottom of the app
Using latest commits up to when post was made [4a92378] and Latest version of YouTube IPA [19.34.2]

### Steps to reproduce the issue

1. Open the Youtube LitePlus App
2. Use your eyes to see it may or may not be there

**Comment by bhackel** [comment]
Long press the Home button to bring it back/make it disappear
