### ISSUE TITLE
[Questions] How to hide these buttons?

### ISSUE THREAD

**Issue by leryeo** [YTLitePlus/YTLitePlus#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

How do I hide these buttons as I only wish to display save and not download, clip, thanks etc?

I looked in the settings but couldn't find anything that would hide these elements.

### Additional context

![IMG_2450](https://github.com/user-attachments/assets/0a7a02ae-4216-4ddd-8d1a-cffd2845bb72)

**Comment by bhackel** [comment]
Not currently possible, I think there is an open request for it as a feature at the moment.

**Comment by systox** [comment]
Yeah, that’d be great
