### ISSUE TITLE
[Bug] Zoom to fill doesn’t work with 9:16 videos

### ISSUE THREAD

**Issue by DBeitniz** [YTLitePlus/YTLitePlus#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

17.5.1

### Device model

iPhone 13

### Sideload method

Sidestore

### Tweak version

19.29.1-4.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

❌ No, I'll explain at the end

### Does the issue happen with the official YouTube from AppStore?

✅ Yes, I can reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

When zooming in on 9:16 (vertical resolution) videos, YouTube shows 'Zoomed to fill,' but nothing actually happens. It seems that YouTube thinks it has zoomed in because if you zoom out, it allows you to move slightly further away from the video compared to zooming out from a video that wasn’t zoomed in initially.

https://github.com/user-attachments/assets/abf86f76-2783-4a78-8418-ec32a563bba3

### Steps to reproduce the issue

1. Find a 9:16 video (example: Telltales)
2. Go to fullscreen
3. Zoom in until the top says „Zoomed to fill“
4. Observe the issue

**Comment by bhackel** [comment]
Hey thanks for the report, since this is a bug in the stock YouTube app, we will have to wait for them to fix it.
