### ISSUE TITLE
[Bug] No Ambient Mode toggle in video player settings

### ISSUE THREAD

**Issue by garshmo** [YTLitePlus/YTLitePlus#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18 

### Device model

iPhone 13 Pro

### Sideload method

Sideloadly

### Tweak version

YTLitePlus - v19.34.2-5.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

There’s no longer the ambient mode toggle in the video player settings, so it can’t be toggled or used anymore 

### Steps to reproduce the issue

1. Play a video
2.  Go to the settings wheel at the top right of the video
3. Unable to toggle ambient mode, button missing
![IMG_2909](https://github.com/user-attachments/assets/f8b347cb-ddef-42c0-9b64-d096836e1778)

**Comment by trytolive** [comment]
same at here!

**Comment by bhackel** [comment]
New youtube change- you can toggle it off in YTLitePlus settings and I believe also in YouTube Plus settings now

**Comment by trytolive** [comment]
> New youtube change- you can toggle it off in YTLitePlus settings and I believe also in YouTube Plus settings now

Thank for check!
Tried turning it off in youtube plus settings v5.0.1, but nothing happens, ambient light still shows!
Toggle it off in YTLitePlus settings is worked!

**Comment by garshmo** [comment]
> New youtube change- you can toggle it off in YTLitePlus settings and I believe also in YouTube Plus settings now

The problem for me is that I want ambient mode on, but there’s no way in the video player or the settings to turn it on, the toggles in both sections of settings don’t turn it on, when toggled on or off in the settings nothing changes, still no ambient mode, have tried every combination I believe

**Comment by bhackel** [comment]
Strange that ambient mode is disabled for you. I would try looking in A/B settings for anything related to `ambient` and seeing if anything causes it to come back

**Comment by garshmo** [comment]
> Strange that ambient mode is disabled for you. I would try looking in A/B settings for anything related to `ambient` and seeing if anything causes it to come back

I fixed it by entirely reinstalling as a new app instead of installing on top of the previous version, thank you for help/suggestions

**Comment by Kenry021** [comment]
@bhackel Strangely enough, I tried everything on here to fix the missing Ambient Mode toggle, and it still wouldn't appear for me.

**Comment by trytolive** [comment]
> @bhackel Strangely enough, I tried everything on here to fix the missing Ambient Mode toggle, and it still wouldn't appear for me.

>>>New youtube changed
So you can toggle it off in YTLitePlus settings  (YouTube Plus has build in that settings now, but it not worked)

**Comment by trytolive** [comment]
> @bhackel Strangely enough, I tried everything on here to fix the missing Ambient Mode toggle, and it still wouldn't appear for me.

No Ambien mode toggle in new youtube version, google was changed/deleted it
So you can toggle it off in YTLitePlus settings  (YouTube Plus 5.0.1 has build in that settings, but is no worked)

**Comment by Kenry021** [comment]
> > @bhackel Strangely enough, I tried everything on here to fix the missing Ambient Mode toggle, and it still wouldn't appear for me.
> 
> No Ambien mode toggle in new youtube version, google was changed/deleted it So you can toggle it off in YTLitePlus settings (YouTube Plus 5.0.1 has build in that settings, but is no worked)

Was it these? 
![Screenshot 2024-09-03 at 6 17 25 PM](https://github.com/user-attachments/assets/5e50aff0-1e18-4908-a807-479d0baf229c)
![IMG_2316](https://github.com/user-attachments/assets/6f47de7d-f432-4e46-9f04-e651cd6fbb07)

**Comment by trytolive** [comment]
> > > @bhackel Strangely enough, I tried everything on here to fix the missing Ambient Mode toggle, and it still wouldn't appear for me.
> > 
> > 
> > No Ambien mode toggle in new youtube version, google was changed/deleted it So you can toggle it off in YTLitePlus settings (YouTube Plus 5.0.1 has build in that settings, but is no worked)
> 
> Was it these? ![Screenshot 2024-09-03 at 6 17 25 PM](https://private-user-images.githubusercontent.com/101542293/364191295-5e50aff0-1e18-4908-a807-479d0baf229c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTMzMjUsIm5iZiI6MTcyNTQxMzAyNSwicGF0aCI6Ii8xMDE1NDIyOTMvMzY0MTkxMjk1LTVlNTBhZmYwLTFlMTgtNDkwOC1hODA3LTQ3OWQwYmFmMjI5Yy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDEyMzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY0YjVhYTgwNTVlM2I3ZTI3OTI2MTJkMjM4YWI0OTg1OGUxMTIzYmI4Nzg2ZTQ2NThiNjVlOWVhNGE3Mjg5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ADSIH0XVHxL_sEbBUTim0Vy_4n-tjdLV5iMS5yb6puQ) ![IMG_2316](https://private-user-images.githubusercontent.com/101542293/364191298-6f47de7d-f432-4e46-9f04-e651cd6fbb07.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTMzMjUsIm5iZiI6MTcyNTQxMzAyNSwicGF0aCI6Ii8xMDE1NDIyOTMvMzY0MTkxMjk4LTZmNDdkZTdkLWY0MzItNGU0Ni05ZjA0LWU2NTFjZDZmYmIwNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDEyMzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI4MTYxZTljNTc1NDk3YmJmYTNhYWQzMzQ3YjNlNDg4MWEzNWNkOWZlMDY1YWI4YjAwNWRkMTZhMjI4MzZkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9sHlHMccWlpacMJZ8nC1OH3g_l2kmu5eIjsrpM3F3wc)

yes, it is bottom photo settings

**Comment by Kenry021** [comment]
> > > > @bhackel Strangely enough, I tried everything on here to fix the missing Ambient Mode toggle, and it still wouldn't appear for me.
> > > 
> > > 
> > > No Ambien mode toggle in new youtube version, google was changed/deleted it So you can toggle it off in YTLitePlus settings (YouTube Plus 5.0.1 has build in that settings, but is no worked)
> > 
> > 
> > Was it these? ![Screenshot 2024-09-03 at 6 17 25 PM](https://private-user-images.githubusercontent.com/101542293/364191295-5e50aff0-1e18-4908-a807-479d0baf229c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTMzMjUsIm5iZiI6MTcyNTQxMzAyNSwicGF0aCI6Ii8xMDE1NDIyOTMvMzY0MTkxMjk1LTVlNTBhZmYwLTFlMTgtNDkwOC1hODA3LTQ3OWQwYmFmMjI5Yy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDEyMzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY0YjVhYTgwNTVlM2I3ZTI3OTI2MTJkMjM4YWI0OTg1OGUxMTIzYmI4Nzg2ZTQ2NThiNjVlOWVhNGE3Mjg5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ADSIH0XVHxL_sEbBUTim0Vy_4n-tjdLV5iMS5yb6puQ) ![IMG_2316](https://private-user-images.githubusercontent.com/101542293/364191298-6f47de7d-f432-4e46-9f04-e651cd6fbb07.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTMzMjUsIm5iZiI6MTcyNTQxMzAyNSwicGF0aCI6Ii8xMDE1NDIyOTMvMzY0MTkxMjk4LTZmNDdkZTdkLWY0MzItNGU0Ni05ZjA0LWU2NTFjZDZmYmIwNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDEyMzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI4MTYxZTljNTc1NDk3YmJmYTNhYWQzMzQ3YjNlNDg4MWEzNWNkOWZlMDY1YWI4YjAwNWRkMTZhMjI4MzZkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9sHlHMccWlpacMJZ8nC1OH3g_l2kmu5eIjsrpM3F3wc)
> 
> yes, it is bottom photo settings

Still, doesn't work :/

https://github.com/user-attachments/assets/f1971d76-b4a7-49fb-a22e-4b081d7c9a24

**Comment by trytolive** [comment]
> > > > > @bhackel Strangely enough, I tried everything on here to fix the missing Ambient Mode toggle, and it still wouldn't appear for me.
> > > > 
> > > > 
> > > > No Ambien mode toggle in new youtube version, google was changed/deleted it So you can toggle it off in YTLitePlus settings (YouTube Plus 5.0.1 has build in that settings, but is no worked)
> > > 
> > > 
> > > Was it these? ![Screenshot 2024-09-03 at 6 17 25 PM](https://private-user-images.githubusercontent.com/101542293/364191295-5e50aff0-1e18-4908-a807-479d0baf229c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTMzMjUsIm5iZiI6MTcyNTQxMzAyNSwicGF0aCI6Ii8xMDE1NDIyOTMvMzY0MTkxMjk1LTVlNTBhZmYwLTFlMTgtNDkwOC1hODA3LTQ3OWQwYmFmMjI5Yy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDEyMzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY0YjVhYTgwNTVlM2I3ZTI3OTI2MTJkMjM4YWI0OTg1OGUxMTIzYmI4Nzg2ZTQ2NThiNjVlOWVhNGE3Mjg5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ADSIH0XVHxL_sEbBUTim0Vy_4n-tjdLV5iMS5yb6puQ) ![IMG_2316](https://private-user-images.githubusercontent.com/101542293/364191298-6f47de7d-f432-4e46-9f04-e651cd6fbb07.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTMzMjUsIm5iZiI6MTcyNTQxMzAyNSwicGF0aCI6Ii8xMDE1NDIyOTMvMzY0MTkxMjk4LTZmNDdkZTdkLWY0MzItNGU0Ni05ZjA0LWU2NTFjZDZmYmIwNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDEyMzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI4MTYxZTljNTc1NDk3YmJmYTNhYWQzMzQ3YjNlNDg4MWEzNWNkOWZlMDY1YWI4YjAwNWRkMTZhMjI4MzZkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9sHlHMccWlpacMJZ8nC1OH3g_l2kmu5eIjsrpM3F3wc)
> > 
> > 
> > yes, it is bottom photo settings
> 
> Still, doesn't work :/
> 
>  freecompress-2024-09-03.18.28.mp4

Are you sure you understand what those toggles do?

**Comment by Kenry021** [comment]
@trytolive disable ambient mode for both portrait and fullscreen?

**Comment by trytolive** [comment]
> @trytolive disable ambient mode for both portrait and fullscreen?

If you want to disable ambient, push the toggle on, if you want to disable it, do the opposite. 
This setting is not to show the option in the video settings menu.

**Comment by Kenry021** [comment]
@trytolive Yeah, I know I'm trying to get the Ambient Mode toggle in video player settings to reappear. The original person managed to get it to appear again, so I'm trying to get the option to appear again because it doesn't appear for me...

**Comment by trytolive** [comment]
> @trytolive Yeah, I know I'm trying to get the Ambient Mode toggle in video player settings to reappear. The original person managed to get it to appear again, so I'm trying to get the option to appear again because it doesn't appear for me...

it won't reappear if it was previously disabled, the only way is to delete youtube and entirely reinstalling as a new app instead of installing on top of the previous version

**Comment by Kenry021** [comment]
@trytolive i just deleted and reinstalled as a new app and same thing still happens...

**Comment by trytolive** [comment]
> @trytolive i just deleted and reinstalled as a new app and the same thing still happens...

Go to Youtube Plus Settings and clear cache
![Uploading IMG_7955.png…]()

**Comment by Kenry021** [comment]
@trytolive I just did it and got the same result...

**Comment by trytolive** [comment]
> @trytolive I just did it and got the same result...

what sideloadly tool you used?
If it is SideStore follow below,
Turn on VPN -> Open SideStore -> Apps -> Long press Youtube and select deactivate -> then long press and select Delete -> Restart phone and install latest ytliteplus and open video and check after install

**Comment by Kenry021** [comment]
@trytolive its altstore

**Comment by trytolive** [comment]
> @trytolive its altstore

Same method can be used for AltStore, but step 1 you will need to connect to pc

**Comment by trytolive** [comment]
> > @trytolive its altstore
> 
> Same  that method can be used for AltStore, but step 1 you will need to connect to pc

**Comment by Kenry021** [comment]
@trytolive Interesting... i did all of those things just for it to show the same result of Ambient Mode toggle in video player still not appearing... i even rebuilt the IPA myself using the latest commits on my fork...

**Comment by trytolive** [comment]
> @trytolive Interesting... i did all of those things just for it to show the same result of Ambient Mode toggle in video player still not appearing... i even rebuilt the IPA myself using the latest commits on my fork...

try ipa i send for u and check ambient mode toggle will show in setting of video player

**Comment by Kenry021** [comment]
@trytolive i already tried with multiple ipas and got the same result...

**Comment by trytolive** [comment]
![Uploading z5795706212317_5da1fd2b3f4c83242669ece95dcf77ec.jpg…]()

**Comment by trytolive** [comment]
> @trytolive i already tried with multiple ipas and got the same result...

I was wondering why ambient mode is so important to you?
if is you try to move to sidestore and try to install this ipa file at this url https://github.com/YTLitePlus/YTLitePlus/actions/runs/10688653647

**Comment by Kenry021** [comment]
> > @trytolive i already tried with multiple ipas and got the same result...
> 
> I was wondering why ambient mode is so important to you? if is you try to move to sidestore and try to install this ipa file at this url https://github.com/YTLitePlus/YTLitePlus/actions/runs/10688653647

I never really cared about ambient mode its just that the app felt off after getting used to it for a long time...

**Comment by trytolive** [comment]
> > > @trytolive i already tried with multiple ipas and got the same result...
> > 
> > 
> > I was wondering why ambient mode is so important to you? if is you try to move to sidestore and try to install this ipa file at this url https://github.com/YTLitePlus/YTLitePlus/actions/runs/10688653647
> 
> I never really cared about ambient mode its just that the app felt off after getting used to it for a long time...

I understand how you feel,
Don't give up because it can be fix.

**Comment by Kenry021** [comment]
@trytolive btw for this link https://github.com/YTLitePlus/YTLitePlus/actions/runs/10688653647 did you download it through here?
![Screenshot 2024-09-03 214619](https://github.com/user-attachments/assets/f3a59f69-acae-40a8-baa8-600d35785e99)

**Comment by trytolive** [comment]
it is like this https://imgur.com/a/NxUoUEc

**Comment by trytolive** [comment]
> @trytolive btw for this link https://github.com/YTLitePlus/YTLitePlus/actions/runs/10688653647 did you download it through here? ![Screenshot 2024-09-03 214619](https://private-user-images.githubusercontent.com/101542293/364226955-f3a59f69-acae-40a8-baa8-600d35785e99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjU1NDYsIm5iZiI6MTcyNTQyNTI0NiwicGF0aCI6Ii8xMDE1NDIyOTMvMzY0MjI2OTU1LWYzYTU5ZjY5LWFjYWUtNDBhOC1iYWE4LTYwMGQzNTc4NWU5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwNDQ3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODRmMjkzNGE5MmVlZjNjY2JiMGE5NDBlMGRkYWQwMTZmMGE3MjVmMGI1YjVkNWI2NGI2NDQ0NjMyMzlmYjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5JZGzuf9L15Lv5LdL5ZXjuNytbJtqGnG9UpJ_fyqjos)

Yes yes, after downloading it will be a ZIP file, you need to unzip it to get the ipa file

**Comment by Kenry021** [comment]
oh okay @trytolive

**Comment by trytolive** [comment]
> oh okay @trytolive

I will wait for your result

**Comment by Kenry021** [comment]
> oh okay @trytolive

I can't do it right now because im kinda busy so i will do it whenever i can

**Comment by trytolive** [comment]
> > oh okay @trytolive
> 
> I can't do it right now because im kinda busy so i will do it whenever i can
yeah, I will wait for your result

**Comment by trytolive** [comment]
> > oh okay @trytolive
> 
> I can't do it right now because im kinda busy so i will do it whenever i can

yeah. i will wait for your result

**Comment by bhackel** [comment]
If that doesn’t work, I can try write something to force-enable it

**Comment by trytolive** [comment]
> If that doesn’t work, I can try write something to force-enable it

why in the latest version you sent me yesterday it feels laggy when scroll home page on my 15 pro max ios 17.6.1

**Comment by bhackel** [comment]
> why in the latest version you sent me yesterday it feels laggy when scroll home page on my 15 pro max ios 17.6.1

Hmm sounds strange. I am on 15 Pro Max and not having laggy issues. I would try exporting settings and reinstalling to see if the issue goes away, then checking what setting is contributing to the lag

**Comment by Kenry021** [comment]
@bhackel @trytolive Unfortunately I just installed the IPA from this link https://github.com/YTLitePlus/YTLitePlus/actions/runs/10688653647 that "trytolive" gave me and it still does the exact same behavior of not showing Ambient Mode toggle in the video player settings...

**Comment by trytolive** [comment]
> @bhackel @trytolive Unfortunately I just installed the IPA from this link https://github.com/YTLitePlus/YTLitePlus/actions/runs/10688653647 that "trytolive" gave me and it still does the exact same behavior of not showing Ambient Mode toggle in the video player settings...

i think it might be because the app cache is still there even though it was uninstalled before, i had it several times yesterday when trying to install different versions to open the ambient toggle in video player setting. and then i uninstalled it completely by deactivating in sidestore settings, then deleting it, clearing iphone cache with 3utools, then rebooting and reinstalling the version that @bhackel sent me, it showed the ambient mode toggle again

**Comment by trytolive** [comment]
> > why in the latest version you sent me yesterday it feels laggy when scroll home page on my 15 pro max ios 17.6.1
> 
> Hmm sounds strange. I am on 15 Pro Max and not having laggy issues. I would try exporting settings and reinstalling to see if the issue goes away, then checking what setting is contributing to the lag

It's such good news! thank you for your hard work.

**Comment by garshmo** [comment]
I did not get the toggle to reappear, I reinstalled the app completely and get ambient mode working again, never was there a toggle in the player, it just started working correctly

**Comment by garshmo** [comment]
I just checked mine and now I have the button in the player too, must have been server side on YouTube’s part

**Comment by garshmo** [comment]
Think we’ll just have to wait for YouTube to get it right. I don’t think it’s YTLitePlus doing it
