### ISSUE TITLE
YouLoop seems to be crashing

### ISSUE THREAD

**Issue by schweppes-0x** [YTLitePlus/YTLitePlus#399]
Looks like when I toggle YouLoop in video overlay, youtube immediately crashes.

**Comment by bhackel** [comment]
I see, I am not getting this issue. Do you have a crash log?

**Comment by trytolive** [comment]
Same at here

> Looks like when I toggle YouLoop in video overlay, youtube immediately crashes.

If you enabled SponsorBlock build-in of Youtube Plus, you see this bug. Turn it off and use sponsorblock extension by ytliteplus

**Comment by trytolive** [comment]
> I see, I am not getting this issue. Do you have a crash log?

This error occurs if you enable sponsorblock build in settings of youtube plus (not extension like ytliteplus)

**Comment by bhackel** [comment]
Ah thank you, I am able to replicate now. Will take a look

**Comment by bhackel** [comment]
It seems like it does not crash when the button is placed at the bottom of the screen. I have also located the issue, and will be updating it soon

**Comment by trytolive** [comment]
> It seems like it does not crash when the button is placed at the bottom of the screen. I have also located the issue, and will be updating it soon

Thank you, when you fix it, please share the build ipa file, and thank you so much if it is version 19.35.3

**Comment by bhackel** [comment]
Fixed in latest here: https://github.com/YTLitePlus/YTLitePlus/actions/runs/10688653647

I unfortunately don't have my trollstore phone, so I cannot generate an updated iPA at the moment. 
Thank you for your help

**Comment by schweppes-0x** [comment]
ur da best!

**Comment by trytolive** [comment]
can u  get the Decrypted iOS IPA at here. Thank you so much
https://armconverter.com/decryptedappstore/us/youtube
