### ISSUE TITLE
[Bug] Shorts Crashing on the latest release

### ISSUE THREAD

**Issue by CiroHoodLove** [YTLitePlus/YTLitePlus#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6.1

### Device model

iPhone 11

### Sideload method

ESign - Telegram Repo

### Tweak version

YTPlus - 19.35.3-5.01

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

Okey so i got 2 points and one isn’t a bug but an oversight i might say
- the shorts crash the app when you watch more than 2 or 3 it varies from time to time sometimes 1 (like in the attached video ) sometimes even 4
- Also the oversight is , when you remove the library from the tab bar , you won’t be able to access the settings again , i had to reinstall youtube again to have it show up again 
![IMG_2038](https://github.com/user-attachments/assets/3822a3b1-0102-41c2-9099-931cf18faa02)

https://github.com/user-attachments/assets/eec133df-019a-48bf-8a1d-0c982250bf88

### Steps to reproduce the issue

1. Open Youtube
2. Click on Shorts
3. Scroll and it will crash

1. Open Youtube 
2. Navigate to Settings > Youtube Plus > Tab Bar 
3. Remove Library

### Crash log (if the app crashes)

```shell
Didn’t find the Analytics & Improvements Option in the settings
```

**Comment by bhackel** [comment]
You can toggle hide/unhide You tab by long pressing home tab. The crash log is in Apple settings app. Also if you could export your YouTube Plus settings and upload those here, that might help

**Comment by CiroHoodLove** [comment]
Okey that long pressing thingie worked but i think you should point that somewhere in the Tab Bar settings , maybe write it in small letters in the bottom section or beside the Library one 

, also couldn’t attach the settings i exported so heres a link  https://easyupload.io/5p86ve

And in the settings app it didn’t register the crashes, i don’t see them 
![IMG_2048](https://github.com/user-attachments/assets/38d7b485-589c-4902-90e7-336189c0eb25)

**Comment by CiroHoodLove** [comment]
Actually it was in the **End** Lol here they are , i attached a couple of them because some have different scenario so, for context the last ones happened while i was watching a video then clicked on a short , it crashed immediately, whereas the last one crashed in the same scenario but after i scrolled it didn’t immediately crash 

**Couldn’t attach them here again** : https://easyupload.io/m/0cb8oh

**Comment by bhackel** [comment]
Just to clarify, I do not develop YouTube Plus, that is from another developer, but I will try to figure out the issue. Can you send a screenshot of your shorts settings?

Also, can you try disabling Downloads Manager and seeing if it fixes your issue?

**Comment by bhackel** [comment]
Sorry I didn’t see that you sent your setting already, I will take a look

**Comment by CiroHoodLove** [comment]
Disabling the Download manager doesn’t fix it i Tried before i opened this issue because i came across that fix on 4.0.1

**Comment by bhackel** [comment]
I guess something to try would be resetting your settings and seeing if you still get crashes. That would make it much easier to determine the cause

**Comment by bhackel** [comment]
Try disabling shorts default quality

**Comment by CiroHoodLove** [comment]
Disabling Default Quality actually fixed it , it didn’t crash no more , the only bad thing is i really wanted this feature since i started using YTLitePlus 🥲, but that’s that its no longer crashing i just set the shorts default quality to default 

P.S : i Didn’t Reset the whole settings

**Comment by bhackel** [comment]
Are you hav

**Comment by CiroHoodLove** [comment]
Yeah actually, i mean no there’s 2 VP9 options i enable the 1 one , i used to get bad quality on all shorts even when internet is fine when enabling the both of them , but now i only enable the 1 one and the quality is normal but i would rather make it always choose 1080p60 
![IMG_2051](https://github.com/user-attachments/assets/44484210-3787-41b2-a1df-170ee6c7fc21)

**Comment by bhackel** [comment]
Yep, enabling just the one is good. Maybe you can use Best quality option instead. Good to try things out

**Comment by CiroHoodLove** [comment]
Yeah , i’m all to reporting bugs for the better optimisation for everyone 
also i set the default quality to best and it still crashed so i guess that’s whats causing the crash so , i don’t know which dev is responsable for it so idk who to tag

**Comment by bhackel** [comment]
Yep no worries, you can report it here: https://github.com/dayanch96/YTLite/issues

Recommended to come report bugs here first, then we report to each separate tweak

**Comment by CiroHoodLove** [comment]
is there a way i can forward this issue directly there ?

**Comment by bhackel** [comment]
Not dire

**Comment by CiroHoodLove** [comment]
alright i submitted it to https://github.com/dayanch96/YTLite/issues/172
