### ISSUE TITLE
[Bug] YouTube interface scrolls to the top (19.35)

### ISSUE THREAD

**Issue by CiroHoodLove** [YTLitePlus/YTLitePlus#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.6.1

### Device model

iPhone 11

### Sideload method

Esign 

### Tweak version

YTPlus-19.35.3-5.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

when you’re enter the YouTube app and scroll on the homepage whenever you reach the end of that section for more content to load it brings you to the top and even if you keep doing that it still send you to the top

https://github.com/user-attachments/assets/17313b74-b58f-4151-9d53-e4aa58b46719

### Steps to reproduce the issue

1. Open Youtube
2. Scroll Until the end of the loaded content
3. done

### Crash log (if the app crashes)

```shell
No Crash
```

**Comment by bhackel** [comment]
Very strange, can you export your settings and attach here?

**Comment by CiroHoodLove** [comment]
Sure , here you go

https://easyupload.io/o6cw6t

**Comment by YokukYo** [comment]
"This bug might be from YouTube. I'm using version 19.35.3 and I have the same issue."

**Comment by CiroHoodLove** [comment]
i have the official youtube running on the same version alongside YTPlus , i couldn’t recreate it in the official app on 19.35.3

**Comment by CiroHoodLove** [comment]
Update : i actually got the same issue today with the official youtube app so i guess you were rights its a bug on 19.35.3
