### ISSUE TITLE
[Bug] YT native share sheet crashes on iPhone and iPad (19.35)

### ISSUE THREAD

**Issue by Macleykun** [YTLitePlus/YTLitePlus#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18 beta

### Device model

iPhone 13 and ipad 2020

### Sideload method

Sidestore

### Tweak version

YTLitePlus_19.35.3_5.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

When going into settings > Youtube Plus > interface > Enable native share sheet it will crash if you click on the 3 dots on a video, and then choose the share option.

### Steps to reproduce the issue

When going into settings > Youtube Plus > interface > Enable native share sheet it will crash if you click on the 3 dots on a video, and then choose the share option.

### Additional context

[YouTube-2024-09-04-225624.ips.txt](https://github.com/user-attachments/files/16880811/YouTube-2024-09-04-225624.ips.txt)

**Comment by bhackel** [comment]
Not having this issue on 19.34, maybe it’s a new thing on 19.35?

**Comment by Macleykun** [comment]
> Not having this issue on 19.34, maybe it’s a new thing on 19.35?

Yup your fully correct
Switched to the one you mentioned and on both it works! Odd that yt changed smth in the share sheet.. but thanks! I’ll use the older version for now but will keep this open (if there’s smth else I can supply of logging do let me know!)

**Comment by Macleykun** [comment]
The issue is fixed upstream, so i'll close this one!
