### ISSUE TITLE
[Request] 4K + HDR support

### ISSUE THREAD

**Issue by SoulReaverFan** [YTLitePlus/YTLitePlus#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

Implement 4K + HDR hardware support.

### Additional context

I recently noticed that 4K + HDR works in Safari, so I’m guessing this is hardware support without vp9 codec requirement?

Is it possible to implement this for the app so we don’t have to use the software VP9 decoding for sideloaded YT ipas?

Thanks for your help :)

**Comment by dayanch96** [comment]
It’s not possible.

The VP9 codec is deeply integrated into Safari’s WebKit, which natively supports VP9 playback.

All App Store apps, including sideloaded ones, require a special entitlement to use the VP9 codec, and only Apple can grant this entitlement. In Google’s case, Apple has granted this to their App Store account (team ID).

When you decrypt and resign an app using your own account, the app loses this special entitlement for VP9 support.

YTUHD relies on hardware acceleration. If your device isn’t powerful enough to download media, convert it in real-time to a supported format, and play it at the same time, you may and probably will experience buffering and overheating issues.

**Comment by SoulReaverFan** [comment]
Wow nice! Thank you for the detailed reply I have an AV1 supported device but did not know YTUHD would take advantage of it as I thought it was only about VP9. 

Thank you so much for the detailed reply! Learned something new today 👍

**Comment by SoulReaverFan** [comment]
> It’s not possible.
> 
> The VP9 codec is deeply integrated into Safari’s WebKit, which natively supports VP9 playback.
> 
> All App Store apps, including sideloaded ones, require a special entitlement to use the VP9 codec, and only Apple can grant this entitlement. In Google’s case, Apple has granted this to their App Store account (team ID).
> 
> When you decrypt and resign an app using your own account, the app loses this special entitlement for VP9 support.
> 
> YTUHD relies on hardware acceleration. If your device isn’t powerful enough to download media, convert it in real-time to a supported format, and play it at the same time, you may and probably will experience buffering and overheating issues.
> 
> However, this doesn’t apply to the iPhone 14, 15, and 16 **PRO** series, which natively support the AV1 codec without requiring any special entitlements.

Do you get AV1 being used on 14 Pro and up using YTLitePlus on 4K60 HDR videos when checking stats for nerds cause I do not :( Anyway to force that codec being used? :)

**Comment by dayanch96** [comment]
> I think only the A17 Pro chipset and later supports it.

Sorry, my bad. Yeah, seems like it supported on A17+
