### ISSUE TITLE
[Bug] Videos don't go in History

### ISSUE THREAD

**Issue by JakeytheeClown** [YTLitePlus/YTLitePlus#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.0.3

### Device model

iPhone SE (3rd Generation)

### Sideload method

Altstore

### Tweak version

YTLitePlus 19.34.2-5.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

[Video of the issue](https://files.catbox.moe/gpbd3j.mp4) 

### Steps to reproduce the issue

1. Go on Youtube
2. Watch a Video
3. Check History

**Comment by JakeytheeClown** [comment]
> Swipe down to update

I already did that

**Comment by Joshua-18** [comment]
Had the same problem as you did years back, turns out it was adguard home (system wide adblocking) blocking something YouTube needs im order for history to work.

**Comment by JakeytheeClown** [comment]
> Had the same problem as you did years back, turns out it was adguard home (system wide adblocking) blocking something YouTube needs im order for history to work.

**Comment by JakeytheeClown** [comment]
Ty My DNS was messing it up
