### ISSUE TITLE
[Bug] home bar is not disappearing in full screen mode

### ISSUE THREAD

**Issue by swajcitytrick** [YTLitePlus/YTLitePlus#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18.0

### Device model

iPhone 13 Pro

### Sideload method

AppDB Self Upload IPA

### Tweak version

YTLitePlus - v19.34.2-5.0.1

### Do you use YouTube Premium?

✅ Yes, I do use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

✅ Yes, I can reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

The home bar (the one you use to exit apps) doesn’t disappear as fast as it did with uYouEnhanced

### Steps to reproduce the issue

1. Start a Video
2. Go Fullscreen Landscape
3. Home Bar stays on screen

**Comment by Blarnix** [comment]
I've also had this issue. Any idea what's causing it?

**Comment by Balackburn** [comment]
If it's reproducible in the official YouTube app and doesn't come from YTLitePlus, I can't fix it, sorry.

**Comment by dayanch96** [comment]
its youtube issue. they fix and break it again and again with their updates
