### ISSUE TITLE
[Request] Release for AltStore PAL?

### ISSUE THREAD

**Issue by KannaHayabusa** [YTLitePlus/YTLitePlus#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

I've been thinking of switching to iOS for a while now and once I switch I need to find a good replacement for YouTube ReVanced/Grayjay. Now I could definitely sideload it via the regular AltStore but could it be possible to have to this released on AltStore PAL to make the whole experience a little easier?

**Comment by Balackburn** [comment]
It's not possible unfortunatly
