### ISSUE TITLE
[Bug] Crashes on Launch

### ISSUE THREAD

**Issue by FriedEngineer** [YTLitePlus/YTLitePlus#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS/iPadOS 18.0

### Device model

iPhone 15 Pro & iPad Pro 11” 20

### Sideload method

Sideloadly

### Tweak version

YTLitePlus - v19.34.2-5.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

Starting sometime in the last few hours, when I try to launch it on either my iPad or iPhone the app immediately crashes.

I’ve tried rebooting my devices and force quitting it (though it often is not in the background after it crashes)

https://github.com/user-attachments/assets/79b18a78-3802-4437-8188-8d76423432da

### Steps to reproduce the issue

1. Try to open app from the Home Screen or search
2. See it open briefly (just a black screen)
3. Say hello again to your Home Screen after a second.

### Crash log (if the app crashes)

I don’t see any logs here from today.

**Comment by FriedEngineer** [comment]
> Try this https://easyupload.io/3dd55b

No offense, but I’m not going to try a download from an unknown source. Based on the name of your ipa, I assume you’ve just rebuilt the current release with a newer version of YouTube (19.37.2) so I can try that myself.

**Comment by FriedEngineer** [comment]
Building using the current commit, 5fbb9ebadaf76d6901413cbe58b5c88d913576a5, and YouTube v19.37.2 does work.

**Comment by dayanch96** [comment]
> I do get this "Incompatible Tweaks Detected" on every fresh launch.

That’s not issue, will be less intrusive with the release of version 5.1 though
