### ISSUE TITLE
[Request] Add tvOS compatibility

### ISSUE THREAD

**Issue by antoniiolpzzz** [YTLitePlus/YTLitePlus#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### My feature request

Modify youtube client for tvOS to be compatible with the same "plugins" as IOS versions.

### Additional context

Given that Apple TV is now allowing more users to install .IPA files due to new ways to install trollstore, there will be more users interested on this tvOS version os your app.

**Comment by Balackburn** [comment]
Unfortunately this isn't possible for now.
