### ISSUE TITLE
[Bug] Timed comments skipping randomly to other timed comments

### ISSUE THREAD

**Issue by harrobe123** [YTLitePlus/YTLitePlus#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iPadOS 18

### Device model

iPad Air 5

### Sideload method

Sidestore

### Tweak version

YTLitePlus 19.34.2-5.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

Timed comments skipping around from right timestamps to wrong timestamps

### Steps to reproduce the issue

1. Find a video
2. Go to comments
3. Press "Timed"

### Additional context

Video not uploading?

**Comment by a-plastic-bag** [comment]
Yeah, I've been seeing the same issue for a while now on iOS 18.

**Comment by dayanch96** [comment]
could be server-side issue
