### ISSUE TITLE
[Bug] error 2 during compilation (macos-13 and up)

### ISSUE THREAD

**Issue by xxxkowal** [YTLitePlus/YTLitePlus#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 17.5.1

### Device model

iPhone 15 pro

### Sideload method

altstore

### Tweak version

with newest commit f445253

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

During compilation with GiTHub actions with newest commit f445253 i got bug (error 2)

![image](https://github.com/user-attachments/assets/a6d03c0e-1f3b-4839-be7b-381c0fbf9fc6)

youtube 19.40.4

### Steps to reproduce the issue

1. 
2. 
3.

**Comment by SuperAmirhamza** [comment]
got same issue

**Comment by QziP22** [comment]
same issue 
![Screenshot 2024-10-12 at 22-42-20 Build and Release YTLitePlus · QziP22_YTLitePlus@1ae3f99](https://github.com/user-attachments/assets/2dedc66d-2861-4a89-b544-3d7d4eb33a81)

**Comment by MrSco** [comment]
Same issue

`> Making all in Tweaks/YTUHD…
> Making all for tweak YTUHD…
==> Preprocessing Settings.x…
==> Preprocessing Common.x…
==> Preprocessing Tweak.xm…
==> Compiling Common.x (arm64)…
In file included from Tweak.xm:1:
/Users/runner/work/YTLitePlus/YTLitePlus/theos/vendor/include/substrate.h:45:1: error: import of C++ module 'MachO.nlist' appears within extern "C" language linkage specification [-Wmodule-import-in-extern-c]
#include <mach-o/nlist.h>
^
/Users/runner/work/YTLitePlus/YTLitePlus/theos/vendor/include/substrate.h:43:1: note: extern "C" language linkage specification begins here
extern "C" {
^
1 error generated.`

**Comment by hanhwa12** [comment]
Same issue with youtube 19.40.4

**Comment by Skawtnyc** [comment]
Also with YT 19.41.3. YTLite/Youtube Plus do compile.

**Comment by ismailshaikh118** [comment]
Same issue

**Comment by Yunogamer** [comment]
is this project still alive..?

**Comment by SuperAmirhamza** [comment]
> is this project still alive..?

I've been wondering that myself I remember this used to be updated every week sometimes even less

**Comment by Balackburn** [comment]
> > is this project still alive..?
> 
> I've been wondering that myself I remember this used to be updated every week sometimes even less

Not really as @dayanch96 made YTPlus incompatible (crash at launch) with YTLitePlus, I am waiting for a new version that will remove the break.

**Comment by ggr8** [comment]
> Not really as @dayanch96 made YTPlus incompatible (crash at launch) with YTLitePlus, I am waiting for a new version that will remove the break.

Intentionally, or due to an update to be compatible with an YouTube update?
The 5.0.1 ipa is still around the place. IYKYK.

**Comment by Yunogamer** [comment]
last commits didnt work, still broken

**Comment by MrSco** [comment]
Still failing the build.

**Comment by MrSco** [comment]
I was just able to build successfully with current commit

**Comment by Yunogamer** [comment]
>Unfortunately it’ll stop working in 2 months which was something I was trying to prevent.

and thats cause..?

**Comment by SuperAmirhamza** [comment]
![image](https://github.com/user-attachments/assets/bdf7dc78-5e97-417a-9ce0-5973df3268af)
Is there any way to remove this pop up every time I open the app

**Comment by CreepsoOff** [comment]
> > ![image](https://private-user-images.githubusercontent.com/45406543/378011636-bdf7dc78-5e97-417a-9ce0-5973df3268af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NDQ1MzIsIm5iZiI6MTcyOTU0NDIzMiwicGF0aCI6Ii80NTQwNjU0My8zNzgwMTE2MzYtYmRmN2RjNzgtNWU5Ny00MTdhLTljZTAtNTk3M2RmMzI2OGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDIwNTcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOTY5N2VmZGNlOTViMTQzMjhlYTkzMWJiNDBkNTY3NTAyOTQzY2M4Yjc0OWI3N2JjNTRkZjg4ODA4ZGFkMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rUAgpfc3hhZKfpJ-54OQgDUhgtdLfWte8A7Yj1gq3xA) Is there any way to remove this pop up every time I open the app
> 
> at the moment there is no way to remove it. I would like to but I really don’t want to disrespect the original developer of YTLite. :(

It bypasses it automatically on my end..?

![IMG_0352](https://github.com/user-attachments/assets/b3bbc240-527b-4a95-9b6f-ecb425bc6302)

**Comment by oldman20** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/45406543/378011636-bdf7dc78-5e97-417a-9ce0-5973df3268af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NDQ1MzIsIm5iZiI6MTcyOTU0NDIzMiwicGF0aCI6Ii80NTQwNjU0My8zNzgwMTE2MzYtYmRmN2RjNzgtNWU5Ny00MTdhLTljZTAtNTk3M2RmMzI2OGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDIwNTcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOTY5N2VmZGNlOTViMTQzMjhlYTkzMWJiNDBkNTY3NTAyOTQzY2M4Yjc0OWI3N2JjNTRkZjg4ODA4ZGFkMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rUAgpfc3hhZKfpJ-54OQgDUhgtdLfWte8A7Yj1gq3xA) Is there any way to remove this pop up every time I open the app
> > > 
> > > 
> > > at the moment there is no way to remove it. I would like to but I really don’t want to disrespect the original developer of YTLite. :(
> > 
> > 
> > It bypasses it automatically on my end..?
> > ![IMG_0352](https://private-user-images.githubusercontent.com/51055703/380637416-b3bbc240-527b-4a95-9b6f-ecb425bc6302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTA2NzAsIm5iZiI6MTczMDE1MDM3MCwicGF0aCI6Ii81MTA1NTcwMy8zODA2Mzc0MTYtYjNiYmMyNDAtNTI3Yi00YTk1LTliNmYtZWNiNDI1YmM2MzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDIxMTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MDY4NTgzMDA2M2I5NTFiMDAxMGIyYzcxNzQxMzc1NGExOTU2YmY4OWRmZjk5MWRlYjkxNjJlYTk2YTY2N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7LRylFyLoUj_jLnEer85yO2dprYTnrhm1rJpV0hB4SQ)
> 
> Are you on an old release? The code was removed in commit [5eb16b0](https://github.com/YTLitePlus/YTLitePlus/commit/5eb16b09b23503dddcbb5e5da0a18b394e6b48dd)

Sorry, your mean current latest release repo can solve that popup? Or we need to edit smt?
