### ISSUE TITLE
[Bug] text context menu doesn't work in comments (Copy, paste, writing tool, etc.)

### ISSUE THREAD

**Issue by ywj515** [YTLitePlus/YTLitePlus#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18.1 beta 7

### Device model

iPhone 15 Pro Max

### Sideload method

Sideloadly

### Tweak version

YTLitePlus 19.34.2-5.0.1

### Do you use YouTube Premium?

✅ Yes, I do use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

Copy, paste not working
Using iPhone 15 Pro Max on iOS 18.1 beta 7

https://github.com/user-attachments/assets/fd4a4f10-68d6-479c-9b52-5658bb760acf

### Steps to reproduce the issue

Described on screen recording

**Comment by dayanch96** [comment]
has nothing to do with the app

**Comment by ywj515** [comment]
Still a prevalent bug for YTLitePlus, can't be reproduced for OG YT app, hope it'll be fixed soon!
