### ISSUE TITLE
[Bug] Lag/Freeze all over the app

### ISSUE THREAD

**Issue by antoniiolpzzz** [YTLitePlus/YTLitePlus#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

IOS 18.0.1

### Device model

iPhone 13

### Sideload method

AltStore

### Tweak version

YTLitePlus - v19.34.2-5.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

So at first i wanna remark that I'm using the AltStore repository IPA.

The problem is that, since the app is open for a few seconds/minutes, it starts to feels laggy (even freeze some times), animations stutter, gestures and UI responsiveness totally felts down, but this doesn't only affects the app itself, the entire OS becomes laggy as well, it turns difficult to get out of the app using the slide up gesture and the OS keeps extremely laggy until the app is closed from the recent apps. 

It feels like a memory leak or something like that, because it has the ability to affect the whole system.

### Steps to reproduce the issue

1.  Open the app
2. Use for some time, usually it takes a minute or more, but it could be seconds as well
3. Starts to feels laggy, not even allowing you to performs some gestures, like closing videos, moving from one tabs to others, or even close the app. Even using IOS if you don't close the app entirely.

**Comment by antoniiolpzzz** [comment]
So there must be something in common which is causing this to happen. The thing is... these two shares so many components, its not gonna be easy :(

**Comment by antoniiolpzzz** [comment]
apparently not my case, I'm spoofing the default one, which happen to be v18.49.3, but I'll look at it as well in case thats something related to it, thanks!

**Comment by dayanch96** [comment]
it's recommended to not spoof at all. google removing old ui settings and it will be even worse in the future

**Comment by antoniiolpzzz** [comment]
I was wrong on my previous comment. I wasn't spoofing any version, I was just using the default one.

So... First apologise for not being precise. Second, determinate that then the issue is not fixed and shouldn't be closed.
