### ISSUE TITLE
[Questions] what is causing this new MiniPlayer design?

### ISSUE THREAD

**Issue by harrobe123** [YTLitePlus/YTLitePlus#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

This miniplayer is showing then the normal one. It's like pip but a miniplayer instead. You can move it around this screen and it's round but not actual pip. there is nothing wrong with it but I'm used to the X in the bottom right rather than top left
![IMG_1797](https://github.com/user-attachments/assets/ca7797fe-40c9-4d8c-b1a1-44a5892b8411)

**Comment by harrobe123** [comment]
all I needed to do is disable "enabled pip styled mini player" and disable
"enabled floating mini player"

**Comment by JayceTheBased** [comment]
> all I needed to do is disable "enabled pip styled mini player" and disable "enabled floating mini player"

Thanks for sharing this, that worked perfectly for me to get the nice old miniplayer back.

> if this solution is too much then I will turn it into an YTLitePlus option next release.

I think it would be great if you could add this as an option, as with all due respect (not sure if it was something you changed or not), I really dislike the new miniplayer design. I play a lot of music playlists in the background with this app and the new miniplayer isn't conducive to that use case at all.

**Comment by Bykuvk** [comment]
These A/B settings to disable aren’t present on mine. Ver. 19.34.2-5.0.1.
