### ISSUE TITLE
[Bug] Double Notifications from Subscriptions

### ISSUE THREAD

**Issue by KayKay919** [YTLitePlus/YTLitePlus#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 16.4.1

### Device model

iPhone 14 Pro Max

### Sideload method

Trollstore

### Tweak version

YTLitePlus_19.41.3_5.0.2

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

As the titel says, I'm getting double notifications from my Subscriptions

### Steps to reproduce the issue

1. Install YTLitePlus
2. Sign in
3. Wait to get a notification and you will get them back to back

**Comment by dayanch96** [comment]
not the app/tweak issue. make sure you have enabled notifications only in one YouTube app
