### ISSUE TITLE
[Bug] Pop up prompt will appear every time

### ISSUE THREAD

**Issue by blue2018** [YTLitePlus/YTLitePlus#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

IOS18.1

### Device model

iPhone 16 plus 

### Sideload method

Sidestore

### Tweak version

YTLitePlus_19.34.2_5.0.2

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

![IMG_0001](https://github.com/user-attachments/assets/4a0e9865-36c6-4384-9edd-de3529101f7b)

### Steps to reproduce the issue

After the first installation, the above pop-up window will appear, and now there will be such a prompt every time it runs.

Prompt detected incompatible plugin, but there are no other YouTube plugins in the phone

May I ask how to repair it?

Thanks a lot!

**Comment by Balackburn** [comment]
Duplicate
