### ISSUE TITLE
[Bug] Unable to Build on Sonoma 15.1 (macos-12 deprecated error)

### ISSUE THREAD

**Issue by armendegga** [YTLitePlus/YTLitePlus#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18.1

### Device model

iPhone 15 Pro Max

### Sideload method

Sideloadly

### Tweak version

YTLitePlus - 19.34.2 - 5.0.1

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

When I am attempting to build using the Build Action, it errors out in the first 30 seconds stating macos-12 deprecated. I am running this from a Sonoma Mac on 15.1.

Latest commit: 8c774a5

I saw another bug report (#356) with a similar issue that showed some updates to make on the Makefile. When I tried that, the build process went longer, and then errored out with an error 2.

I am sure there is something basic i am missing, but i have searched, and tried editing the files as was called out in the previous report but i can't get it to build. 

### Steps to reproduce the issue

1. Try to build via actions.
2. 
3.

**Comment by Skawtnyc** [comment]
It will compile if you edit .github/workflows/buildapp.yml and change macos-12 to macos-15.

**Comment by armendegga** [comment]
THANK YOU!

**Comment by Skawtnyc** [comment]
Looks like the latest YouTube Build does break compiling, however.
![IMG_4518](https://github.com/user-attachments/assets/eaab66bc-288c-485c-8483-41659626ec26)

**Comment by armendegga** [comment]
That let me start to compile and then I got an error message

ld: warning: ignoring duplicate libraries: '-lc++'
ld: warning: search path '/Users/runner/work/YTLitePlus/YTLitePlus/theos/vendor/lib/iphone/rootful' not found
ld: building for 'iOS', but linking in dylib (/Users/runner/work/YTLitePlus/YTLitePlus/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd) built for 'iOS-simulator'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/runner/work/YTLitePlus/YTLitePlus/theos/makefiles/instance/library.mk:52: /Users/runner/work/YTLitePlus/YTLitePlus/main/.theos/obj/arm64/YTLitePlus.dylib] Error 1
make[2]: *** [/Users/runner/work/YTLitePlus/YTLitePlus/theos/makefiles/instance/library.mk:52: /Users/runner/work/YTLitePlus/YTLitePlus/main/.theos/obj/arm64/YTLitePlus.dylib] Error 2
make[1]: *** [/Users/runner/work/YTLitePlus/YTLitePlus/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make: *** [/Users/runner/work/YTLitePlus/YTLitePlus/theos/makefiles/master/rules.mk:119: YTLitePlus.all.tweak.variables] Error 2
Error: Process completed with exit code 2.

**Comment by armendegga** [comment]
It looks like with the latest YouTube build, and the latest YTLitePlus build (f198493), compiling works again.

**Comment by federicotorrielli** [comment]
@arichornlover stopped working just today, macos-12 was deprecated

**Comment by armendegga** [comment]
I reopened the issue.

**Comment by federicotorrielli** [comment]
Working fine right now, thanks!
