### ISSUE TITLE
Videos keep buffering and loading when watching videos and shorts

### ISSUE THREAD

**Issue by eobi1976** [YTLitePlus/YTLitePlus#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

18.1

### Device model

iPhone 15 pro max

### Sideload method

Altstore

### Tweak version

YRLitePlus 19.46.3-5.0.2

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

buildapp.yml (GitHub Actions)

### Describe the bug

Video keeps randomly buffering and loading the the loading symbol when watching videos and shorts.
Maybe it has something to do with VP9?

### Steps to reproduce the issue

1. Click on a couple of videos/shorts
2. Watch for a couple of seconds

**Comment by dayanch96** [comment]
you dont need vp9 at all on iphone 15 pro and 16 pro series. these models use avc codec instead. completely turning off ytuhd recommended
