### ISSUE TITLE
Dynamic Island bug

### ISSUE THREAD

**Issue by mutzingoyangee** [YTLitePlus/YTLitePlus#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS/iPadOS version

iOS 18.1.1

### Device model

iPhone 15 Pro

### Sideload method

Feather

### Tweak version

YTLitePlus - 19.47.7

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Are you using the newest version of YTLitePlus?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Method used to build the iPA

Downloaded from third party

### Describe the bug

After enabling background playback mode in YTLitePlus, dynamic island playback animation always appears in the app. Are there any related settings in A/B?
![IMG_0272](https://github.com/user-attachments/assets/4f2174dc-5595-4745-8d0b-9a5d112b49e8)

### Steps to reproduce the issue

Background playback Dynamic Island issue

**Comment by dayanch96** [comment]
probably provisioning issue. not related to tweak but sideloading overall
