### ISSUE TITLE
[Questions] Unable to install 

### ISSUE THREAD

**Issue by abhirooptalasila** [YTLitePlus/YTLitePlus#488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Hi
I'm trying to install it but running into some problems. The first time I tried, an "Invalid Parameters (1008) error popped up. 
When I tried again, it asked me to approve app permissions, but the progress is stuck at around 75%. 
Any suggestions?

**Comment by abhirooptalasila** [comment]
I just uninstalled Altstore and started from fresh. It worked then.

**Comment by Ahmosys** [comment]
> I just uninstalled Altstore and started from fresh. It worked then.

Okay, thanks you, I tried multiple times to install and finally work without any issues.
