### ISSUE TITLE
[Questions] Build sources and deploy

### ISSUE THREAD

**Issue by meoz** [YTLitePlus/YTLitePlus#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

I can't find a straightforward answer to this question:  
Is it possible to manually build the sources in Xcode and deploy them to a device using a developer account? If so, would this eliminate the need for jailbreaking?

**Comment by Balackburn** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### Do you think this is a bug?
> 
> ✅ Yes, I believe this is a bug. I will open a new issue with the bug template
> 
> ### My question
> 
> I can't find a straightforward answer to this question:  
> 
> Is it possible to manually build the sources in Xcode and deploy them to a device using a developer account? If so, would this eliminate the need for jailbreaking?
> 
> ### Additional context
> 
> _No response_

Use the GitHub actions, you can't build the source with Xcode as it's just tweaks injected into a decrypted YouTube .ipa
