### ISSUE TITLE
[BUG] Google Account Sign in doesn’t work with Scarlet 

### ISSUE THREAD

**Issue by BlueJeans7** [YTLitePlus/YTLitePlus#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.1.1
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Scarlet
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 18.45.2-2.4

### Describe the bug

After entering the email ID on sign in page, you’ll get a prompt saying, “Google couldn’t verify it’s safe.”

uYouPlusExtra IPA does allow you to sign in.

### Steps to reproduce the issue

1. Install YTLitePlus from Scarlet
2. Open YouTube app and try to sign in with your Google account 
3. It won’t let you sign in.
4. If you sideload using AltStore/SideStore it allows you to sign in.
5. uYouPlusExtra allows you to sign in to your Google account even when you sideload using Scarlet.

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Please add this app in the official repo of Scarlet. Or please have a repo created to be used with Scarlet.

**Comment by Balackburn** [comment]
Hello could you try with latest version it should be fixed

**Comment by BlueJeans7** [comment]
Scarlet is revoked. Will have to wait for sometime to test this. Thanks.

**Comment by Balackburn** [comment]
> Still can’t sign in with Google account when using Scarlet. v18.48.3-2.4
> 
> ![IMG_5979](https://github.com/Balackburn/YTLitePlus/assets/24786247/399264db-fede-4a75-aae0-4037b58ad17f)
> 
> 

Try this https://www.icloud.com/shortcuts/214c4403becb4c25911471a3b84a1c42

**Comment by Balackburn** [comment]
Could you try with Sideloadly instead? I never had this issue myself don't know if this is from Scarlet, are you using an entreprise certificate?

**Comment by BlueJeans7** [comment]
> I don't know, the problem come from entreprise certificate for sure but idk why it work with UyouPlusExtra, will look into it

Certainly, thank you. Scarlet is currently accessible with a valid enterprise certificate using the direct method. Feel free to check it out.

**Comment by huandney** [comment]
I also had the same problem using Scarlet.

**Comment by merouane-tazeka** [comment]
I have the same issue but by self signing the app. But sideloading it using Altstore works just fine, but in Altstore I can't access the unlimited apps as my account is in an organisation

**Comment by xnymphie** [comment]
I am have the same issue as Mero. I just updated  refreshed the app today and was signed out due to changing my password.  When I put in my emails it says: Google couldn’t verify it’s safe.

v19.08.2-2.7

**Comment by Vel-San** [comment]
Having same issue here using SideStore - Google is working hard with the DMCA to block everything not official I guess?

**Comment by Balackburn** [comment]
> Having same issue here using SideStore - Google is working hard with the DMCA to block everything not official I guess?

Hello, you can use uYouEnhanced, login then reinstall YTLitePlus and it will already be logged, I don’t know why but uyouenhanced doesn’t have this issue.

**Comment by Balackburn** [comment]
Should be fixed https://github.com/YTLitePlus/YTLitePlus/commit/ae2957dfcb67b9be1f6a7d9527829e2654906594
