### ISSUE TITLE
[Bug] Empty space in subscription tab

### ISSUE THREAD

**Issue by gimmeamin** [YTLitePlus/YTLitePlus#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.1.1
- Device model: iPhone 12
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 18.46.3-2.4

### Describe the bug

Honestly not a big deal, just slightly annoying.

So I tested it and when you enable Hide Shorts (YTUnShorts), it does the job and hides all the shorts.

But when you open the subscription tab and scroll down a bit, there would always be an empty space that would glitch in, and glitch away when scrolling back up, then glitch back in when scrolling down again.

### Steps to reproduce the issue

1. >Settings
2. >YTLitePlus
3. >Miscellaneous
4. Enable Hide Shorts (YTUnShorts)

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
> @gimmeamin does the issue still persist in v18.48.3-2.4 (latest release)?
> 
> ![image](https://github.com/Balackburn/YTLitePlus/assets/79799243/8b337a70-3c30-43e5-be8e-55a282b4985f)
> 
> 

Yes

**Comment by Delamcode** [comment]
Personally I’d also like to have an option to leave shorts enabled in the subscriptions feed and disabled everywhere else, as shorts in subscriptions only come from creators you are subscribed to.

**Comment by Balackburn** [comment]
@Delamcode Good idea, this option is from https://github.com/PoomSmart/YTUnShorts you should do the request here.

Their is also an option from the YTLite tweak, you should make the request here :
https://github.com/dayanch96/YTLite

**Comment by Delamcode** [comment]
Done!

**Comment by Delamcode** [comment]
I would assume that something like https://github.com/PoomSmart/YTUnShorts/commit/3e6fab7f528ba4f320b527de8d0fb733b437db93 would work, although I’m not sure how the YouTube app works. This would also not give any options.

**Comment by ev0tto** [comment]
will fixed by this?

https://github.com/PoomSmart/YTUnShorts/issues/5

**Comment by Balackburn** [comment]
@ev0tto @gimmeamin  Yes it's finally fixed! 
https://github.com/YTLitePlus/YTLitePlus/commit/9bebcbbf7282aa0b4863c4d3b93d9b6f44dc0842

**Comment by ev0tto** [comment]
@Balackburn 
One of my accounts isn't working properly. Any idea why? I built and installed ytliteplus with the YouTube 19.18.2 ipa, and only enabled YTUnShorts.

https://github.com/YTLitePlus/YTLitePlus/assets/80548883/272e7817-ca80-4e36-b328-252c093919a0

**Comment by Balackburn** [comment]
@ev0tto What doesn't work? Are you referring to #116? Or is this another issue?

**Comment by Balackburn** [comment]
@ev0tto Their is two options, disable the one from YTLite, this one isn't updated and cause the gap bug enable the one from YTLitePlus only.

**Comment by ev0tto** [comment]
@Balackburn  
When there are shorts, I'm experiencing the same kind of blank spaces as before. However, this issue only occurs with one of my multiple accounts. As shown in the video, if I move to the post tab and then go back to the feed, the blanks disappear. Restarting the app causes the problem to recur. It's clear that the blanks occur where there are shorts. I enabled YTLitePlus only

**Comment by Balackburn** [comment]
@ev0tto Strange I don't know what could cause this sorry

**Comment by ev0tto** [comment]
I'm also not sure why it's happening only with certain accounts. It's not a big issue, so it's okay, I guess.

**Comment by talhah58** [comment]
Its still broken for me :(
