### ISSUE TITLE
[Bug] When I try to select the thumbnail of a short video on my phone, it turns black.

### ISSUE THREAD

**Issue by Cy9oz** [YTLitePlus/YTLitePlus#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:17.3
- Device model:iphone15
- Sideload tool (AltStore, Sideloadly, TrollStore,...):AltStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!):[v18.49.3-2.4]

### Describe the bug

When I try to select a thumbnail of a short video on my phone, the other frames are black!
I have to swipe my finger to the other frames to see them.

![bug-1](https://github.com/Balackburn/YTLitePlus/assets/106731312/f6bad9f6-51df-4ae3-bce4-9ed6c8d6b214)
![bug-2](https://github.com/Balackburn/YTLitePlus/assets/106731312/6fcae3fb-0c51-4d46-a4d4-b5a0ce115019)

### Steps to reproduce the issue

1. Upload a video
2. Select Thumbnail
3. It will be pitch black.

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by bhackel** [comment]
Not seeing this issue in the latest build, feel free to re-open the issue if you are still having issues.
