### ISSUE TITLE
[Bug] I can't login to my Youtube account in v19.08.2-2.7

### ISSUE THREAD

**Issue by TW527E** [YTLitePlus/YTLitePlus#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.3.1
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): SideStore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): latest

### Describe the bug

I can’t login my Google account in to YTLitePlus’s YouTube on this iPhone 13.
Old version (19.06.2-2.6.1) can’t too.
But on my previous phone, iPhone 8 Plus, it works very well.
![IMG_0116](https://github.com/Balackburn/YTLitePlus/assets/37478187/8e155925-ee12-483c-80d7-8f7d0e780857)

### Steps to reproduce the issue

1. Install by using SideStore 
2. Open it
3. Sign in
4. That screenshot

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Hello, unfortunately I don't know how to solve this issue at the moment, I made a new build with the latest version of Youtube today you can try it but I doubt it will fix your issue as I didn't changed anything in the YTLitePlus code I just updated the submodules and Youtube.

The only fix for now would be to switch to older version or maybe try another Tweaked ipa, can you connect with the latest version of uYouEnhanced?
https://github.com/arichornlover/uYouEnhanced/releases/tag/v19.08.2-3.0.3
If so please tell me, maybe it use a sideloading fix that I don't have.

**Comment by TW527E** [comment]
> The only fix for now would be to switch to older version or maybe try another Tweaked ipa, can you connect with the latest version of uYouEnhanced?
> https://github.com/arichornlover/uYouEnhanced/releases/tag/v19.08.2-3.0.3
> If so please tell me, maybe it use a sideloading fix that I don't have

I just tried your latest build, and it didn’t work, so I tried another Youtube you mentioned, which can log in normally. Maybe it really used some sideload patch that you didn’t use.

As I just said, another YouTube can log in normally, and then I installed YTLitePlus for him, but the account was not logged out,~~ is it a solution that doesn’t count as a solution? ~~

**Comment by Balackburn** [comment]
This is indeed an unanticipated workaround, I'll check if it uses a patch I don't have.

**Comment by drsudhanshu524440** [comment]
The only way to log in is to install another modded YouTube app like uYouEnhanced, sign in with your Google account, then uninstall it and reinstall YTLitePlus. You will automatically log in to your Google account now.

**Comment by samuelc02** [comment]
Thanks, I have the same problem and this workaround is the only thing that worked

**Comment by Balackburn** [comment]
Fixed 
https://github.com/YTLitePlus/YTLitePlus/commit/ae2957dfcb67b9be1f6a7d9527829e2654906594
