### ISSUE TITLE
[Bug] Crash when casting to youtube tv

### ISSUE THREAD

**Issue by Yunogamer** [YTLitePlus/YTLitePlus#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.4
- Device model: iPhone 14 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sidestore, Altstore
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.10.5-3.0.1

### Describe the bug

When pressing on a video to play on youtube tv, it loads and plays on tv fine, app on ios crashes, open again, return to the video and all is normal and works for that video, until  i try to load another and happens over and over... did it on last version too..

uYouplus does not have this problem.

### Steps to reproduce the issue

1. Enable cast to youtube tv
2. Play any video
3. ios app crashes

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Balackburn** [comment]
Thank you for the report will look into it

**Comment by Yunogamer** [comment]
bug remains 19.10.7_3.0.1

**Comment by Balackburn** [comment]
Could you try with YTLite alone or other tweaked Youtube app to see if this come from YTLitePLus only?
I don't have a TV to broadcast, so it's difficult for me to fix this problem.

**Comment by Yunogamer** [comment]
works fine with uYouPlus, YTLite is a mess and i dont understand how to build it..

install "Custom UserAgent String" for firefox or chrome, in extension options set like so:

URL: https://www.youtube.com/tv
UserAgent: Mozilla/5.0 (PlayStation; PlayStation 4/11.50) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15 (or any user agent that has youtube tv, ps4, any smart tv etc)
Domain: UNCHECKED
State: checked

with this any pc can have youtube tv like on a console etc by simply putting in www.youtube.com/tv, or just www.youtube.com for regular pc youtube. content filters/blockers also work since the pc is playing the video, the iphone is just the "remote".

**Comment by hobgoblin123** [comment]
Still broken. Anyway I can help with this?

**Comment by quoctrile8** [comment]
> Could you try with YTLite alone or other tweaked Youtube app to see if this come from YTLitePLus only?
> I don't have a TV to broadcast, so it's difficult for me to fix this problem.
I think this issue related to the “Playback quality on Wifi” and “Playback quality on Cellular” options in YTLite Advanced Mode.
When I set 2 options above to “Best” and cast to TV, YouTube app on my iPhone crashes.
When I set 2 options above to “Default” and cast to TV, everything is working fine.

**Comment by Yunogamer** [comment]
> > Could you try with YTLite alone or other tweaked Youtube app to see if this come from YTLitePLus only?
> > I don't have a TV to broadcast, so it's difficult for me to fix this problem.
> 
> I think this issue related to the “Playback quality on Wifi” and “Playback quality on Cellular” options in YTLite Advanced Mode. When I set 2 options above to “Best” and cast to TV, YouTube app on my iPhone crashes. When I set 2 options above to “Default” and cast to TV, everything is working fine. Tested with v19.16.3-3.0.1 - YTLitePlus.

quality does nothing, problem still remains. ill just stay with uYouPlus... though i like YTLitePlus better..

**Comment by Balackburn** [comment]
> > > Could you try with YTLite alone or other tweaked Youtube app to see if this come from YTLitePLus only?
> 
> > > I don't have a TV to broadcast, so it's difficult for me to fix this problem.
> 
> > 
> 
> > I think this issue related to the “Playback quality on Wifi” and “Playback quality on Cellular” options in YTLite Advanced Mode. When I set 2 options above to “Best” and cast to TV, YouTube app on my iPhone crashes. When I set 2 options above to “Default” and cast to TV, everything is working fine. Tested with v19.16.3-3.0.1 - YTLitePlus.
> 
> 
> 
> quality does nothing, problem still remains. ill just stay with uYouPlus... though i like YTLitePlus better..

I will look into it this week, I don't spend much time on YTLitePlus recently

**Comment by Yunogamer** [comment]
fixed in v19.21.3-4.0 ty
